### ISSUE TITLE
Configuration option for rounded borders

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#105]
Currently JWM always uses rounded window and button borders unless compiled without the shape extension.  A configuration option for the "radius" would allow differing degrees of rounded borders as well as square borders.

**Comment by Israel-** [comment]
Hi, could you specify the format?  My guess is that it is something like:
<WindowStyle>
  <Radius>0.75</Radius>
</WindowStyle>
Where 1.0 is square
though I suppose you could be using degrees
where 90 is square
Or,
It could also be
<WindowStyle radius="1.0">
</WindowStyle>

**Comment by joewing** [comment]
Radius is probably a poor choice for the name.  This is actually the width of the corner in pixels, so 0 or 1 is square and higher integers are rounded.

**Comment by joewing** [comment]
I decided to rename this to “Corner” to hopefully make it less confusing.

**Comment by Israel-** [comment]
Thank you!  Could you also update the release notes (it says Radius)
What is the upper limit for the amount of pixels?  is it based on the size of the titlebar?
For example if my titlebar is 32px a rounded corner of 40px would not work, correct (just an example)

I apologize if my many questions are overkill, I just want to make sure I understand fully how something works before beginning to incorporate it into my settings manager program.  This way I can make sure it is clear for the user.

**Comment by joewing** [comment]
Radius is in pixels, default is 4, valid values are 0 to 5.  That information is in the full documentation (http://joewing.net/projects/jwm/config.shtml).  I’m just lazy and only documented it in one place, otherwise I forget to update it when it changes, as is evidenced by the fact that the release notes still mentioned Radius instead of Corner.
