### ISSUE TITLE
Mouse bindings are not configurable

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#11]
There is currently no way to modify mouse bindings in JWM.

Debian bug: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=497465

**Comment by Israel-** [comment]
I have found that using the scrollwheel on my clock (I use zenity --calendar) opens multiple windows.
I think this could be a very useful option in the future!
Though simply allowing a tag to disable the scroll wheel interacting with JWM would suffice for most use cases I can think of.
Something like:
<Scrollwheel>false</Scrollwheel>
But still letting synaptics, or whatever handle the scrollwheel in applications, in other words only disabling JWM interacting with it.  Unless this interferes with scrolling window content.

**Comment by joewing** [comment]
I just checked in a fix to ignore the scroll wheel for clocks and tray buttons.  For now, I don’t see any reason to allow it and it’s a little annoying to clean up a whole bunch of windows if you accidentally scroll over the clock.

**Comment by Israel-** [comment]
Thank you!  This is something my wife likes least.  She does it when she is scrolling in a program, but moves the mouse accidentally to the top, where my tray with a clock sits.

**Comment by technosaurus** [comment]
Why not add the capability of binding a different exec for each mouse button... Exec[1-5]?
Doing so would not only fix this, but would allow tray-applet-like functionality without taking a lot of resources...
A volume applet could use exec1 to pop up master volume exec2 to pop up the full mixer, exec3 for advanced configuration and exec4/5 for volume up/down.

Bonus if it could redraw the icon, though I didn't see an obvious way to trigger redrawing just 1.

**Comment by joewing** [comment]
I really like that idea @technosaurus!  I opened a new issue for the TrayButton thing.  I think that could be done pretty easily.

**Comment by Israel-** [comment]
With this current state of things, is this still needed?
I would like to inhibit the scroll wheel from shading windows, and switching through the tasklist/pager
I also like @technosaurus Idea to implement some way to trigger a redraw of a TrayButton Icon... this coupled with some sort of customizable Popup window could bring a lot of functionality from scripts.
Especially with dynamic menus..

**Comment by Israel-D** [comment]
@joewing isn't this fixed now?

**Comment by joewing** [comment]
This is fixed now and in recent snapshots.
