### ISSUE TITLE
Enhancement: support tooltips for menu entries

### ISSUE THREAD

**Issue by AlisterH** [joewing/jwm#111]
It would be nice if JWM could support tooltips for menu entries.  e.g. people building their main menu from .desktop files could use the "Comment" field from the .desktop file.

**Comment by technosaurus** [comment]
I guess this didn't make it in to 2.3.3.  What is needed to get this done?

Tray buttons already support it, so the main code is there.   So the menu items need an extra property and some kind of default positioning???

**Comment by joewing** [comment]
2.3.3 isn't released yet, so there's still a chance I suppose.
I think the hardest part with implementing this would be routing the time notifications through to the menu and tracking the last mouse position and time of the last movement to know when to show a popup.  I don't think it would be difficult, but it's more than a few lines of code that would need to change.

**Comment by joewing** [comment]
So @technosaurus convinced me.  This is available as of snapshot 1302.  For example:
```xml
<RootMenu>
   <Program label="Terminal" tooltip="This is a tooltip">xterm</Program>
</RootMenu>
```
