### ISSUE TITLE
no key binding to send the current window to a different desktop.

### ISSUE THREAD

**Issue by valdoonicanlives** [joewing/jwm#119]
please consider adding this - its strange you can do it if you click on the title bar but not all of us like to use the mouse that much.

**Comment by Israel-** [comment]
Hi @joewing could you add the send keybindings to http://joewing.net/projects/jwm/release-2.3.shtml please.  Thanks for this new goodie!!

**Comment by joewing** [comment]
I must have missed this.  Anyway, the release notes have been updated now. Thanks!

**Comment by Israel-** [comment]
No problem!  One thing I noticed about this functionality, is that I expected the desktop to switch to the workspace I switched the window to.  I am not sure if this is the general consensus for this behaviour.  AFAIK this is the default behaviour in many DE.  It might be worth tying the switch desktop functionality to this as well.  Anyhow thanks for this new feature!

**Comment by joewing** [comment]
That would be an easy change.  I could see it working either way.  I guess ideally it should be possible to specify multiple actions for a key binding to allow it to be configured either way.

**Comment by Israel-** [comment]
It d be handy to assign multiple things to a keybinding.  I could see a lot of applications for that.  For instance you could set a key binding to open a series of programs.  And potentially you could chain things together, like open geany and maxleft, open the filemanager and max right, switch desktops and open the music player and maxleft open the web browser and max right.
That may far too complicated to actually implement, but the simplest form (moving the window and switching desktops) would be handy.  Though, as is it is a great improvement.

**Comment by TaylanTatli** [comment]
Is there anything like desktop# to send windows to specified desktop? like send#?

**Comment by joewing** [comment]
There is currently no key binding to send windows to a specific desktop, but there’s no reason such a thing couldn’t exist.  I opened #395 to address that.
