### ISSUE TITLE
some basic tiling?

### ISSUE THREAD

**Issue by valdoonicanlives** [joewing/jwm#120]
I notice Icewm and Fluxbox have some basic tiling. The ability to press a keycombo and or menu choice to make two open windows take half the screen each (side by side).

**Comment by joewing** [comment]
As of snapshot 1057, JWM supports max left, right, top, bottom via keybindings.
Are there any others that would be nice to have?

I would like to also make these available via the window menu, but I think that would make the menu a little large.  A customizable window menu is probably the solution.

**Comment by bbidulock** [comment]
Fluxbox and some others have buttons in the title bar that can be used for left and right.  Some allow combinations of control keys and mouse clicks on the maximize button to toggle the different forms of maximization.  There is a set of EWMH states for maximus left, right, top and bottom, allowing menu control from external pagers and panels.

**Comment by Israel-** [comment]
ou can also assign key combinations for some of these.
this is what I use...
```xml
    <Key mask="C4" key="Up">maxtop</Key>
    <Key mask="C4" key="Left">maxleft</Key>
    <Key mask="C4" key="Right">maxright</Key>
    <Key mask="C4" key="Down">maxbottom</Key>
    <Key mask="C4" key="v">maxv</Key>
    <Key mask="4S" key="Up">maxv</Key>
    <Key mask="C4" key="h">maxh</Key>
```
So you can split the screen fairly easily, you can maxright and maxleft (or top and bottom)
I generally maxleft and maxright.

**Comment by joewing** [comment]
@bbidulock, I couldn’t find EWMH states (in the 1.5 spec) for top/bottom/right/left maximization, only horizontal/vertical.  Is that a proposed update?  I would like to be able to give external programs the ability to control that.

Configurable mouse bindings and window buttons would be nice for this and a bunch of other things, so I think I’ll leave that for later.  I’m considering adding group options for this though.

**Comment by bbidulock** [comment]
Unofficial, unproposed extensions.  All the way back to twm there has been the "zoom" function that can be activated with a key.  Fluxbox has key bindings for left-half and right-half.  Metacity has key bindings for left, right, top and bottom.  Windows 7 does this by dragging the title bar to the appropriate edge of the screen.

So, I defined four new state atoms:

    _NET_WM_STATE_MAXIMUS_BOTTOM
    _NET_WM_STATE_MAXIMUS_LEFT
    _NET_WM_STATE_MAXIMUS_RIGHT
    _NET_WM_STATE_MAXIMUS_TOP

**Comment by vmnlopes** [comment]
Pytile can also do this http://sourceforge.net/projects/pytile/

**Comment by holmeslinux** [comment]
see also stiler in https://goo.gl/7a2nbb

vlw fwi, Holmes

**Comment by joewing** [comment]
There is support for max{top,left,right,bottom} in JWM 2.3, so I'm closing this.  Please feel free to open an issue for any additional requests for new features related to this or otherwise.
