### ISSUE TITLE
JWM tray 's border is not showing

### ISSUE THREAD

**Issue by the-scavenger** [joewing/jwm#143]
I am currently on JWM vgit-879 which doesn't have this problem , i tried updating to either latest git snapshot [10963e45c1] or the 976.tar.xz in the main site , after restarting X , the applications in the tray have no border separating them from each other , even after i increased the border value in the conf file , there is no change

**Comment by joewing** [comment]
There is now a "Border" tag in TrayStyle that allows you to specify the color of a tray border (as of revision 49033a5a).
