### ISSUE TITLE
background scaling

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#146]
Hi,
The backgrounds do not scale the way they used to in the older versions of JWM.
Is there an option (not listed in the config page) to 'stretch' the background?

The old behaviour was all bgs were stretched, but now they shrink to fix based on the width of the picture.  How can I get the old behaviour back again?

**Comment by Israel-** [comment]
Hi,
I was just wondering if this issue has been addressed in recent versions.
I have had a few testers ask about why the background looks out of place.
If it has been fixed in recent versions I will certainly update my packages to use the latest version.

I am increasingly impressed with JWM!  Thank you so much for this!

**Comment by joewing** [comment]
I just now commited a fix for this, so "stretch" should behave as it used to.  I also added a "scale" background type for anyone who would desire the newer behavior.

**Comment by Israel-** [comment]
You rock!  Thanks I'll pull the tar and repackage this!!
