### ISSUE TITLE
Keyboard shortcuts on login don't work until a window is opened

### ISSUE THREAD

**Issue by Sanchezman** [joewing/jwm#148]
My computer has a fresh install of JWM from the Arch official repository.

After logging in, I find that when I try to use any of my keyboard shortcuts to do things like open windows or switch desktops, none of them work.  Only when I have opened the JWM root menu by clicking and then selected some program from my menu can I now use shortcuts.  If I open the root menu but do not click on any programs contained in it, my shortcuts will not work.  Once I have opened this first window from the menu, I can close it and continue to use my keyboard shortcuts.

**Comment by joewing** [comment]
I think this should be fixed now, so I'm closing this.  Feel free to reopen if there's still a problem.
