### ISSUE TITLE
Disable Minimize button

### ISSUE THREAD

**Issue by blah43** [joewing/jwm#152]
I'm building a one app appliance using VirtualBox, Fedora Linux and JWM. Because of a VirtualBox seamless-mode limitation I'd like to disable the browser's Minimize Window button. Minimizing an application disappears it in the window mgr, which is hidden by the Seamless mode option - minimizing a window is effectively a one-way operation.

I can live without the minization option. Is there a JWM configuration option that can disable the button? (I've not found - or missed - an answer in the documentation, etc.)

Thanks,
Paul

**Comment by bbidulock** [comment]
All window managers that respect MOTIFY_WM_HINTS can be set to have no minimize button.  Just clear the MWM_FUNC_MINIMIZE bit in the MOTIF_WM_HINTS before mapping the window (or get your toolkit to do so).  What toolkit does it use?

**Comment by joewing** [comment]
It should be pretty easy to add a group option for this.  There is already a "noshade" option.  Something like "nomin" perhaps.  It might be good to add "nomax" and "noclose" also.
Of course, there are two aspects to this: removing the actual button and prohibiting the behavior.  I tend to think prohibiting the behavior is more useful (and hiding the button if the behavior is prohibited).

**Comment by blah43** [comment]
I agree that prohibiting the behavior is the better alternative. Ideally, the optional nomax and/or noclose would allow more of the flexibility that my project needs. Thanks for your help!!

**Comment by joewing** [comment]
I ended up adding nomin, nomax, noclose, nomove, and noresize since those were already supported internally, just not exposed through the configuration file.
