### ISSUE TITLE
--disable-icons results in error 

### ISSUE THREAD

**Issue by stali** [joewing/jwm#153]
stali@x61:~/jwm$ make all
cd src ; make all ; cd ..
make[1]: Entering directory '/home/stali/jwm/src'
gcc -c -g -O2 -I/usr/include/freetype2  -I/usr/include/freetype2   -DLOCALEDIR=\"/usr/local/share/locale\"  background.c
background.c: In function ‘LoadImageBackground’:
background.c:299:51: error: macro "LoadNamedIcon" passed 3 arguments, but takes just 2
    ip = LoadNamedIcon(bp->value, 0, preserveAspect);
                                                   ^
background.c:299:9: error: ‘LoadNamedIcon’ undeclared (first use in this function)
    ip = LoadNamedIcon(bp->value, 0, preserveAspect);
         ^
background.c:299:9: note: each undeclared identifier is reported only once for each function it appears in
Makefile:36: recipe for target 'background.o' failed
make[1]: *** [background.o] Error 1
make[1]: Leaving directory '/home/stali/jwm/src'
cd po ; make all ; cd ..
make[1]: Entering directory '/home/stali/jwm/po'
make[1]: Leaving directory '/home/stali/jwm/po'

**Comment by joewing** [comment]
Should be fixed now. Thanks!
