### ISSUE TITLE
Git repo doesn't merge well with current (rather old) Debian version

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#154]
I want to package the latest git version, as it includes the fix for background scaling, as well as some other nice options, but I am unable to do so.  2.2.2 from the [jwm homepage](http://www.joewing.net/projects/jwm/) works brilliantly.  however, I am wondering if something changed (the recent change today did not fix my issue) that I am unaware of... or if there is something remarkably different in the releases that is not present in the current git repo.  Any sort of help tracking down this issue would be most appreciated, as I want to have the latest JWM available, and have to option of continually updating it very easily.  Thanks so much!

**Comment by joewing** [comment]
What doesn't merge well?
If it helps, I have a list of changes from v2.2.2 here: http://joewing.net/projects/jwm/release-2.3.shtml
Also, I just updated the snapshot on joewing.net to have the head revision.

**Comment by Israel-** [comment]
There is some issue in the autoconf that I am not understanding.
building it using autoreconf && ./configure && make
works fine here.
However I get errors trying to build with pbuilder.  I tried using the original setup, but it failed.  So I am wondering what could have changed.  The debian/ubuntu version is 2.1.0+svn579
I figure the changes form 2.1.0 (s579) to 2.2.2 were not major enough to break autotools being used in the Debian process, but something has diverged significantly since then, as I am no longer able to simply merge things and rebuild.
Thanks for taking the time to reply to me, I really appreciate all you do!!

**Comment by Israel-** [comment]
I just brute-forced everything to work by tar-ing the directory and using it as upstream source.  I have been trying to contact the Debian maintainer for months to get a more recent version in.  Hopefully I can get in contact and get things updated, as the more recent version supports some very good features.  Thanks for humouring me.  Sometimes it just helps to get it out so I can find the solution.
