### ISSUE TITLE
Max Verticale Half screen

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#157]
I'd really like to have an option to have a window maximize on the right or left side of the screen.
Mainly so I could do something like
```
<Key mask="4A" key="Right">maxright</Key>
<Key mask="4A" key="Left">maxleft</Key>
```

**Comment by joewing** [comment]
This is a duplicate of issue #120 (though a slightly more limited request).
At some point I need to get a list of "tiling" features together and prioritize them.  I imagine these mappings would be pretty high.

**Comment by joewing** [comment]
JWM now (as of snapshot 1057) supports “maxleft”, “maxright”, “maxtop”, and “maxbottom” key bindings to maximize to half of the screen.
