### ISSUE TITLE
[jwm1026] Logic error raising the tray

### ISSUE THREAD

**Issue by jdoe0154** [joewing/jwm#158]
I just upgraded from jwm1016 to jwm1026. I have a dual-monitor setup, with an autohiding tray at the bottom of the left-hand screen. Initially the tray wouldn't autohide, which was easily repaired by changing the tray's setting in the configuration file from "autohide=true" into "autohide=bottom". Then the tray showed (on mouse-over) and hid as expected, at the bottom of the left-hand screen.

Unexpectedly, switching between windows with Alt-Tab leads to a different behavior. This key combination normally makes the tray pop up (on key press) and hide (on key release) at its regular place (left screen / *bottom*). With jwm1026, the tray pops up (on key press) at the correct place, but then "hides" (on key release) at the *top* of the left screen. "Hides" is in quotation marks because it shall describe only the temporal sequence; the tray actually is and stays fully visible there.

Next I recompiled jwm1026 with "./configure --enable-debug", and then got a more interesting result: rather than hiding at the wrong place after Alt-Tab, the code now hits the "Assert(0)" in the function "HideTray":

DEBUG: ASSERT FAILED: tray.c[641]

The rest from here on is speculation:

I have not fully followed the new code logic yet. The function "RaiseTrays" in tray.c logically ORs the variable tp->autohide (with would hold the value THIDE_BOTTOM = 4 in my use case) with the constant THIDE_RAISED (which is 8). The variable stays at that value until LowerTrays() is called; I don't know by what, and when. In any case, something else than LowerTrays() seems to call HideTrays() first --  while tp->autohide still has the THIDE_RAISED mask bit set. Perhaps a regular, clock-based time-out? The switch statement in HideTray() would handle (THIDE_BOTTOM), but has no case for (THIDE_BOTTOM or'ed with THIDE_RAISED), and therefore falls through to the default case, which is the "Assert(0)".

**Comment by joewing** [comment]
I just left off a check for the case when the tray is raised due to an event other than mouse-over (which is where the THIDE_RAISED comes into play).  It shouldn't attempt to hide the tray when that flag is set.
This should be fixed now.
Thanks!

**Comment by joewing** [comment]
As a side note, I think this is probably a long-standing bug, but it was much less severe in older versions (it would have just made the tray "flicker").
