### ISSUE TITLE
All maximized apps maximize behind tray

### ISSUE THREAD

**Issue by willbprog127** [joewing/jwm#160]
Every maximized app's bottom edge maximizes beyond the top of the tray.  The expected behavior is to have the bottom edge of the maximized app touch the top edge of the tray (when the tray is at the bottom, of course).  

The red arrow in the image below shows that the bottom scroll button has gone below the tray after Firefox is maximized:
![jwm-maximize-issue-01](https://cloud.githubusercontent.com/assets/1296250/5970841/2c569a2a-a7ee-11e4-85d6-3785a9bc08cf.png)

-
:information_source: 
Git version: 85ffabca6eb7f4b062d8031fde815cdef4728261
OS: FreeBSD 10.1 - AMD 64
Compiler: clang

**Comment by willbprog127** [comment]
Issue also confirmed on Ubuntu 14.04 LTS.

**Comment by joewing** [comment]
This should be fixed in snapshot 1040.
Thanks!

**Comment by willbprog127** [comment]
@joewing Thank you very much! :smile:
