### ISSUE TITLE
please add nofullscreen Option for Group

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#163]
Hi,
I just found an interesting bug (may have been previously reported).
I am using pcmanfm for my desktop icons, and when there are no open windows, if I press my fullscreen key combo, the  desktop becomes fullscreen (the Tray becomes hidden).
If there is already an option to do this in the interim releases, please advise me what Option to use (and which tag to build from).
Thanks!!

**Comment by joewing** [comment]
The “nofullscreen” option is available as of snapshot 1057.
