### ISSUE TITLE
Fullscreen windows pushed "below" when 2 or more trays are used

### ISSUE THREAD

**Issue by just22** [joewing/jwm#169]
Hello,

I noticed that using multiple trays (e.g., one as panel and the other for reserving some space on the top of the screen), the "fullscreen" action doesn't work as expected: the window is expanded, but it is pushed below all the other ones.

The problem should be easily reproducible (I'm using JWM 2.2.2, OpenBSD 5.7-current), if that's not the case I'll try to report more details concerning my configuration.

All the best

**Comment by joewing** [comment]
By pushed below, do you mean in the stacking order or in the x-y plane?  The way maximization is implemented, windows will not maximize over trays unless the trays are in a layer below the window being maximized.

**Comment by just22** [comment]
Hello Joe,

the window that I want in fullscreen is maximized, but it ends up covered by all the other opened (and not iconic) windows, and the trays are over it too. So this is definitely related to the stacking order.

The problem disappear when I use only one tray.

**Comment by joewing** [comment]
I’m having some trouble reproducing this.  Does it only happen with a particular program?  If not, would you mind sending me your JWM configuration?  It might be worth a shot to see if it still happens with a recent snapshot of JWM to see if the problem is still there.

**Comment by just22** [comment]
Hi Joe,

it happens with all applications (I tried xterm, xpdf, mplayer and a bunch of others).

This is my .jwmrc (along with a couple of schots that show the problem):

<?xml version="1.0"?>

<JWM>

    <StartupCommand>
        conky -x 0 -y 1 -c ~/.config/conky/conkyrc-statusline
    </StartupCommand>

    <StartupCommand>
        /usr/local/libexec/tray-app/sound -i
    </StartupCommand>

    <StartupCommand>
        /usr/local/libexec/tray-app/eject -i
    </StartupCommand>

    
    
    <RootMenu height="12" onroot="12">
       <Program icon="terminal.png" label="Terminal">xterm</Program>

       <Menu icon="folder.png" label="Applications">
          <Program icon="editor.png" label="Dia">dia</Program>
          <Program icon="www.png" label="Firefox">firefox</Program>
          <Program icon="gimp.png" label="Gimp">gimp</Program>
          <Program icon="mail.png" label="Mutt">
             xterm -e mutt
          </Program>
          <Program icon="word-processor.png" label="Open Office">
             ooffice
          </Program>
          <Program icon="chat.png" label="Pidgin">pidgin</Program>
          <Program icon="music.png" label="Rhythmbox">rhythmbox</Program>
          <Program icon="development.png" label="Xilinx ISE">
             /usr/local/xilinx/bin/ise
          </Program>
          <Program icon="video.png" label="Xine">gxine</Program>
       </Menu>
       <Menu icon="folder.png" label="Utilities">
          <Program icon="calculator.png" label="Calculator">xcalc</Program>
          <Program icon="font.png" label="Fonts">xfontsel</Program>
          <Program icon="viewer.png" label="Magnify">xmag</Program>
          <Program icon="programs.png" label="Synaptic">
             gksudo synaptic
          </Program>
          <Program icon="window.png" label="Window Properties">
             xprop | xmessage -file -
          </Program>
       </Menu>
       <Separator/>
       <Program icon="lock.png" label="Lock">
          xscreensaver-command -activate
       </Program>
       <Separator/>
       <Restart label="Restart" icon="restart.png"/>
       <Exit label="Exit" confirm="true" icon="quit.png"/>
    </RootMenu>

    <Group>
       <Name>xterm</Name>
       <Option>icon:terminal.png</Option>
       <Option>iignore</Option>
    </Group>

    <Group>
       <Name>xconsole</Name>
       <Option>desktop:6</Option>
    </Group>

    
    <Tray x="0" y="-1" height="20" autohide="false">

       <TrayButton label="Start" popup="">root:1</TrayButton>

       <TrayButton icon="desktop.png" popup="Show desktop">showdesktop</TrayButton>

       <TrayButton icon="media-removable.png" popup="Show removable media contents">exec:xfe /vol</TrayButton>

       <TrayButton icon="media-playback-start.png" popup="Play link in clipboard">exec:ytdl-smplayer $(xclip -o)</TrayButton>

       <TaskList maxwidth="0"/>

       <Dock/>

       <Spacer width="5"/>

       <Pager labeled="true"/>

       
       

       <Clock format="%a %d/%m (%V) %R">xclock</Clock>

       <TrayButton icon="system-suspend.png" popup="Suspend">exec:apm -z</TrayButton>

       <TrayButton icon="system-hibernate.png" popup="Hibernate">exec:apm -Z</TrayButton>

    </Tray>

    
    <Tray insert="right" valign="top" halign="center" border="0" height="15" autohide="false"/>


    

    <WindowStyle>

       <Font>DejaVu Sans-8</Font>
       <Width>2</Width>
       <Height>18</Height>

       <Active>
          <Text>white</Text>
          <Title>#70849d:#2e3a67</Title>
          <Outline>black</Outline>
          <Opacity>1.0</Opacity>
       </Active>

       <Inactive>
          <Text>#aaaaaa</Text>
          <Title>#808488:#303438</Title>
          <Outline>black</Outline>
          <Opacity>0.5:0.9:0.1</Opacity>
       </Inactive>

    </WindowStyle>

    <TaskListStyle>
       <Font>DejaVu Sans-8</Font>
       <ActiveForeground>black</ActiveForeground>
       <ActiveBackground>gray80:gray90</ActiveBackground>
       <Foreground>black</Foreground>
       <Background>gray90:gray80</Background>
    </TaskListStyle>

    
    <TrayStyle>
       <Font>DejaVu Sans-8</Font>
       <Background>gray90</Background>
       <Foreground>black</Foreground>
       <Opacity>0.75</Opacity>
    </TrayStyle>

    <PagerStyle>
       <Outline>black</Outline>
       <Foreground>gray90</Foreground>
       <Background>#808488</Background>
       <ActiveForeground>#70849d</ActiveForeground>
       <ActiveBackground>#2e3a67</ActiveBackground>
    </PagerStyle>

    <MenuStyle>
       <Font>DejaVu Sans-8</Font>
       <Foreground>black</Foreground>
       <Background>gray90</Background>
       <ActiveForeground>white</ActiveForeground>
       <ActiveBackground>#70849d:#2e3a67</ActiveBackground>
       <Opacity>0.85</Opacity>
    </MenuStyle>

    <PopupStyle>
       <Font>DejaVu Sans-8</Font>
       <Outline>black</Outline>
       <Foreground>black</Foreground>
       <Background>yellow</Background>
    </PopupStyle>

    <ClockStyle>
       <Font>DejaVu Sans Mono-8</Font>
    </ClockStyle>

    <IconPath>
        /usr/local/share/icons/hicolor/48x48/apps
    </IconPath>

    <IconPath>
        /usr/local/share/icons/gnome/48x48/places
    </IconPath>

    <IconPath>
        /usr/local/share/icons/gnome/48x48/apps
    </IconPath>

    <IconPath>
        /usr/local/share/icons/gnome/48x48/actions
    </IconPath>

    <IconPath>
        /usr/local/share/icons/gnome/48x48/devices
    </IconPath>

    <IconPath>
        /usr/X11R6/include/X11/pixmaps/
    </IconPath>

    
    
    <Desktops width="6" height="1">
       
       <Background type="gradient">#073642:#586E75</Background>
    </Desktops>

    
    <DoubleClickSpeed>400</DoubleClickSpeed>

    
    <DoubleClickDelta>2</DoubleClickDelta>

    
    <FocusModel>sloppy</FocusModel>

    
    <SnapMode distance="10">border</SnapMode>

    
    <MoveMode coordinates="off" delay="0">outline</MoveMode>

    
    <ResizeMode coordinates="off">outline</ResizeMode>

    
    <Key mask="4"  key="#">      desktop#</Key>

    
    <Key mask="4" key="w">       close</Key>
    <Key mask="4" key="m">       maximize</Key>
    <Key mask="4" key="minus">   minimize</Key>
    <Key mask="4" key="f">       fullscreen</Key>
    <Key mask="4" key="Tab">     next</Key>

    
    <Key mask="4" key="space">   root:1</Key>
    <Key mask="4" key="l">       window</Key>


    
    <Key mask="4"  key="F1">     exec:xterm -e "man jwm"</Key>
    <Key mask="S4" key="F2">     exec:</Key>
    <Key mask="S4" key="Return"> exec:xterm</Key>
    <Key mask="S4" key="t">      exec:xterm -e "tmux attach-session -d || tmux new-session"</Key>
    <Key mask="S4" key="b">      exec:chrome</Key>
    <Key mask="S4" key="d">      exec:arandr</Key>
    <Key mask="S4" key="s">      exec:apm -z</Key>
    <Key mask="S4" key="h">      exec:apm -Z</Key>
    <Key mask="S4" key="m">      exec:iExec xterm -title "Mail client" -e mutt</Key>
    <Key mask="S4" key="f">      exec:xfe</Key>
    <Key mask="S4" key="p">      exec:transmission-gtk</Key>
    <Key mask="CA" key="Delete"> exec:xloxk</Key>

    
    <Key mask="4"  key="t">      exec:change-perfpolicy</Key>

    
    <Key key="Up">up</Key>
    <Key key="Down">down</Key>
    <Key key="Right">right</Key>
    <Key key="Left">left</Key>
    <Key key="Return">select</Key>
    <Key key="Escape">escape</Key>

</JWM>


![before_fullscreen](https://cloud.githubusercontent.com/assets/6371186/7106350/ad680d6e-e13d-11e4-8f00-4a54f8ed3573.png)
![after_fullscreen](https://cloud.githubusercontent.com/assets/6371186/7106351/b5d16158-e13d-11e4-9629-56c380bc9708.png)

**Comment by bbidulock** [comment]
I noticed this a while back too, but with JWM's tray at the bottom and a separate EWMH tray at the top.  Might be a bug in work area calculations.  With regard to stacking, wmspec-1.5 says that fullscreen windows with the keyboard focus are to be stacked above all other (normal) windows.

**Comment by joewing** [comment]
I think this is working now. Feel free to re-open if it's still broken.
