### ISSUE TITLE
Add the ability to show a menu from a clock tray component.

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#174]
Currently, it is possible to run a command when a clock tray component it clicked.  It should be possible to run a command just like with a tray button.  Supporting this would break backwards compatibility.

**Comment by joewing** [comment]
Clock tray components are configured the same way as tray buttons as of snapshot 1092.

**Comment by Israel-** [comment]
Joe you are amazing!

**Comment by joewing** [comment]
@Israel-, I know :smile:
That should work.  It’s also possible to just put “exec:xclock” in the body without the Button tags to get the same behavior as before.

**Comment by Israel-** [comment]
:smile: 
Great!  Once I rebuild I will test it out.  I will have to add another check into my settings program, but it is nice to get these features in as they occur, as it gives me time to troubleshoot.
Thank you!
