### ISSUE TITLE
Tray Vertical layout TrayButton issues

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#176]
I am having a bit of issues with a vertical Tray.

I have tried a few variants... but I think this *might* be a bug
For example:
```xml
<Tray layout="vertical" valign="center" halign="left" width="0" height="0">
  <TrayButton icon="/usr/share/ardour2/icons/ardour_icon_22px.png" popup="Ardour Digital Audio Workstation">exec:/usr/bin/ardour2</TrayButton>
  <TrayButton icon="audacious.svg" popup="Audacious">exec:audacious </TrayButton>
</Tray>
```
The buttons are laid out horizontally
The Tray is only a few pixels in height and the icon width in width
Try as I may... it seems nearly impossible to figure out how to automatically make it nicely display vertical tray buttons.

I have tested changing the width and height, and adding a spacer, halign="fixed"... nothing works

I am having this issue in 1074, but AFAIK this hasn't been mentioned since then (though I may have missed it, or forgotten).

I will test in 1092 and report any other findings

**Comment by Israel-** [comment]
still the same in 1092 unfortunately

**Comment by joewing** [comment]
JWM wasn’t properly computing the height of tray buttons when there was no label.  This should be fixed in snapshot 1099.

**Comment by joewing** [comment]
Make that snapshot 1101 (I pushed to the wrong branch).

**Comment by Israel-** [comment]
Ok, I will update and test this to confirm it is fixed!  Thanks so much!!

**Comment by Israel-** [comment]
In my first bit of testing everything works great!!
I will do some more intensive testing, but my initial impression is that it works exactly as desired!
Thank you @joewing

**Comment by Israel-** [comment]
AFAIK this bug is fixed
