### ISSUE TITLE
SVG icons 

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#177]
Hi,
I am not entirely sure when this issue crept in...
![iconissue](https://cloud.githubusercontent.com/assets/4912582/7497119/2bc1acee-f3de-11e4-855a-93fdba1b9f63.png)
But now certain SVG icons are displaying very oddly...
(Places folder/ web icon)
The main issue is random garbage being displayed behind the SVG.
(Places has black garbage, Web icon has yellow garbage)
This was definitely NOT present in 1064
I do not think it existed in 1074

it existed in 1092 (I think) and 1101

**Comment by joewing** [comment]
This should be fixed in snapshot 1102.  Thanks!

**Comment by Israel-** [comment]
AFAIK this is indeed fixed!
Thanks so much Joe, you are extremely quick!
Your user support is tremendous!!

**Comment by Israel-** [comment]
I just found a small issue... it seems the icons disappear when the panel autohides and I suspend.
I am also using xcompmgr so I will try to narrow down what is causing it.  I will reclose this if the bug is xcompmgr

**Comment by Israel-** [comment]
Unfortunately I think this is an xcompmgr issue...
I will reopen if I find the issue is related to suspending and autohiding

**Comment by Israel-** [comment]
Hi, I am not sure how to solve the issue of non-existent icons when using a compositor.
I have used both xcompmgr and compton (which is an xcompmgr fork) but have not had any success in fixing this.  The issue occurs when I am using a Tray with autohide.  
![compton](https://cloud.githubusercontent.com/assets/4912582/8968932/f437a8e0-3605-11e5-954f-bfcab2fcbae1.png)
(ignore the screenshot window blur in the background...)

**Comment by Israel-** [comment]
this is fixed as of 1260!
