### ISSUE TITLE
Allow modifiers to be used as both modifiers and keys

### ISSUE THREAD

**Issue by wdlkmpx** [joewing/jwm#178]
- Default: false
- [WinMenu]true[/WinMenu]

In most Keyboards there is a WinKey: SUPER_L SUPER_R. 

When pressed & released, it will display the main Menu. It's like clicking the Menu button.

Such behavior is not possible in JWM, at least when I try to tweak the configuration. The WinKey can not be used alone.

What I did was configure Ctrl+Super_L to call a script. This script moves the cursor to where the menu button is located and simulates a click.
- [Key mask="C" keycode="115"]exec:jwmmenuclick[/Key]

By implementing this simple feature JWM will become more friendly to newbies.

**Comment by Israel-** [comment]
This is a good idea!

However, 2 major things.
1 This is already used as a modifier, so it would have to differentiate between modifier and press, as I like it as a modifier and probably many others do as well

2 it should be extendible, where you could use root:n or exec:program

**Comment by joewing** [comment]
With key bindings, it’s already possible to raise a root menu with “root:n” or a window menu with “window” as the action.  So it seems to me the only thing missing is being able to use a modifier by itself as a key binding.  Or am I missing something?

**Comment by Israel-** [comment]
No, I think you have it.
But will it still be possible to do something like:
```xml
<Key key="4">root:n</Key>
<Key mask="4" key="Up">exec:myscript</Key>
```
4 is the Super (win), at least on all my computers

**Comment by joewing** [comment]
Probably don’t want to allow “mask” settings in the “key” attribute, since “4” would be ambiguous.
So maybe adding the ability to do:

```xml
 <Key mask=“4”>root:n</Key>
```

and still support using “4” as a modifier by only doing the action on release of the modifier if no other key was pressed.  This may not be easy to implement though, I’m not sure.

**Comment by Israel-** [comment]
Ah... yeah... maybe it would be easier to do something like:

```xml
<Key key="Super">mask:4</Key>
<!--- more stuff -->
<Key key="Super">root:5</Key>
```
Though that might also make problems....

**Comment by joewing** [comment]
I’m able to use, for example, Control_L (I lack a windows key) with “key=“, but currently that prevents control from being used as a modifier.  I would think the same situation would exist for Super_L/R.

So the following works:
```xml
<Key key=“Control_L”>root:1</Key>
```
but, the following does not work:
```xml
<Key key=“Control_L”>root:1</Key>
<Key mask=“C” key=“w”>window</Key>
```

Unfortunately, making a modifier key behave as both a modifier and a regular key is a bit tricky the way things are currently implemented.  Certainly would be nice to have though.

**Comment by yetanothergeek** [comment]
FWIW, the Windows&trade;  default keybinding for displaying the "Start" menu on keyboards without a "Windows" key is `Ctrl+Esc`.

That's what I got accustomed to way back in '95 and I still use it today:
```xml
<Key mask="C" key="Escape">root:1</Key>
```

**Comment by wdlkmpx** [comment]
Well, "root:n" does does display the JWM menu, but it's placed in the top left of the screen.

JWM config

	
	
	<Key keycode="116">exec:jwmmenuclick</Key>
	<Key mask="C" keycode="115">exec:jwmmenuclick</Key>

To make it look fancy I wrote this script

	#!/bin/sh

	while read line ; do
		if [[ $line == *\** ]] ; then
			for word in $line; do res=$word ; break ; done
		fi
	done <<< "$(xrandr -q 2>/dev/null)"

	screenheight=${res#*x}

	xdotool mousemove 10 $((screenheight-10)) click 1 mousemove restore

Explanation:
Move cursor to the bottom left of the screen, generate a click event, then return the cursor to its original position.
