### ISSUE TITLE
Icon filenames extentions (strictly declared or not)

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#181]
Would it be possible to use icon names like
firefox
rather than firefox.png or firefox.svg or firefox.xpm
but also to use
/usr/share/pixmaps/firefox.xpm
or
firefox.svg

This would be nice if the user switches icon paths to a series of icons that use a different extention, and also to be able to explicitly set the type of icon wanted

**Comment by wdlkmpx** [comment]
This a very important feature, it would put JWM in the major leagues..

I guess this would be desired behavior:

If icon file extension is specified, then look for that specific file in [IconPaths]

This would increase processing time, but:

If icon extension is specified and icon file is not found then, look for the same file with other extension. svg: png, xpm | png: svg xpm | xpm: png xvg

If icon file extension is not specified then, look for icon.png, icon.xpm & icon.svg in [IconPaths]

In Puppy, there is a script that automatically generates a JWM menu from the info in /usr/share/applications/*.desktop files... when installing *.deb files or external packages, most of them come with this entry

icon=program [no ext]

So, definitely, this would be greatly welcomed.

**Comment by wdlkmpx** [comment]
I really don't know how this is implemented in the JWM code, but this specific behavior could be implemented in a new function.

And a new configure switch, something --enable-intensive-icon-search. Maybe this should be de default, so --disable-intensive-icon-search.

So, depending on the configuration, one can choose a heavier JWM.

This is what happens in lxp-icewm, it starts smoothly, but before displaying the menu for the first time, it just consumes the CPU for a couple of seconds, which means that it must be searching and loading the icons...

**Comment by Israel-** [comment]
I already do this in my menu script, but I thought it might be nice to have as a general feature for all the icons.
I think the big issue is:
would the benefit of having such a flexible WM outweigh the possibility that it gets heavier?

Unless of course it would only check when jwm -restart (or reload might be nicer) was called then the memory savings would be the same, and only need a bit more, and more cpu cycles to check when it was told to.

**Comment by Israel-** [comment]
I would say this issue is resolutely solved thanks @joewing
