### ISSUE TITLE
[jwm1102] Keyboard shortcut crashes the empty desktop

### ISSUE THREAD

**Issue by jdoe0154** [joewing/jwm#182]

**Comment by jdoe0154** [comment]
To toggle windows between maximized and normal state I have the following keyboard shortcut in the configuration file:

    <Key mask="A" key="Return">maximize</Key>

Pressing that shortcut when no windows are open (that is, on the blank desktop) leads to a segmentation fault, ending jwm and Xorg. The effect can be provoked both easily and reliably. It also happens by accident when starting X (which by default shows a blank desktop here), then as the first activity starting f. ex. a terminal with a keyboard shortcut, and following up immediately with the above shortcut before the terminal actually shows up.

The issue is easily avoided by "shielding" the KEY_MAX handling in the function HandleKeyPress in event.c a bit better. See the patch below which solves the issue for me: it simply adopts the "shielding" technique for the KEY_MAX case that is used by JWM already for the KEY_STICK case.

```
--- jwm-1102/src/event.c
+++ jwm-new/src/event.c
@@ -479,10 +479,12 @@
       }
       break;
    case KEY_MAX:
-      if(np->state.maxFlags) {
-         MaximizeClient(np, MAX_NONE);
-      } else {
-         MaximizeClient(np, MAX_HORIZ | MAX_VERT);
+      if(np) {
+         if(np->state.maxFlags) {
+            MaximizeClient(np, MAX_NONE);
+         } else {
+            MaximizeClient(np, MAX_HORIZ | MAX_VERT);
+         }
       }
       break;
    case KEY_MAXTOP:
```

**Comment by joewing** [comment]
This should be fixed for max (and related key bindings) in snapshot 1103.
Thanks!

**Comment by jdoe0154** [comment]
Yes, snapshot 1103 has fixed it. Thank you!
