### ISSUE TITLE
[jwm1104] Pager shows noisy pixel pattern at startup

### ISSUE THREAD

**Issue by jdoe0154** [joewing/jwm#184]
Since commit 87ed281940af87d897f5f7b1d3d5464f9943cdf5 the pager in my auto-hiding tray shows a noisy pixel pattern initially -- that is, when starting X to a blank desktop and making the tray pop up. See the screenshot below. It is a different pattern each time, and happens reproducibly 100%.

The pixel pattern is replaced with the regular pager view after I start some program, click on the pager with the mouse, or manually switch to a different desktop with f. ex. the key combination Alt-2. The random pattern comes back when restarting JWM from the menu (which has a "Restart" entry in its configuration).
![Uploading pager_noise.png…]()

**Comment by jdoe0154** [comment]
Sorry, picture upload did not work immediately ...

![pager_noise](https://cloud.githubusercontent.com/assets/4623911/8142568/352460c4-1170-11e5-8103-694dfe493f1b.png)

**Comment by 01micko** [comment]
Yep, me too, but disappears as soon as a window is opened, so was tricky to get a shot.

![noise](https://cloud.githubusercontent.com/assets/1019119/8142885/a1aa5bc4-11d2-11e5-8ada-69460d1747e2.png)

**Comment by joewing** [comment]
This should be fixed as of snapshot 1107.

**Comment by 01micko** [comment]
Thanks! Fixed for me.

**Comment by jdoe0154** [comment]
Snapshot 1107 fixes it for me too. Thank you! Closing the issue.
