### ISSUE TITLE
Focus issues with virtual keyboards

### ISSUE THREAD

**Issue by 01micko** [joewing/jwm#185]
It seems virtual keyboards maintain the focus and don't allow typing in any text area.

`xvkbd`isn't too bad because it has a focus button so you can choose a window to type in.

`cellwriter` and `matchbox-keyboard` don't work at all however on the same system both work in open-box.

Hitting the letters on the virtual keyboard seem to do nothing at all. I have no idea where the events end up, but since the respective programs have the focus I suspect the events are fed back to the parent. 

Of course, this makes JWM fairly useless on a touch-screen enabled device.

**Comment by joewing** [comment]
This should be fixed as of snapshot 1107. Thanks!

**Comment by 01micko** [comment]
Works for me in all keyboards I mentioned :-)

Thanks for a speedy response.
