### ISSUE TITLE
Issues with `<Dynamic>` tag

### ISSUE THREAD

**Issue by 01micko** [joewing/jwm#188]
Couple of problems.

- it needs a label or else "Dynamic" shows up as the label

- it does not respect menu heights

A simple screen shot and my code -

```
<RootMenu label="1" labeled="false" height="24" onroot="3">
<Dynamic label="Bookmarks" icon="about.svg" height="24">exec:$HOME/.jwm/root_menus/menu3</Dynamic>
</RootMenu>
<RootMenu label="2" labeled="false" height="24" onroot="2">
<Dynamic label="Main Menu" icon="puppy.svg" height="24">exec:$HOME/.jwm/root_menus/menu2</Dynamic>
</RootMenu>
```

![screenshot1](https://cloud.githubusercontent.com/assets/1019119/8448433/d1ff2570-200a-11e5-8751-82a33c95dc66.png)

Thanks

**Comment by 01micko** [comment]
I suppose the first one is not really an issue, but is there a simple solution for the second one? Maybe each entry needs the menu height specified? Hmm.. maybe its me...

**Comment by 01micko** [comment]
Ok, seems that `<Dynamic>` should support heights to me. I can work around it with an unlabelled `<Menu>` in my script ( @zigbert 's script actually)  but it's not ideal as we get the arrow in between "Bookmarks" and the menu. We have a similar script for the main menu with the same effect.

**Comment by joewing** [comment]
It should support heights and the default label was just an artifact of how it was implemented.  Both should be fixed in snapshot 1149.

**Comment by 01micko** [comment]
Thanks!

I'll give 1149 a spin shortly.

**Comment by 01micko** [comment]
Yep, fixed for me, thanks! Closing.
