### ISSUE TITLE
Customizable window button placement

### ISSUE THREAD

**Issue by alexbib** [joewing/jwm#19]
Hi, I've looked without success into placing the min max and close window button on the left of windows, or even better for me, on cloning them so they're both at the top left and top right.  Maybe it's already possible and I just don't know how.

Fluxbox and Icewm handle this in a quite elegant way, where you can specify something like

TitleButtonsLeft="xmi"
TitleButtonsRight="s" 

where x is close, m is maximise, s is shade, etc.

Anyways, thanks a lot for all the work on this awesome window manager!
Alex

**Comment by joewing** [comment]
This is supported as of snapshot 1628.
The option is `TitleButtonOrder` with the following options:
* m Maximize button
* i Minimize (iconify) button
* t Window title
* w Window menu button
* x Close button

So you could do:
```xml
<TitleButtonOrder>wtimx</TitleButtonOrder>
```
to get the default layout.

**Comment by Israel-** [comment]
@joewing This is awesome!  You rock!
It works great for me

**Comment by Israel-** [comment]
@joewing wait... I am having an issue with the buttons actually reacting.  The pictures are correct,
however they are not responding at all... :frowning_face:

**Comment by Israel-** [comment]
@joewing They are not working at all, even if that Tag is not included.... something broke here

**Comment by joewing** [comment]
@Israel- I would guess that you're missing mouse bindings, which are now required (see #11 and #386).  You can copy them from the default configuration [see here](https://github.com/joewing/jwm/blob/master/example.jwmrc#L195).

**Comment by joewing** [comment]
As an aside, I'm still undecided on how to handle the upgrade path from 2.3 to 2.4 in this regard.  Though more config changes are likely going to sneak in, so it might be more obvious in the future.

**Comment by Israel-** [comment]
@joewing aha... I must have missed that one... you have done a lot recently.
It might be nice to default to those common values if nothing is defined.... otherwise you might have a slew of users who think the upgrade broke something.
Yes it is completely working now.
When you add this to the docs, please include that bit of info (even if you go for the auto defaults route)

**Comment by gouthamsanthosh** [comment]
> This is supported as of snapshot 1628.
> The option is `TitleButtonOrder` with the following options:
> 
> * m Maximize button
> * i Minimize (iconify) button
> * t Window title
> * w Window menu button
> * x Close button
> 
> So you could do:
> 
> ```
> <TitleButtonOrder>wtimx</TitleButtonOrder>
> ```
> 
> to get the default layout.

@joewing Where should I put the above code? Is it in the .jwmrc file
