### ISSUE TITLE
showdesktop command makes me lose control over the keyboard

### ISSUE THREAD

**Issue by wdlkmpx** [joewing/jwm#191]
showdesktop command makes me lose control over the keyboard

I'm using jwm git 20150719

I'm having this issue since this month I think.

This is the configuration I'm using:

	<Key mask="4" key="d">showdesktop</Key>
	<Key mask="4" key="m">showdesktop</Key>
	<TrayButton popup="Show Desktop" icon="mini-desktop.xpm">showdesktop</TrayButton>

I barely use the mouse, so it's easy for me to notice this.

When I press Win+M all windows are minimized or whatever, I see the ROX desktop (the same thing happens when I click the desktop icon) and I am unable to use the keyboard anymore, unless I click a button in the taskbar.

Then I press Alt+Shift and I switch between the taskbar buttons, Win+E launches ROX, etc. Then I Press Win+M and all windows are minimized or whatever, I see the ROX desktop and I am unable to use the keyboard anymore, unless I click a button in the taskbar.

**Comment by joewing** [comment]
I think this should work better now.  Now JWM assigns keyboard focus to the root window if the window with the keyboard focus is minimized when showing the desktop.  I'm not sure if it's the correct solution, but it appears to fix it for me.

**Comment by wdlkmpx** [comment]
Yes, it also fixes for me. So I'm closing this. Thanks Joe!
