### ISSUE TITLE
Tray Outline color = Foreground color?

### ISSUE THREAD

**Issue by wdlkmpx** [joewing/jwm#193]
I have these settings

	<Tray autohide="false" insert="right" x="0" y="-1" border="0" height="28" >
	<TrayStyle>
	<Outline>#222222</Outline>
	<Foreground>red</Foreground>
	<Background>#222222</Background>
	<Active>
		<Foreground>white</Foreground>
		<Background>#484E60</Background>
	</Active>
	</TrayStyle>
	
I'd like to hide the outline or apply to it the same color as the Background color

Here is a screenshoot so you can see what I see, maybe I'm missing something?

![capture26228](https://cloud.githubusercontent.com/assets/10052849/8917255/9196fdd0-34e3-11e5-8ee9-440680daa921.png)
![capture26589](https://cloud.githubusercontent.com/assets/10052849/8917258/97e0a754-34e3-11e5-94da-1af64eab7411.png)

**Comment by joewing** [comment]
As of snapshot 1191, this should work again by setting "Outline".

**Comment by joewing** [comment]
Make that snapshot 1192...

**Comment by wdlkmpx** [comment]
Yes. Thanks Joe!

![Uploading capture8624.png…]()


By the way, the Outline tag in PopupStyle is mentioned in the man page, but JWM says it's an invalid tag

JWM: warning: /****/.jwm/jwmrc-theme[37]: invalid tag in PopupStyle: Outline

**Comment by Israel-** [comment]
This may be similar, but menus now have an outline.  I tried using the same
```xml
<MenuStyle>
  <!-- more -->
  <Outline>#383838</Outline>
</MenuStyle>
```
but this does not work in 1192

**Comment by joewing** [comment]
MenuStyle/Outline and PopupStyle/Outline should both work as of snapshot 1196.
Thanks!

**Comment by Israel-** [comment]
I am using 1198 (just upgraded) and this still doesn't work...

**Comment by joewing** [comment]
This seems to work for me... Is it possible the wrong version of JWM is running or it's using the wrong configuration?

**Comment by Israel-** [comment]
```
$ apt-cache policy jwm
jwm:
  Installed: 1198-0~36~ubuntu15.04.1
```
So this means it is 1198... my configuration is above... did I implement it wrongly?
jwm -p
gives no feedback at all, so jwm is reading it correctly for me.

My menu is dark coloured and the text is white (I cannot take a screenshot while it is open)
The outline is the same colour as the text... so maybe if your text is the colour of the outline it looks fine to you?  It is very noticeable to me...

```
$ jwm -v
JWM v2.3.2 by Joe Wingbermuehle
compiled options: confirm fribidi icons jpeg nls png shape svg xbm xft xinerama xpm xrender 
system configuration: /etc/system.jwmrc
```
this of course wont show the github version...
I am going to update my PPA with 1206 and try that when it builds.
https://code.launchpad.net/~israeldahl/+archive/ubuntu/jwm
in case you want to look at my branch (or if anyone is running Ubuntu and wants the most up-to-date... let me know and I will build for distributions other than 15.04 if needed)

**Comment by joewing** [comment]
I copied your MenuStyle into my configuration and I get a black border with white text (I'm now using 1206, but it worked the same way with 1198).  Here's a screen shot:

![menu](https://cloud.githubusercontent.com/assets/1285008/8998668/19625ce6-36f6-11e5-8ec2-9b84ef04cb1c.png)


It is possible to have multiple MenuStyle's defined, in which case JWM will take the last one.

**Comment by joewing** [comment]
Status windows were still using the foreground color for the border.  That should be fixed now.

**Comment by Israel-** [comment]
HA!  I just figured restarting JWM (jwm -restart) would use the new version... apparently I kept trying to refresh the old version... It does work... sorry for the false positive. Thanks for fixing this.  Next time I will log out and log back in, such a silly mistake sorry.

**Comment by joewing** [comment]
Ah yes, I've done that before.  Usually I just run JWM from an xterm and restart it there for development.  I've also been known to add an "Exit" menu entry that runs jwm.

**Comment by Israel-** [comment]
Yeah, I've been doing so much testing, and I have been fixing my JWM settings manager program to work with the current version (as well as older ones too still). I have also been testing a gtkmenu-standalone program to try to use it with JWM (and a few other things) so I just forgot to log out since I had so much going on.  That I and I guess I just figured jwm -restart would restart JWM totally... though it is more like jwm -reload, since it uses the currently running JWM and reloads it.
Anyhow thanks for fixing it so quickly!!  I look forward to testing out 1206 soon :)
