### ISSUE TITLE
flickering borders

### ISSUE THREAD

**Issue by mrfricks** [joewing/jwm#195]
hi joewing,

i'm using the snapshot 1215 on puppylinux.
if i open 2 windows and move the front window around, the thin border that surrounds the second window flickers, like it's continually being redrawn.

this doesn't happen in 976

**Comment by joewing** [comment]
This should be better in snapshot 1217.
Thanks!

**Comment by mrfricks** [comment]
1217 fixes the issue for me .. no more flickers

thankyou
