### ISSUE TITLE
EFL applications not being drawn in the desktop

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#199]
not shure if it his a jwm issue or an efl issue will drop it here anyways.

i am running manjaro linux with 4.1 kernel!

jwm 2.3.1.2

:elementary elm_sys_notify.c:318 _name_owner_get_cb() Eldbus Error: org.freedesktop.DBus.Error.NameHasNoOwner Could not get owner of name 'org.freedesktop.Notifications': no such name

**Comment by joewing** [comment]
JWM doesn't currently have anything to do with D-Bus.  I would guess that's the issue.

**Comment by vmnlopes** [comment]
the weird bit his wen i hit the external task switcher the terminal window is there and it appears in the screen if i click it.
it does not show in jwm task list or in the screen just by launching the application.

works fine on xfce and budgie, this needs further testing i will do it wen i get some free time.

**Comment by technosaurus** [comment]
Jwm doesn't handle notifications.  You can run a separate notification provider though.  It might be possible to model something after the clock widget to accept "notifications" and display them as tooltips or popups as Joe calls them.
It may be doable if a script/program could trigger an action, but that tag may need an "id" property and a socket for communication... as long as dbus doesn't become a hard dependency.
I wrote a gtk2 app called "simple icon tray" that could instead be used for such purposes (and many others)... Just add a dbus daemon to write notifications to the icon's tooltip file... I'd have to look up the protocol at ? standards.freedesktop.org ?

**Comment by vmnlopes** [comment]
@joewing @technosaurus done a bit more testing this morning and it seems EFL applications are not drawn in the desktop or appear in jwm task swicher i run them from the terminal and did not had anything about dbus being spit out except for terminology. 

changed the title of the issue to EFL 

but wen using 3 party task switcher in this case skippy-xd the applications appear in there and wen i click them they appear in the screen.

tested applications:
terminology
eflete
enventor
elementary-test

**Comment by joewing** [comment]
I think this should be fixed now.
JWM wasn't mapping (or minimizing) windows that had initial_state in WM_HINTS set to Withdrawn.

**Comment by vmnlopes** [comment]
tested in snapshot 1233 EFL works fine!
