### ISSUE TITLE
VirtualBox does not take focus for keyboard input

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#201]
I am using VirtualBox to test ISO of Ubuntu-based distro with JWM.
In other DE VirtualBox takes all the keyboard input focus.
Issue:
Ctrl+Alt+T opens a terminal in VirtualBox in other DE, in JWM it opens a Terminal on the host computer

**Comment by joewing** [comment]
I think this should work better now.  I'm not sure why JWM was grabbing the keys on windows, but I don't think it should be necessary.  Let me know if you run into any problems.
Thanks!

**Comment by Israel-** [comment]
Yes, thank you this works much better now!!
Do you think you could make another point release soon, as I think some of the fixes you have done (especially the fix for the menu showing Include or Dynamic ) are very important usability issues.  The icon search path feature is also very good, as well as this VirtualBox fix.

**Comment by joewing** [comment]
I plan to do a release of 2.3.2 very soon.  Hopefully within the next week or so.

**Comment by Israel-** [comment]
Awesome!  I really appreciate it Joe, thank you!!
