### ISSUE TITLE
Dynamic Menu Timeout

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#203]
Currently dynamic menus allow JWM to run an external program to load menu contents as needed.  If the program takes to long to return, JWM will hang.  One solution is to add a timeout so that JWM doesn't hang.

Another possible solution is to have JWM show a temporary menu until the dynamic menu finishes loading.  This would require running the menu generation program asynchronously.  This would probably end up being more work than a timeout, but probably more desirable too.

**Comment by Israel-** [comment]
Actually if there are enough dynamic menus that take too long JWM crashes

**Comment by Israel-** [comment]
@joewing 
Would it be possible to extend Dynamic to function similar to Include
```xml
<Dynamic root=true>exec:/path/myscript</Dynamic>
```
To remove the submenu nature.  Then this ignores label and icon making, since it would generate nothing.
Instead of creating the current equvalent jwmrc xml
```xml
<Menu label=$label icon=$icon>
<!- script output -->
</Menu>
```
I looked at the code a bit, but I need to find out where all the functions are before I can attempt any thing major.

**Comment by joewing** [comment]
I don’t think it would take too much effort to make it possible to have dynamic top-level menus, but unfortunately, it’s not a trivial change either.  I think the way to implement it would be to restructure things a bit such that top-level menus looked like menu actions, which can be dynamic menus.  I’ll open a separate issue for this.

**Comment by Israel-** [comment]
Thanks, I think my main timeout issue has been trying to dynamically generate each category of applications causes somewhat of an overload, which ultimately crashes JWM and kills it.

**Comment by Israel-** [comment]
I am having an issue with multiple Included menus that come from an exec:
that is relevant to this issue.
I have 4 included executable menus and one dynamic menu from an executable.
I find that sporadically some do not list, and it is rather unpredictable which one will not list.
If I reload JWM (via jwm -restart) I do get the menus I am missing.
I have one perl script and 3 bash scripts that generate these menus.
The perl script is used once as an include and once as a dynamic.
The dynamic menu always loads perfectly fine, albeit a bit slowly sometimes.
Can the timeout for Included menus be increased easily?

**Comment by joewing** [comment]
There is no timeout right now.  JWM will wait forever.  However, if a script spews enough output, it can crash JWM by causing JWM to run out of memory.  Of course, neither situation is ideal and there should be both a configurable timeout and a limit on memory usage.

Another issue that could arise is a syntax error in the generated XML from a script.  JWM will log errors, but depending on how things are set up, those errors may not be easy to find.

**Comment by Israel-** [comment]
@joewing Where is this logged to?  that may help find the issue.
If JWM waits for ever, I cannot explain why my menu is not populated.  When I click on the traybutton there is nothing there.  There must be some sort of hidden issue with this that is causing my odd problem.
I have plenty of memory on this computer (7.92 G) and with all the things I have open I am using less than 1 G currently.

I have also found that if I use `cat` in a script that will always will crash jwm, but not if I use cat in the exec portion of jwm.  I have not tried this with simple small on menu item files, but the file I cat is only 16.8KiB so it shouldn't be an issue of memory, or at least I do not think it should.

Please point me in whatever direction to go to look for info, or things to test, as I really like being able to make a menu for anything I want (in theory).

**Comment by joewing** [comment]
JWM logs to stderr, so you can try redirecting that to a file or check where X is logging its output.  My usual trick is to run JWM from an xterm.

It shouldn't be possible to crash JWM by feeding it configuration (other than running it out of memory).  I'll have to look into that.  If you can provide the stack trace from gdb, that would be helpful, but I'll try reproducing it myself.

**Comment by joewing** [comment]
There is a timeout as of snapshot 1659.
