### ISSUE TITLE
Run a command when changing desktops

### ISSUE THREAD

**Issue by codesardine** [joewing/jwm#206]
JWM 2.3.1.2
Background type="image" does not work in conjunction with Background type="command"

``` javascript
<Background type="image"> this tag his not working wen we also use the command tag</Background>
<Desktop>
    <Background type="command">notify-send "Desktop 1"</Background></Desktop> 
   <Desktop>
    <Background type="command">notify-send "Desktop 2"</Background></Desktop> 
   <Desktop>
    <Background type="command">notify-send  "Desktop 3"</Background></Desktop> 
   <Desktop>
    <Background type="command">notify-send "Desktop 4"</Background></Desktop>
```

I think a best approach will be?

``` javascript
<Background type="image">/home/username/Videos/jwmwalpaper.png</Background>

<Desktop><Command>notify-send "Desktop 1" </Command></Desktop>
 <Desktop>
    <Command>notify-send "Desktop 2" </Command><
    <Background type="image">override background tag on the top for desktop 2</Background>
</Desktop> 
   <Desktop>
       <Command>notify-send  "Desktop 3" </Command>
       <Background type="image">override background tag on the top for desktop 3</Background>
    </Desktop> 
   <Desktop><Command>notify-send "Desktop 4" </Command>/Desktop>
```

**Comment by joewing** [comment]
I believe this is working as designed. The outside "Background" tag is a default and JWM expects the command to set the background, so it won't set the background to the default if it runs a command to do so.  I could see wanting a command to run when JWM switches the desktop, but as you mention, that would be a new feature.

**Comment by technosaurus** [comment]
Is Command run every time that desktop is switched to?  If so, that's pretty simple; just run a script that uses some-tool ( ... there are too many to mention) to set the background then notify-send.  Jwm seems to start much faster and use less resources with no background or just solid colors anyhow (my Xvesa + jwm initramfs uses only ~2mb combined)

**Comment by vmnlopes** [comment]
the command tag his one of the most useful tags in jwm a allows me to start an kill applications just by switching desktop or even systemd services i could write a scrip to do all that and set the desktop background that's not an issue.

what i mean is the tag itself could be more descriptive all it does his running command from the shell
and <Background type="command"> suggest even from the documentation (A command to be run for setting the background) .

I get what the tag does you guys get it too, but how about some guy messing with the configuration that only knows XML i just tink it could have some improvements here syntax wise?

**Comment by technosaurus** [comment]
@vmnlopes Many people don't like mixing csv with their xml
My jwm tools use a flat config file with csv and convert it to xml.

**Comment by vmnlopes** [comment]
@technosaurus  i guess it goes down to personal preference .

**Comment by codesardine** [comment]
The background tag works just fine to run scripts, closing this issue
