### ISSUE TITLE
Dealing with translations inside jwmrc, Question maybe Feature

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#207]
We can do manual tray buttons, menus, popups etc but how we deal with translations inside the XML issue https://github.com/joewing/jwm/issues/197 might sort that out with scripting any ideias?

**Comment by 01micko** [comment]
Most distros use some sort of menu generator so it is really up to the
developer of said menu generator and the distro maintainer.

**Comment by vmnlopes** [comment]
i have a menu generator in python i guess all i need to do is build a tray button generator that manages the translations for the poups and am good to go @01micko tanks.

I think this issue can be closed @joewing

**Comment by Israel-** [comment]
gettext works with many languages.  So there may be a way to use gettext to translate things, like having a shell script start things and pull in the right word for different things.
