### ISSUE TITLE
How to tell JWM to rather switch to another virtual desktop?

### ISSUE THREAD

**Issue by graemeg** [joewing/jwm#209]
As the subject says. Is there a way to **tell JWM not to bring a window from another Virtual Desktop to the current one**. I use 4 virtual desktops and arrange them always the same so I instantly know where my email client, web browser and dev apps are. But if I click say a URL link in an email, then JWM will bring the web browser from another virtual desktop into the current one. I have to then manually drag my browser back to the virtual desktop where it belongs.

**Comment by vmnlopes** [comment]
I cant see any option that does that in http://www.joewing.net/projects/jwm/config.shtml#groups.

You can try sticky or desktop tag but i doubt they will work most probably this is a bug!

**Comment by joewing** [comment]
There was a similar request a while back (issue #108).  JWM does have the desktop group option, but it will only cause the application to open on the specified desktop, not force it to remain on that desktop.  So when an application requests to be activated, JWM moves it to the current desktop.  I think the solution would be to add a group option to specify that an application is fixed to it’s desktop and/or an option to cause JWM to switch desktops when an application is requests focus.

**Comment by graemeg** [comment]
Yes, Issue #108 seems similar. What I would like is the last part you mentioned "an option to cause JWM to switch desktops when an application is requests focus.".

**Comment by dumblob** [comment]
I would also prefer the second solution (*an option to cause JWM to switch desktops when an application requests focus*).

**Comment by joewing** [comment]
There is a new group option, `fixed`, as of snapshot 1431 to address this.

**Comment by joewing** [comment]
I think this should be resolved now, so I'm closing this issue.  Please let me know if something still doesn't work right.
