### ISSUE TITLE
how to disable rounded windows?

### ISSUE THREAD

**Issue by graemeg** [joewing/jwm#210]
Somewhere I upgraded JWM (I think 3 years ago) under FreeBSD, and since then I have rounded corner windows. I really don't like that, but lived with it. I thought now to ask if there is actually a way to switch that off so I can get rectangular windows again.

**Comment by vmnlopes** [comment]
copy system.jwmrc to your home folder, rename to .jwmrc edit < WindowStyle> tag and you good to go!
```javascript

<WindowStyle>
    
        <Font>Source-9:bold</Font>
        <Width>1</Width>
        <Height>40</Height>
        <Corner>20</Corner> <--set corner to 0

**Comment by graemeg** [comment]
I was still on JWM 2.2.2 (latest in FreeBSD 10.1's ports system) which I don't think had the <corner> property. I manually upgraded my JWM to 2.3.1 from Joe's website, and then set the <corner> to 0. Many thanks for the help.

I see much of of the .jmwrc file format has changed... busy working through that now - based on the default system version.

**Comment by Israel-** [comment]
@graemeg 
You can use the xsltproc file Joe includes
```
cp ~/.jwmrc ~/.jwmrc.old
xsltproc jwm-2.3.xslt ~/.jwmrc.old > ~/.jwmrc 
```

**Comment by graemeg** [comment]
@Israel- many thanks for that tip, I didn't know about that.

**Comment by Israel-** [comment]
no problem @graemeg I am not sure if it updates it to remove the now obsolete (TaskListStyle PagerStyle, etc...)  so if not...  check here:
http://www.joewing.net/projects/jwm/release-2.3.shtml
This lists the major changes... but you may already have seen that
