### ISSUE TITLE
Startup (screen blanking)

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#213]
Hi... I have a script that does some nice things.
It looks through my $XDG_CONFIG_HOME/autostart directory and runs the programs (unless Hidden or OnlyShowIn make it not want to)
It also runs
```
xset s off
xset dpms 0 0 0 
```
I have a logging system for it, and it tells me that it ran the programs and set the screen blanking off.
However,  pidof <program_that_is_supposed_to_be_running>
is non-existent.
And of course... the screen blanks.
So, does JWM run everything in the script before it starts, or do I start too fast, or.....  some other things work fine (such as volumeicon)
How do I overcome this issue??
I'm running github version 1230... though I am upgrading to 1233 currently.

**Comment by joewing** [comment]
JWM runs the startup commands after connecting to the X server and reparenting any existing windows, etc.  JWM does not wait for the commands to complete, it's as if you ran them via a menu.

**Comment by Israel-** [comment]
hi... it was a bit of an issue with the script AFAIK...  I will keep testing things, and if I find there is an issue with JWM I will report back.

**Comment by Israel-** [comment]
@joewing sorry to bring up an old issue again, however I was wondering if there was a way to programatically prevent the screen blanking from happening using the X11 libraries inside JWM.
If a user wants a screen saver (if they have an older CRT monitor) they can use a screen saver.]

**Comment by joewing** [comment]
I think this is something that's best handled via the X11 configuration (for Xorg, the "BlankTime" option in xorg.conf).

**Comment by Israel-** [comment]
Thanks Joe, it just seems like something most DE handle automatically, so I thought I'd suggest it.
To me it seems like setting the dpms off and screenblanking off as default makes more sense LCD monitors/laptop screens don't really need the screensaver to be on (except to conserve power of course), as they don't burn the image into the screen like the old CRT monitors did.
I will continue using xset
Thanks for all the amazing work you do!
