### ISSUE TITLE
Issues with window maximazing (LXTerminal, Sakura, ROXTerm only)

### ISSUE THREAD

**Issue by wdlkmpx** [joewing/jwm#218]
These 3 terminal emulators refuse to maximize, it's like the window is saying: this is wrong so I'll go back to my previous state.

I think I've traced the origin of the problem.

This happens since commit https://github.com/joewing/jwm/commit/f538f75e8c4ef186ba2660b2af7a0e31f55a9a9d

The key file is src/place.c

I've been testing s1051, s1053(ORIGIN) and s1247

In s1051 there are issues with window maximizing, however LXTerminal does maximize.
In s1053 there are issues with window maximizing

s1051 & 1053: geany search dialog is BIG, pcmanfm confirm dialogs have incorrect size

s1247: EVERYTHING OK but LXTerminal windows don't maximize.

===============
place.c
===============

So, after undoing and redoing every change, I think the issue happens here:

Line 844

	   /* If maximizing vertically, update height. */
	   if(flags & MAX_VERT) {
		  np->y = box.y + north;
		  np->height = box.height - north;

 
If I remove '- north'

	   /* If maximizing vertically, update height. */
	   if(flags & MAX_VERT) {
		  np->y = box.y + north;
		  np->height = box.height;

And compile again... LXTerminal windows maximize, though maximized windows now have incorrect height

**Comment by wdlkmpx** [comment]
I copied the wrong comments, should be "/* If maximizing vertically, update height. */" (I fixed that), but it's certainly line 844, place.c

Line 844

Now I'm playing with random numbers to see if anything happens. Something like:

	np->height = box.height - north + 8;
	np->height = box.height - north + 10;
	np->height = box.height - north + 16;
	np->height = box.height - north + 20;
	np->height = box.height - north + 28;

But LXTerminal would maximize only if I remove '- north'

	np->height = box.height;

Obviously this is beyond my comprehension

**Comment by wdlkmpx** [comment]
In JWM there 3 options to maximize a Window:

Maximize
Maximize-x (horizontally)
Maximize-y (verically)

LXTerminal maximizes horizontally, the issue is a vertical maximizing.

**Comment by wdlkmpx** [comment]
No errors occur if I replace 'place.c' (s1247) with the one from s1051. 

It looks ok. There have been many fixes elsewhere. So basically this is just working without the issues present in s1051 (QtWeb whould not maximize (or unmaximize?) correctly.. it was a mess. some dialogs having the wrong size, etc).

The borders flicker when I resize a Window. There might be some important regressions, but everything looks OK right now.

So if this issue (I mean rebellious libvte windows) remains unfixed for some time, perhaps it would  be a good idea to use the "place.c" file from s1051, apply some fixes... and that would be it. 

So at least for me, JWM is complete and is my favorite window manager, the most lightweight, the fastest, the one and only. I'll be using it for the next years and beyond. Thanks Joe!

**Comment by joewing** [comment]
Thanks for narrowing this down.  I think it's finally fixed!

**Comment by joewing** [comment]
This fix is available in snapshot 1257.

**Comment by joewing** [comment]
This appears to be fixed now (for me at least), if there's still a problem, please re-open.

**Comment by mrgreenlinux** [comment]
I am having a similar problem with Lxteminal, if I use Group/ Option to maximize then when term opens it simply snaps back to top left corner. Did try 'st' terminal and it works fine.

` <Group>
      <Name>lxterminal</Name>
      <Option>maximized</Option>
   </Group>
`
