### ISSUE TITLE
Dialogs windows in the taskbar

### ISSUE THREAD

**Issue by aleksandr-samusenko** [joewing/jwm#222]
"Some other" window managers for main windows which are "dialogs" display button in the task bar - for example, nm-connection-editor, xfce4-power-manager, mate-power-manager and so on - have buttons in taskbar. JWM does not display the buttons for these windows. Freedesktop(.org)'s standards do not require explitcitly display the button for these window's type, but nevertheless, it would be good to make similar? Correcting patch is very easy -  delete one line in func. ReadWindowState (in hint.c):
.
.
.
   status = JXGetWindowProperty(...ATOM_NET_WM_WINDOW_TYPE...);
.
.
.
         } else if(  state[x] == atoms[ATOM_NET_WM_WINDOW_TYPE_DIALOG]) {
            result.border &= ~BORDER_MIN;
//-- (delete this line)            result.status |= STAT_NOLIST;
            break;
         } else if(  state[x] == atoms[ATOM_NET_WM_WINDOW_TYPE_MENU]) {
.
.
.
So, "main" dialog windows will be like "normal" windows (except maximize/minimize buttons).

**Comment by joewing** [comment]
This seems reasonable to me, especially now that it’s possible to group windows in the task bar.

**Comment by joewing** [comment]
This is fixed in snapshot 1271.
