### ISSUE TITLE
Add a README for upgrading when conf needs to be updated

### ISSUE THREAD

**Issue by cicku** [joewing/jwm#224]
Hi,

Fedora jwm current maintainer here. I'm not sure if it's useful, but it'd be better to create a new readme like README.Upgrading, and documents notes like 2.2 to 2.3.

Idea?

**Comment by joewing** [comment]
Sounds like a good idea.  I'll try to get that in and maintained for the next release.

**Comment by joewing** [comment]
I added README.upgrading.  It's pretty simple for now (the fewer places I have to maintain the full release notes the better).  Please let me know if there is anything else of interest that I should add to it.
