### ISSUE TITLE
Window closing if user click middle button of mouse  in taskbar on client 

### ISSUE THREAD

**Issue by roandbox** [joewing/jwm#232]
Please add window closing if user click middle button of mouse  in taskbar on client.
Patch file:
```
diff -cr jwm-2.1.0/src/taskbar.c jwm-roand/src/taskbar.c
*** jwm-2.1.0/src/taskbar.c 2012-01-21 17:39:19.874691527 +0000
--- jwm-roand/src/taskbar.c 2012-01-21 18:07:43.204610350 +0000
***************
*** 257,262 ****
--- 257,269 ----
              FocusGroup(entry);
           }
           break;
+       case Button2:
+          if (entry) { 
+            ClientEntry *cp;
+            for (cp = entry->clients; cp; cp = cp->next) 
+               DeleteClient(cp->client);
+          }
+          break;
        case Button3:
           ShowClientList(bar, entry);
           break;
```

**Comment by yetanothergeek** [comment]
This is somewhat dangerous, if a clumsy user like me accidentally middle-clicks a task. ( I just lost about 15 minutes work, but it could have been much worse! ) Please revert this, or at least make it optional.

**Comment by joewing** [comment]
I don't have a strong opinion on this, but I can see how it can cause problems.  The binding isn't particularly intuitive from my perspective, so I'll revert it.  Making bindings more configurable is something I plan to implement.
