### ISSUE TITLE
Allow exclude for <WindowStyle>

### ISSUE THREAD

**Issue by ScrumpyJack** [joewing/jwm#239]
WindowStyle affects every window, including desktop manager window. It would be nice to exclude window or a group of windows.

Example: Window manager: <b>JWM</b>, Desktop Manager: <b>PCManFM</b>
 ```
<WindowStyle>
 <Active>
  <Opacity>1.0</Opacity>
 </Active>
 <Inactive>
  <Opacity>0.4</Opacity>
 </Inactive>
</WindowStyle>
```
pcmanfm also changes opacity on/off focus

How to exclude pcmanfm from WindowStyle in this case?

**Comment by technosaurus** [comment]
Is there something missing in http://joewing.net/projects/jwm/config.shtml#groups that you need for pcmanfm?

**Comment by ScrumpyJack** [comment]
Thanks for your response. However, I'm not sure how relevant the link to jwm groups config is to my issue. The fact that I used pcmanfm in the example is incidental. Replace pcmanfm with xterm in the above if it helps.

In short, I would like to exclude items (for example xterm) from ```<WindowStyle>```

Let me know if it's unclear, and I'll try to rephrase it.

**Comment by Israel-** [comment]
@ScrumpyJack you have a typo see below:
```xml
    <Group>
        <Name>pcmanfm</Name>
        <Option>opacity:1.0</Option>
    </Group>
```
it is a : not =

**Comment by ScrumpyJack** [comment]
You're right, my bad, that was a typo. It's correct in my config though.

**Comment by technosaurus** [comment]
Sometimes the name an app advertises is not what you would expect.  Try using xwininfo to see what it says it is, sometimes the command line you run is a symlink or wrapper script or the app specifically sets a different name or class (rox-filer comes to mind)

**Comment by ScrumpyJack** [comment]
If I add
```    
<Group>
     <Name>mate-terminal</Name>
        <Option>opacity:1.0</Option>
        <Option>notitle</Option>
 </Group>
```
I have no terminal title bar, but the terminal still changes opacity during active/inactive transition

**Comment by technosaurus** [comment]
Hmm it sounds like maybe the opacity values are cumulative.  I wonder if setting the default value to 30% and the group setting to 30% would make it look like ~10%?... I don't know that part of the code well.
Fwiw pcmanfm/rox do this for good reason... they can set the root window in the same process that has file manager windows .  You probably wouldn't want the root window to be translucent.
 I don't know, I tend not to use settings like this that use additional resources ... I even use a flat background color and sometimes add an image with the same color background in a borderless tray.

**Comment by ScrumpyJack** [comment]
Thanks for all your suggestions so far. 
I'm not sure I follow. What is the default opacity? In my case, it's either 0.4 (inactive window) or 1.0 (active window).

**Comment by ScrumpyJack** [comment]
Ok, I updated to 2.3.2 and opacity:1.0 inside a group works!

I still have a few problems with layers, but I'll save that for later
