### ISSUE TITLE
motif look

### ISSUE THREAD

**Issue by LastOfBrunnenG** [joewing/jwm#245]
<MenuStyle decorations="motif">

Above doesn't seem to be doing anything at the moment. Menu looks exactly the same as 'flat' style. I suppose the small arrows which point to sub menus should have motif "carved in" look.

I happen to be fan of 'retro' UNIX things, particularly motif. I still use programs like xcalc and xpdf.

**Comment by joewing** [comment]
The ```decorations=“motif”``` attribute should be valid for MenuStyle, WindowStyle, and TrayStyle.  For trays and menus, it only makes the border 3-d (doesn’t change the arrows).  For windows, it makes the border 3-d and makes adds “handles”.
Making the arrow 3-d in addition certainly would be possible, but isn’t implemented yet.
