### ISSUE TITLE
Make the default window icon configurable

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#246]
JWM now displays a "square" if there is no application-specific icon specified.  This default icon should be configurable.

**Comment by joewing** [comment]
Fixed as of snapshot 1355.

**Comment by technosaurus** [comment]
Naming stuff is hard.  The current fix sounds like a default tray button for root menus... Window or title icon would fit better for this usage; however it would be great to have a configurabe, generic, default icon.
 The xdg specifications list an icon- missing icon in the naming spec that would be a good example in the documents accompanying the source code.

**Comment by joewing** [comment]
I like the current name since it’s consistent with the others: ButtonMin, ButtonMax, ButtonMaxActive, ButtonClose, and ButtonMenu (to show the window menu).
A default for root menus would make sense, but I think it would be called something else, perhaps DefaultIcon under TrayStyle?  Really, I think the ButtonX options should go under WindowStyle, but that would break compatibility.
