### ISSUE TITLE
Individual properties for trays/menus

### ISSUE THREAD

**Issue by technosaurus** [joewing/jwm#247]
Currently many of the properties of trays/menus are set as child nodes.
I realize this would introduce further incompatibilities in addition to previous changes to `<Active>`, but IMHO it would be more intuitive/simpler and allow more functionality if they were properties.

Here is the proposal for Tray components

``` xml
<TrayStyle
    group="true"
    decorations="flat"
    background="#000"
    foreground="#FFF"
    active-background="#777"
    active-foreground="#FFF"
    outline="#FFF"
    opacity="0.1"
    active-opacity="1.0"
/>
```

...similar properties for individual trays.

Note: that opacity could be included in the color components instead as rgba (background images using their alpha values), so that xrender (if enabled) could handle the opacity.

Note2: previous discussion has shown interest in supporting tablets/phones... having a tray be mostly translucent until "grabbed" rather than hidden would be an effective solution; however the main tray may want to be always viewable or with different background, so add per tray bg/fg settings

The struct would look something like this (slightly reordered for efficiency and packing)

``` c
/** Structure to represent a tray. */
typedef struct TrayType {
   struct TrayType *next;  /**< Next tray. (should be 1st) */

   /** Start of the tray components. */
   struct TrayComponentType *components;

   /** End of the tray components. */
   struct TrayComponentType *componentsTail;

   /** floating point values here: (actual opacity...) see opacity below */

   Window window; /**< The tray window. unsigned long */

   unsigned bgcolor[2];  /** NEW */
   unsigned bgcolorActive[2];  /** NEW */
   unsigned fgcolor;  /** NEW */
   unsigned fgcolorActive;  /** NEW */

   unsigned short requestedX;      /**< The user-requested x-coordinate of the tray. */
   unsigned short requestedY;      /**< The user-requested y-coordinate of the tray. */

   unsigned short x;   /**< The x-coordinate of the tray. */
   unsigned short y;   /**< The y-coordinate of the tray. */

   unsigned short requestedWidth;  /**< Total requested width of the tray. */
   unsigned short requestedHeight; /**< Total requested height of the tray. */

   unsigned short width;     /**< Actual width of the tray. */
   unsigned short height;    /**< Actual height of the tray. */

   /** opacity floating point value gets converted to 8 bit alpha anyhow */
   unsigned char opacity;       /**< Opacity of the tray when not "grabbed". */
   unsigned char opacityActive; /**< Opacity of the tray when "grabbed". */   

   WinLayerType layer;        /**< Layer. unsigned char */
   LayoutType layout;         /**< Layout. unsigned char */
   TrayAlignmentType valign;  /**< Vertical alignment. unsigned char */
   TrayAlignmentType halign;  /**< Horizontal alignment. unsigned char */

   TrayAutoHideType  autoHide;
   char hidden;     /**< 1 if hidden (due to autohide), 0 otherwise. unsigned char */

} TrayType;

```

Menus would be similar; though one change that I'd like to see from a user point of view would be to change `root:#` to `menu:#`

Some of these could be removed from settings.{c,h} and the rest could go in client.{c,h} for better locality of reference.

Part of the reason for moving some of the properties to the tray struct was so that a static global default tray could be used to memcpy for quick initialization.

**Comment by joewing** [comment]
I prefer the elements over properties for these (and it would greatly impact backward compatibility).  Since TrayStyle and Tray are separate elements in the configuration, I don't see an advantage.  Of course, there is no reason the code has to mirror the configuration.

Issue #39 mentions a method of supporting different styles for different trays that I like.  Supporting multiple TrayStyles that are able to inherit from each other seems like it would address many of these issues.

**Comment by joewing** [comment]
Closing in favor of #39, which is a similar request.
