### ISSUE TITLE
pass width and height to LoadImage()

### ISSUE THREAD

**Issue by technosaurus** [joewing/jwm#253]
libjpeg and rsvg have builtin scaling that could allow for better/more efficient scaled results
http://jpegclub.org/djpeg/
http://cairographics.org/manual/cairo-Transformations.html#cairo-scale
https://developer.gnome.org/rsvg/stable/RsvgHandle.html#rsvg-handle-set-size-callback

**Comment by joewing** [comment]
I agree.  The primary reason I didn't do this before was that JWM used to cache the raw image data and scale that as needed.  Now that JWM loads the image each time a new size is requested, this is a lot easier.

**Comment by joewing** [comment]
Available as of snapshot 1343.
