### ISSUE TITLE
Is it possible to resort the windows after switching between them?

### ISSUE THREAD

**Issue by mogeiwang** [joewing/jwm#254]
Suppose there are four windows, namely, 1, 2, 3 and 4, and the current window is 1.
Then I may press A-Tab to focus the next window 2.
Then I press A-Tab again, I hope to focus 1, before switching to  3 and 4.
Currently, it always loops in the order of 1, 2, 3, 4.

Also, it would be very helpful if a little menu, which indicates the logo and titles of windows, can be shown in the centre of screen while switching between these windows.

**Comment by Israel-** [comment]
http://www.joewing.net/projects/jwm/config.shtml#keys
You can use a different keybinding
```
next 	Key to move to the next window in the task list.
nextstacked 	Key to move to the next window in the stacking order.
prev 	Key to move to the previous window in the task list.
prevstacked 	Key to move to the previous window in the stacking order.
```
You want nextstacked instead of next

**Comment by mogeiwang** [comment]
Yes, that helps, thank you.
