### ISSUE TITLE
Is it possible to have less layers?

### ISSUE THREAD

**Issue by mogeiwang** [joewing/jwm#255]
Current, more than 10 layers are engaged, however 3 layers are very enough for most cases. 
I hope JWM can be configured to has less layers, or has only 3 layers by default.

**Comment by Israel-** [comment]
The only layers I can think of are for the Tray OR the windows
```
layer
The layer of the tray. The default is above. Valid values are below, normal, and above. 

layer:layer 	The layer on which windows in this group will be started. Valid options are below, normal, and above. 
```
Could you be more specific, as there are only 3 layers: below, normal and above

**Comment by mogeiwang** [comment]
Currently, I bind the window menu to `W-x`, i.e.,
```
<Key mask="4" key="x">window</Key>
```
Everytime I press `W-x`, the window menu will popup as expected. The structure of the menu looks like this,
```
    [Send To]
        1
        2
    [Layer]
        Bottom
        1
        2
        3
        Normal
        5
        6
        7
        8
        9
        10
        11
        Top
    Stick
    Maximize
    .
    .
    .
``` 
There seems to be 13 layers. 

I hope it has been fixed since you claim that there are only 3 layers. My JWM version is 2.1.0:
```
    ~> jwm -v
    JWM vsvn-579 by Joe Wingbermuehle
```

**Comment by Israel-** [comment]
Hi,
You should really run a newer version of JWM.  There are a LOT of improvements since 2.1.0
But indeed for me it looks like
```
[Layer]
  Below
  [Normal]
  Above
```

**Comment by mogeiwang** [comment]
Yes, great idea! Thank you again for helps.
