### ISSUE TITLE
 Windows minimized: problems key binding

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#257]
user jerefeltan reports this problem in Forum Manjaro Linux and i tested here. this really occurs!

when all windows are minimized and i touch a key binding, nothing happens. 

why?

vlw fwi, Holmes :)

**Comment by joewing** [comment]
It seems to work for me.  What version of JWM?  There was a bug a while back that caused this.  Also, what key binding?  The one I'm used to test is showing the root menu.

**Comment by jerefeltan** [comment]
In the versions 2.3.3 and 2.3.4 (in Manjaro Linux). When I use `<Key mask="4" key="d">exec:wmctrl -k on</Key>` to hide the windows, there is no problem, everything works. But if I hide the windows manually, there is no key binding that works.

**Comment by joewing** [comment]
What do you mean by hide windows manually? Are you closing the windows or minimizing or?

**Comment by technosaurus** [comment]
Check to see if it is the keybinding itself or wmctrl.  Temporarily replace exec:wmctrl... with exec:xterm (or some random app)  Perhaps wmctrl does something different if the windows are all iconified.  Then try your wmctrl command from the terminal to see if it works:
sleep 20 && wmctrl -k on (then minimize within 20 seconds)

**Comment by blconde** [comment]
I can confirm this on Manjaro JWM 16 dev 30116, JWM 2.3.4 . It occurs when you minimize to tray tracklist all the widows one by one.
But, when everything is minimized using 'showdesktop', as is assign here ' <Key mask="4" key="d">showdesktop</Key> ' (in ~/.jwm/keys , but I guess you know it), the key bindings work fine.

**Comment by joewing** [comment]
See #322. It appears that this happens with conky and/or compton.
