### ISSUE TITLE
Dock icons sometimes rendered too large to fit

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#260]
From #231.  Some dock icons are rendered too large to fit in the dock.  This can be seen when setting the tray height explicitly to certain values (setting height=“23”, the audacious icon is rendered too large for me).

**Comment by jerefeltan** [comment]
Other examples: hplip and qbittorrent with tray height="24".
![captura de pantalla de 2015-12-04 12-10-54](https://cloud.githubusercontent.com/assets/16145487/11593093/2381b930-9a81-11e5-990b-87aee28247cf.png)
![captura de pantalla de 2015-12-04 12-11-07](https://cloud.githubusercontent.com/assets/16145487/11593094/2381d258-9a81-11e5-980c-9041cc8700e3.png)
![captura de pantalla de 2015-12-04 12-19-54](https://cloud.githubusercontent.com/assets/16145487/11593137/5f021f0e-9a81-11e5-9d22-d053f4aac2fb.png)

**Comment by joewing** [comment]
This turns out to be kind of annoying to fix.
To place a window in the notification area, an application provides JWM a window.  JWM then reparents that window in the dock and sizes it according to the size of the dock.  This is happening correctly right now.  It appears that some applications only work correctly with certain window sizes.  So when JWM resizes the window, the application draws something that doesn't fit.  I'm not actually sure what the proper solution is.

According to [the spec](http://standards.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html#docking), "tray icons may be assigned any size by the system tray, and should do their best to cope with any size effectively."  Therefore, I'm inclined to think this is actually a bug with the applications being docked rather than JWM.  JWM does appear to be sizing the window correctly, but the application apparently has a fixed set of icons.  I would guess the application is selecting the icon that is closest in side rather than the largest one that fits (this appears to be the case with Audacious, which I have been using for testing).

As a work around, I would select a tray size that is likely to be supported, something like 18, 26, or 34 (note that the border will take 2 pixels).

**Comment by dumblob** [comment]
>As a work around, I would select a tray size that is likely to be supported, something like 18, 26, or 34 (note that the border will take 2 pixels).

I myself would leave JWM with the current "correct" behavior and write to the documentation a suggestion to contact the author of the application to fix it. The reason for this is, that many screens nowadays have wildly varying sizes with even more wildly varying resolutions and applications are therefore expected to accommodate.

**Comment by joewing** [comment]
Since I don't know a good way around this, I'm going to close this issue for now.
