### ISSUE TITLE
Key bindings with alt+shift don't work

### ISSUE THREAD

**Issue by J5lx** [joewing/jwm#261]
I put these key bindings into my .jwmrc:
```xml
<Key mask="AS" key="Right">rdesktop</Key>
<Key mask="AS" key="Left">ldesktop</Key>
<Key mask="AS" key="Up">udesktop</Key>
<Key mask="AS" key="Down">ddesktop</Key>
```
However, when I press Alt+Shift+\<arrow key\> nothing happens. Without shift in the modifier mask (i.e. `mask="A"`) the bindings work just fine (but of course they also trigger when shift is not pressed, which is not what I want since it is commonly used in browsers to navigate history).

In case it matters, I use the German Dvorak keyboard layout but I have also confirmed the bug with the German standard QWERTZ layout as well as US QWERTY.

**Comment by joewing** [comment]
Those key bindings work fine for me.  Is this with a recent version of JWM?  I suppose it could be a certain application is intercepting them.

**Comment by J5lx** [comment]
It's the current version (2.3.4). Also I don't think it's because of another application's interference since gkbd-keyboard-display has absolutely no problems detecting that both keys are pressed:
![screenshot from 2015-12-07 00-18-18](https://cloud.githubusercontent.com/assets/2063777/11616318/0b7e447c-9c78-11e5-93df-762beac26d91.png)

**Comment by J5lx** [comment]
On a second thought, when looking at that screenshot I just made, it seems that there's "Meta L" on level 2 of the alt key. Could that be a problem?

**Comment by joewing** [comment]
That might be a problem, I'm not really sure what that means.  `xmodmap` should be able to tell you what keys are mapped to which modifiers.  JWM treats "A" as "mod1".

**Comment by blconde** [comment]
@J5lx (maybe joe could help too), sorry if it is silly, but is there a version of this gkbd-keyboard-display utility for Arch linux?
Actually, my issue is the shortcut 'ctrl + w' that doesnt work in Palemoon, PCManFM, Medit and so on, but 'ctrl + q', 'ctrl + s' and so, works fine. I cant figure out what is going on...

**Comment by J5lx** [comment]
@joewing I just got reminded of the issue by blconde’s reply. According to `xmodmap`, both Alt_L and Meta_L are mod1. Running `xev`, which I discovered recently, reveals that my alt key is reported as Meta_L when the shift key is pressed and as Alt_L when it is not. Is it possible that JWM uses the same mechanism for recognizing key presses as `xev`? That would explain the cause of the issue.

@blconde Yes, that’s what I’m using :) It’s contained in libgnomekbd.

Not directly related to the issue, but if you ever need to find a package containing something again, you can just install pkgfile from extra, sync the repos using `sudo pkgfile -u` and do e.g. `pkgfile gkbd-keyboard-display`.

**Comment by blconde** [comment]
Tks @j5lx , I managed to run gkbd-keyboard-display, which is a very fine tool, but later I found the source of my issue: it was another program, Dunst notification, that was 'stealing' the 'ctrl + w' shortcut.
This can happen to anyone (and can be very annoying), but have you looked for applications conflicts (and not JWM), like it turned to be my situation?

(And for this Manjaro JWM I just found a pkgfile in AUR, not in the official repos, but tks anyway, I'll try later, seems an useful extra, besides pkg name and description, the standard pacman search.)
