### ISSUE TITLE
Clicking submenu closes the entire menu, so it's impossible to use menus on a phone/tablet

### ISSUE THREAD

**Issue by lope** [joewing/jwm#264]
When clicking on Applications, the whole root menu (all the menus) close. So it's not possible to see what's inside the Applications menu on a phone/tablet. Phones and tablets don't do mousemove over VNC, they click only.

It would be nice if clicking on a menu did not close everything?

```
   <RootMenu height="75" onroot="12">
      <!--Menu icon="folder.png" label="Applications">
            <Program icon="font.png" label="Fonts">xfontsel</Program>
      </Menu-->
etc
```

**Comment by technosaurus** [comment]
I wonder if the mouse masks could be applied to menus to remedy this as is done for trays.  It may be useful to have exec associated with menus such that a right click could bring up a config/help menu for that particular submenu ... like the kde menu and formerly gnome.

**Comment by joewing** [comment]
This should be fixed as of snapshot 1361.
