### ISSUE TITLE
nl_langinfo(CODESET) in USE_ICONV doesn't work with --disable-nls

### ISSUE THREAD

**Issue by tsutsui** [joewing/jwm#266]
In src/font.c, nl_langinfo(CODESET) is called inside #ifdef USE_ICONV.
However nl_langinfo(CODESET) assumes setlocale(3) is called and setlocale(3) is called only if
defined(ENABLE_NLS) in main.c.
Probably USE_ICONV should be enabled only if ENABLE_NLS is defined?

**Comment by joewing** [comment]
I could see someone wanting Unicode support, but not NLS.  I think the right thing to do is to call setlocale if either NLS or iconv support is enabled, which would allow that situation.

**Comment by joewing** [comment]
This should be fixed as of snapshot 1361.
