### ISSUE TITLE
Smart window placement

### ISSUE THREAD

**Issue by romildo** [joewing/jwm#269]
Smart window placement chooses the best place to position a window in the screen based on the available free screen areas. It chooses a position which minimizes window overriding. It is an option on several window managers, like `Openbox`, `xfwm`, `fluxbox`, `Enlightenment`, and others. It makes the desktop easy to work with because the user  has not to reposition windows as much as with other placement algorithms like centred and cascaded.

The algorithm should not be that difficult to be implemented. It would collect rectangles of free spaces on the screen and sort them by size (let's say by their area), choosing one where the window would best fit.

It would be very nice if `JWM` could have this placement option too.

**Comment by joewing** [comment]
JWM has a window placement policy to place windows with no overlap.  Of course it falls back to the default policy if no position is available.  It’s available as a `Group` option, so you can do something like:
```xml
<Group>
    <Option>tiled</Option>
</Group>
```

An improved placement policy to minimize overlap would be nice to have.

**Comment by romildo** [comment]
I had found the `tiled` option before, but it is not satisfactory yet because as soon as there is no position where the window could be positioned without covering any other windows, it falls back to the default cascaded placement.

The smart placement can be an enhancement to the `tiled` placement where the default placement is not used in that circumstance. Instead it would find a position where the window would benefit from any area of desktop that is still unused. It would still cover parts of other windows, but in a minimized way.

If there is absolutely no free desktop area available, it could use a random positioning ([like `Openbox`](http://icculus.org/pipermail/openbox/2008-February/005363.html)).

**Comment by joewing** [comment]
As of snapshot 1366, the tiled option will attempt to find the location with the least overlap if it can't find a location with no overlap.  If you have a chance to try it out, please let me know what you think!

**Comment by romildo** [comment]
I have tried and liked it. Thanks.

**Comment by roandbox** [comment]
It works.
