### ISSUE TITLE
Add support for the icon theme specification

### ISSUE THREAD

**Issue by romildo** [joewing/jwm#271]
From the [Icon Theme Specification](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html): _An icon theme is a set of icons that share a common look and feel. The user can then select the icon theme that they want to use, and all apps use icons from the theme._

Please add support for looking icons according to the specification.

**Comment by Israel-** [comment]
@romildo I have a script and a binary program that can do this.
I am sure others such as @technosaurus have similar programs.

[jwmIconFinder.txt](https://github.com/joewing/jwm/files/92068/jwmIconFinder.txt)
Feel free to modify it to suit your needs.
I had to upload as a .txt file, but it is indeed a bash script.

**Comment by joewing** [comment]
JWM doesn't currently enforce any type of standard as far as icon or menu support is concerned.  I think dealing with such things is best left to third-part programs that generate configuration for JWM.

**Comment by blconde** [comment]
Actually, I dont know if I'm gonna write a nonsense the follow (or 'break' some standards already set), but is there a way to set something like an 'icon path binding'? Like this: you could write to ~/.jwm/menu (ie):
`<Program icon="programname" label="Program name">exec:programname</Program>`
So JWM would load the icon as the selected icon pack (after a restart, I believe).
I mean that this kind of setup would leave open the possibility to also 'manual edit' the icons, as it is today, where you write the full path to the icon.

**Comment by Israel-** [comment]
@blconde download that text file in my earlier comment.
The script allows you to simply write out the icon includes to a separate file (default) or put them into the base .jwmrc file.
but currently, if I understand you correctly, you simply put the icon name.
i.e.
terminal
Not
/path/to/specific/theme/terminal.svg
you do not need to specify svg,png,xbm either... @joewing did some nice things for us and JWM now checks common extensions very quickly
So your example is a reality for anyone running a recent version of JWM.

**Comment by blconde** [comment]
Hmm interesting @Israel- , I'm gonna take a look, tks.

**Comment by technosaurus** [comment]
The icon theme specification, icon naming specification and most other xdg specifications for that matter are poorly defined, outdated and/or just plain broken.

Go ahead and try to figure out what is supposed to go in /usr/share/desktop-directories
Look at how many categories are named in the desktop file specification that have no corresponding entry in the icon naming specification.
The icon theme specification is basically useless.  Its overly verbose on the mundane and vague on the important parts to the extent that it recommends using ../icons/*/apps/*  while the icon naming spec  clearly uses "applications/*"

I have tried addressing multiple issues on the xdg mailing list but my posts don't seem to  get through and I doubt anyone is listening anyhow.

**Comment by joewing** [comment]
I'm marking this as closed.  I think there are other ways of accomplishing this via third-party applications that make more sense.  Feel free to reopen/discuss further if there is disagreement.
