### ISSUE TITLE
Is there a way to set a key binding to move the focused window to next (or previous) desktop?

### ISSUE THREAD

**Issue by blconde** [joewing/jwm#272]
This is a little function I found in Openbox, which the key binding is shit + alt + left/right (and also Metacity and Xfwm, if I remember correctly), and I think is very handy.

But looking here, http://joewing.net/projects/jwm/config.shtml#keys , I couldnt find this function in JWM to be called by a key binding.

(And I'm new here, and sorry, as I couldnt find a forum or something like that, I thought that this could be a way to ask this question; if I'm doing the wrong way, pls point the right direction.)

**Comment by roandbox** [comment]
The actions for a key binding:
sendl - Send the active window left.
sendr - Send the active window right.
sendu - Send the active window up.
sendd - Send the active window down.

**Comment by joewing** [comment]
I just updated the online documentation.  As @roandbox mentioned, this functionality exists, it just wasn't correctly documented.

There is no forum or anything (that I know of) for for JWM, so asking questions here is fine.

**Comment by blconde** [comment]
Tks you two, I'm trying to help in Manjaro JWM community edition with Holmes, the maintainer there, and we're trying to tweak JWM (which is a very nice WM, pretty light, and very complete) and get a bunch of small nice things done, like this function. Nice to know it's already implemented and that the online documentation is update.

**Comment by blconde** [comment]
Ow, I just tested it here, and the windows are sending fine to my right or left desktop, but the 'focused desktop' stays the same, right? I mean, it doesnt switch the desktop following the active window (that was moved to the left or right desktop).
I guess it's not that big deal, but the usability is a bit different than a few WM I have used, like Openbox and Metacity. Or maybe, just maybe, this could be implemented as two different actions to set key bindings... just a suggestion, I guess.
(Oh, and sorry again, English is not my primary language, hope I made myself a least a little bit clear, ehehe.)

**Comment by joewing** [comment]
I agree that it makes more sense to switch to the desktop where the window is sent.  Ideally, I think it should be possible to configure it either way, but that's a different issue.

Snapshot 1369 makes it switch desktops when sending a window to a different desktop via a key binding.

**Comment by blconde** [comment]
Nice! It is still version 1356 in AUR ( https://aur.archlinux.org/packages/jwm-git/ ), but I believe it will be update anytime soon, then I'll try (because I'm not good at all in compiling, eheh).
And will be a different command or still 'sendl', 'sendr'?

Also: if it is possible to have both, send a window changing the desktop right away, and not changing the desktop, would open a nice range of configurations possibilities, so JWM would be (even more) complete.

Though, it's already pretty nice, I'm 'migrating' from Openbox, learning a bit more everyday about JWM and liking it a lot.

**Comment by Israel-** [comment]
@blconde it works with the current sendl,sendr,sendu,sendd
@joewing Thanks for this!  it really improves my workflow.   I am glad the focus stays on that window, when moving, because I can move it to any of my desktops easily.  This is a great improvement!!!

**Comment by blconde** [comment]
@Israel- I mean the action 'send to the leff/right/up/down desktop AND change to this desktop as well'. Today, if you press a keybinding assigned with sendl, ie., the window is sent, but the desktop remains the same (actually, it seems that the window vanishes, ehehe).

**Comment by Israel-** [comment]
@blconde 
I am running jwm (1369-0ubuntu1)
1369 is the snapshot from github.  This action 
>  'send to the leff/right/up/down desktop AND change to this desktop as well'.
works flawlessly for me.
It moves the window to the desktop I choose, and the screen follows it.

**Comment by blconde** [comment]
Oh, I see, now I understood what you're talking, tks for the patience, ehehe.
And I'm eager to try this snapshot, and even more the next one, 1370, with this little fix: https://github.com/joewing/jwm/issues/275 .

**Comment by Israel-** [comment]
Another bit of helpful code for your .jwmrc might be adding this gem
```
    <Group>
        <Option>noshade</Option>
    </Group>
```
This prevents windows from shading altogether.  We do this, as it is very easy on newer touchpads to accidentally scroll the window up.  It is a bit of a hack workaround, but it is really nice if you have a synaptics touchpad like mine.
