### ISSUE TITLE
Is possible to make only the clock font in tray to be bold (or even to change the font)?

### ISSUE THREAD

**Issue by blconde** [joewing/jwm#276]
I know the 'thickness' of a font can be set in ~/.jwm/theme , ie:

    <TrayStyle decorations="flat">
        <Font>Roboto-10:**bold**</Font>
[...]

But if set as it this, all tray fonts, including the Root Menu (if assigned), the TaskList, etc. would become bold.

It would be nice to set only a parameter to a single component of the tray (or whatever you are configuring in JWM), maybe something to set in ~/.jwm/tray like this (the following is 'syntax mock up'):

>  
> [...]
>   < Clock font="Roboto-10:bold" format="%H : %M"></Clock >

Just an idea.

**Comment by holmeslinux** [comment]
hello @blonde, interesting this request! not whether it is possible to implement, only Joe can tell us.

it would be nice to have this feature....;)

vlw fwi, Holmes :)

**Comment by joewing** [comment]
In older versions of JWM, it was possible to specify the font of the clock using the `ClockStyle` tag.  While simplifying the JWM configuration, I removed that ability to make the configuration and code simpler.  I suppose I could be persuaded to add the ability back, but I don't personally find it useful.

Another way to accomplish the goal is to use `Swallow` with xclock (or equivalent).

**Comment by technosaurus** [comment]
+1 for restoring some of the removed styles ... I like an LCD style font for my clock, but not for menus, etc...
I also kinda liked having tray-button styles that were different from the tray (it makes the buttons more obvious ... especially with a flat tray and gradient buttons)
For small devices it would be nice to be able to configure the pagerstyle to have different backgrounds per desktop to use as sort of notebook tabs for different app types.

**Comment by blconde** [comment]
Hmmm, interesting.
Sure I can understand that having a simpler syntax for config files is a good thing, but at a cost of loosing some features... well, this is a thing that could be asked for the community, no?
I mean, this other user @technosaurus (ahaha, pretty nice username) is up to have this feature back. Maybe this question I asked here could became a poll (or just a stick question) here in this JWM github page (for a couple of days or a week or so).
Also I could open a poll (or just a thread) in Manjaro JWM subforum, there's a few folks there that could give their opinions.

I guess this is the best way I can think how to go in this situation.

**Comment by roandbox** [comment]
+1 for restoring some of the removed styles

**Comment by holmeslinux** [comment]
> Another way to accomplish the goal is to use Swallow with xclock (or equivalent).

how would this alternative? give an example?

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
Here is an example using xload (I have this in my config)
Make sure the name="" part MATCHES the program name exactly.
<Swallow name="xload" width="64">xload -nolabel -bg DimGrey -fg Grey -hl DarkGrey</Swallow>
for xclock I'd suggest reading
`man xclock`
for a complete configuration....
but the option -face is what you will need to use to make a different font

**Comment by holmeslinux** [comment]
thank you @Ismael and i will prove here... ;)

vlw fwi, Holmes :)

**Comment by joewing** [comment]
`ClockStyle` is back in snapshot 1381.  I may restore `TrayButtonStyle` and `TaskBarStyle` since most of the machinery is already there and it's apparently useful to some people.

I opened a new issue to allow different pager background colors (issue #284).

**Comment by wosss** [comment]
Hi Joe, i'm a big fan of your window manager since the xdsl days in xbox classic, I updated to 2.3.5 to gain some handy features but one that I miss is: TaskListStyle tag, specially for different font change from other tray areas, please can you restore this one?

**Comment by joewing** [comment]
I plan to reinstate the `TaskListStyle` and `TrayButtonStyle` tags for v2.3.6.  Thanks!

**Comment by joewing** [comment]
The `TaskListStyle` and `TrayButtonStyle` tags have been restored as of snapshot 1485.  Please let me know/reopen if you run into any problems.
