### ISSUE TITLE
Mulit-line popups

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#278]
It would be nice to have multi-line popups.  For example:

```xml
<TrayButton ... popup="line one&#30;line two">
...
</TrayButton>
```

**Comment by blconde** [comment]
Hmmm, sorry if I'll be annoying next (eheh), sure it could be nice, but, Joe, could you pls give a couple of examples where this could be applied?
And is it present in some other WMs?

**Comment by roandbox** [comment]
> Hmmm, sorry if I'll be annoying next (eheh), sure it could be nice, but, Joe, could you pls give a couple of examples where this could be applied?

```
<TrayButton ... popup="Midnight Commander&#30;Visual file manager">
...
</TrayButton>
```
 I like more a separator of rows "\n"

**Comment by roandbox** [comment]
I would like to have a smart popup, that retains the aspect ratio, for example, 1/10

**Comment by blconde** [comment]
I see. This could be nice.

**Comment by joewing** [comment]
Available in snapshot 1395.  Thanks @roandbox!
