### ISSUE TITLE
Menu navigation and windows switching with keyboard stops working

### ISSUE THREAD

**Issue by romildo** [joewing/jwm#279]
Menu navigation with the keyboard stops working after some time. The movement keys just do nothing.

Also windows switching with the Alt+Tab key stops working correctly after some time. It just switches between the two most recent windows, completely ignoring all other windows.

These two behaviours seems to be connected, as they start at the same time.

I cannot tell exactly what is triggering this malfunctioning though.

**Comment by joewing** [comment]
I haven't noticed this behavior (I apologize for not responding sooner).  Is this still an issue?  Any ideas on how to reproduce it?

**Comment by romildo** [comment]
Yes, it is still happening. I will try to identify which actions may be triggering this misbehavior.

**Comment by joewing** [comment]
Something I noticed is that if I hold down a mouse button while doing "alt-tab", JWM will toggle between the top two windows.  It's not something I really considered worth fixing, but it might be the source of the issue here.  So I wonder if somehow a mouse button is being reported or something.

**Comment by joewing** [comment]
Perhaps related to #322?
