### ISSUE TITLE
does jwm support event hooks in jwmrc ?

### ISSUE THREAD

**Issue by thechile** [joewing/jwm#280]
Hi

If i have a window open in JWM, lets say gedit or firefox, and the user closes the window. Is there a way in the jwmrc i can specify some action to be performed when this happens such as to logout the user ?

A group action or something like `ACTION_CLOSE, exec:jwm -exit`

Or even allow an arbitrary script to be run so zenity or xdialog can be used to prompt the user for confirmation before continuing.

I would like to create a minimal JWM session with no menu, tray or keybindings. The application will be launched full screen and have `nomin` specified. In the event the user closes the app i want JWM to respond to that event and probably exit the session other wise they will just be locked in a bare JWM .

I think with JWM i can already force a window to be full screen, disable minimize, have no tray, no menu and if i don't specify any keyboard shortcuts then they will also be disabled. Its just the responding to application events like CLOSE that i'm missing. 

Many thanks for JWM .

fLo

**Comment by technosaurus** [comment]
exec:first-command && good-exit-command || bad-exit-command

**Comment by thechile** [comment]
ok thanks, tried that and works. I was thinking more a JWM integrated event but using the commands exit status to do something will work.

Problem i now have is `jwm -exit` prompts to exit yes/no which i can't see a `force` option :( 

Any workaround to this ? 

Thanks again

**Comment by thechile** [comment]
OK.. just noticed this was fixed a few days ago ( https://github.com/joewing/jwm/commit/fb93ce3e3c1a8d244b74503d21250d88e542f8dc )

Will close this issue since JWM already does everything i want it seems :)
