### ISSUE TITLE
Would it be possible to make current "raise-on-click" behavior optional?

### ISSUE THREAD

**Issue by just22** [joewing/jwm#286]
When clicking within application window's area, the client is raised; I typically find this unconfortable, particularly during text cut-and-paste between terminals; my workflow is instead based on a "raise-when-clicking-on-window-titlebar".
This could be implemented by means of an additional dedicated tag, e.g. "<RaiseOnClick>{area,titlebar}</RaiseOnClick>", with "area" as default value.

**Comment by joewing** [comment]
This is a common focus model that I think would be good for JWM to support.

**Comment by technosaurus** [comment]
Correct me if I am wrong, but IIRC the existing modes are sloppy and click?  I don't think it needs a whole  new tag, just a 3rd option ... possibly title or titleclick.  Another one that might be nice is if right-clicking on an unfocused window would bring up the same options that normally come up on the title bar except with the raise option on top.

**Comment by joewing** [comment]
There are two new options for `FocusModel` as of snapshot 1580: `clicktitle` and `sloppytitle`.  These both require that you click the title or border of the window to raise the window.
