### ISSUE TITLE
Recursively search for icons

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#290]
JWM currently supports specifying the icon path by one or more `IconPath` tags, which are searched in order for icons.  This request is to add the ability to recursively search for icons under a directory.  One complication with doing this is that the icon path search order will not be deterministic for recursively searched directories.

**Comment by joewing** [comment]
Note that this can be accomplished now by running something like:

```bash
echo "<JWM>"
for p in $(find /usr/share/icons -type d); do
   echo "<IconPath>$p</IconPath>"
done
echo "</JWM>"
```

and including the output in ~/.jwmrc.

**Comment by joewing** [comment]
I think issue #291 provides a more generic way of providing this ability, so this may no longer be needed.

**Comment by Israel-** [comment]
I think recursive includes are a bad idea.  This could provide inappropriate icons based on the screen size.  The way I do it is to read the theme's index file and, based on the icon size include the appropriate icons (but ignore certain specific types that cause problems) and also do the same for the inherited icons.
Ultimately using the icon theme specification is better than recursion, as recursion will cause wrong icons to display on occasion.
For example I ignore Animations, Stock, Status, Emblems, Emotes, International from the .theme file
There is also the issue of threshold sizes, and whether you are using scalable icons, etc..

So, supporting the icon theme specification:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
is better, but probably not desired by all parties, such as Puppy which likes a minimal setup (for good reason)

**Comment by despicere** [comment]
https://github.com/andreyrogojin/menu for jwm.
<Dynamic label="Programs" icon="/usr/share/xpupsay/cow_small.png">exec:jwmtst</Dynamic>
it is necessary jwm understand path recursively /usr/share/icons/*,  instead many paths to manually entry.
Need support "without icons", with full path to icons (has already) and recursively option in jwmrc. 
For PRA linux (Puppy in based Arch) for good reason.

The path can be specified <IconPath>/usr/share/icons/hicolor/22x22/*</IconPath> but need continue to recursively...

**Comment by joewing** [comment]
It's now possible to do something like this.
$HOME/.jwmrc:
```xml
<JWM>
   <!-- ... -->
   <Include>exec:$HOME/.icon_paths</Include>
   <!-- ... -->
</JWM>
```

$HOME/.icon_paths:
```bash
#!/bin/sh
echo "<JWM>"
for p in `find /usr/share/icons -type d`; do
   echo "<IconPath>$p</IconPath>"
done
echo "</JWM>"
```

This is actually more versatile than building something into JWM since you can now control the order and depth of the directories, as well as do lots of other things.  So I think it's best to not add additional support for this particular use case.

**Comment by Israel-** [comment]
One quick question about this @joewing does running `jwm -reload` reload these?  In the case of `<IconPath>` it would not redraw the icons, so -restart is required for that.

**Comment by joewing** [comment]
Running `jwm -reload` will reload the include files (to look for menus), but it will not update the icon paths.

**Comment by Israel-** [comment]
Ok, thanks @joewing!!!!

**Comment by pvlb** [comment]
Not work.., without the icon menu.

$HOME/.jwmrc:

```
<JWM>
   <Dynamic label="Programs">exec:jwmtst</Dynamic>
   <Include>exec:$HOME/.icon_paths</Include>
</JWM>
```

$HOME/.jwm/icon_paths or $HOME/.icon_paths:

```
#!/bin/sh
echo "<JWM>"
for p in `find /usr/share/icons -type d`; do
   echo "<IconPath>$p</IconPath>"
done
echo "</JWM>"
```

**Comment by joewing** [comment]
What doesn't work?  Everything seems to work for me.  Does your `.icon_paths` script have the execute bit set (`chmod +x .icon_paths`)?

**Comment by pvlb** [comment]
yes, permissions 755
