### ISSUE TITLE
<Corner>0</Corner> is not square

### ISSUE THREAD

**Issue by pevsner** [joewing/jwm#292]
Hi Joe,
For me built from git today <Corner>0</Corner> in Windowstyle does not result in square corners.
Interestingly <Radius>0</Radius> does still, although I see it's deprecated.
Thx Adrian.

**Comment by pevsner** [comment]
opps code gets lost 
Corner 0 Corner ........Radius 0 Radius still works.

**Comment by joewing** [comment]
`Radius` no longer works (it was replaced by `Corner`).  It sounds like you have an old version of JWM running.  Are you sure that you restarted JWM and the right version of JWM was picked up?

**Comment by joewing** [comment]
Also, just to be sure, `jwm -restart` or selecting a restart menu item is not sufficient, since that will only restart the currently loaded version of JWM.  You need to exit JWM and start it over.  I sometimes set up an `Exit` menu item that does this for me (though usually I just run JWM from xterm).

**Comment by pevsner** [comment]
@joewing thanks for your response.
I built it today off a fresh git pull.. but jwm -v reads
JWM v2.3.4 by Joe Wingbermuehle
compiled options: confirm icons jpeg nls png shape svg xbm xft xinerama xpm xrender 
system configuration: /usr/local/etc/system.jwmrc
/usr/local/bin jwm --last modifiied 09/03/16 22:36 ..interesting, i didn't remove it before installing however.

**Comment by joewing** [comment]
If `jwm -v` reports 2.3.4, then you're running an old version.  A fresh pull from git will report 2.3.5.  Are you sure you re-built/installed?

**Comment by pevsner** [comment]
haha i found it, was an old verion in /usr/bin. just changed sorted it. corner works fine. Sorry .. my cock up

**Comment by pevsner** [comment]
had 2 versions  the git one was in urs/local/bin

**Comment by joewing** [comment]
No problem, that type of thing seems to happen a lot.  I've considered adding the ability to have JWM report the running version somehow, maybe a property on the root window or something.

**Comment by pevsner** [comment]
That would be cool.
I actually think I just stopped  bothing to ./configure --prefix= /usr and went with the default, hence the old version lucking about.
Thanks Joe, sorry to bother you with my stupidity..haha
