### ISSUE TITLE
Invalid entity problem for JWM?

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#294]
hi guys, i would like to know the **invalid entity** are problems for jwm:

`JWM: warning: /home/manjaro/.jwm/menu[21]: invalid entity: "& sleep "
JWM: warning: /home/manjaro/.jwm/menu[21]: invalid entity: "&& notif"
JWM: warning: /home/manjaro/.jwm/menu[21]: invalid entity: "& notify"
JWM: warning: /home/manjaro/.jwm/menu[22]: invalid entity: "&& sleep"
JWM: warning: /home/manjaro/.jwm/menu[22]: invalid entity: "& sleep "
JWM: warning: /home/manjaro/.jwm/menu[22]: invalid entity: "&& notif"
JWM: warning: /home/manjaro/.jwm/menu[22]: invalid entity: "& notify"
JWM: warning: /home/manjaro/.jwm/menu[23]: invalid entity: "&& sleep"
JWM: warning: /home/manjaro/.jwm/menu[23]: invalid entity: "& sleep "
JWM: warning: /home/manjaro/.jwm/menu[23]: invalid entity: "&& notif"
JWM: warning: /home/manjaro/.jwm/menu[23]: invalid entity: "& notify"
JWM: warning: /home/manjaro/.jwm/menu[24]: invalid entity: "& scrot "
JWM: warning: /home/manjaro/.jwm/menu[24]: invalid entity: "&& sleep"
JWM: warning: /home/manjaro/.jwm/menu[24]: invalid entity: "& sleep "
JWM: warning: /home/manjaro/.jwm/menu[24]: invalid entity: "&& notif"
JWM: warning: /home/manjaro/.jwm/menu[24]: invalid entity: "& notify"
JWM: warning: /home/manjaro/.jwm/start[5]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[6]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[7]: invalid entity: "&& volum"
JWM: warning: /home/manjaro/.jwm/start[7]: invalid entity: "& volume"
JWM: warning: /home/manjaro/.jwm/start[7]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[8]: invalid entity: "&& clipi"
JWM: warning: /home/manjaro/.jwm/start[8]: invalid entity: "& clipit"
JWM: warning: /home/manjaro/.jwm/start[8]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[9]: invalid entity: "&& conky"
JWM: warning: /home/manjaro/.jwm/start[9]: invalid entity: "& conky "
JWM: warning: /home/manjaro/.jwm/start[9]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[10]: invalid entity: "&& notif"
JWM: warning: /home/manjaro/.jwm/start[10]: invalid entity: "& notify"
JWM: warning: /home/manjaro/.jwm/start[10]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[11]: invalid entity: "&& xauto"
JWM: warning: /home/manjaro/.jwm/start[11]: invalid entity: "& xautol"
JWM: warning: /home/manjaro/.jwm/start[11]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[12]: invalid entity: "&& /usr/"
JWM: warning: /home/manjaro/.jwm/start[12]: invalid entity: "& /usr/l"
JWM: warning: /home/manjaro/.jwm/start[12]: invalid entity: "&</Start"
JWM: warning: /home/manjaro/.jwm/start[13]: invalid entity: "&& xrdb "
JWM: warning: /home/manjaro/.jwm/start[13]: invalid entity: "& xrdb m"
JWM: warning: /home/manjaro/.jwm/start[13]: invalid entity: "&</Start"`

vlw fwi, Holmes

**Comment by Israel-** [comment]
Hey @holmeslinux It is an XML file and a literal & is invalid
you need
`sed -i "s#&#&amp;#g" /home/manjaro/.jwm/start`

**Comment by holmeslinux** [comment]
hi @Israel- thank you!

but this can damage the use of jwm?

**Comment by holmeslinux** [comment]
`JWM: warning: /home/manjaro/.jwm/keys[33]: invalid Key action: "smplayer"
JWM: warning: invalid key symbol: "PgDn"
JWM: warning: invalid key symbol: "PgUp"`

**Comment by Israel-** [comment]
@holmeslinux we may need to see the file.... but
smplayer should *likely* be
`exec:smplayer`
You should use`xev` to find keys
```
KeyPress event, serial 37, synthetic NO, window 0x3000001,
    root 0xf5, subw 0x0, time 1992921, (761,829), root:(818,881),
    state 0x0, keycode 112 (keysym 0xff55, Prior), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
from this I think you might be wanting
`Prior`
for "PgUp"
and might need
`Next`
for "PgDown"
If you are wanting that as well...
Hope this helps :)

**Comment by holmeslinux** [comment]
kkkkkkk @Israel- 
really missed exec: to smplayer. very good...
i did not understand that:

**from this I think you might be wanting
Prior
for "PgUp"
and might need
Next
for "PgDown"**

thank you @Israel-

**Comment by holmeslinux** [comment]
thank @Israel- i and managed to fix everything!

vlw fwi, Holmes :)

**Comment by joewing** [comment]
It sounds like this is resolved, so I'm closing this.  Please let me know otherwise.
