### ISSUE TITLE
Text alignment in title of window

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#299]
hi all,
with the new version of jwm can center the text window.
i follow it https://github.com/joewing/jwm/pull/277, but it did not work. does anyone have any advice?

vlw fwi, Holmes :)

**Comment by joewing** [comment]
It works for me.  Are you sure you're running the right version of JWM and that it's pulling in the right configuration?

**Comment by holmeslinux** [comment]
hi Joe,
my version is 2.3.5.
i did it:
`...
<WindowStyle>
        <Font align="center">Sans-9:bold</Font>
        ...
<WindowStyle>
...`

and it did not work!

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
sorry guys...
i was doing wrong!
it worked...

sorry...........................

vlw fwi, Holmes :)

**Comment by joewing** [comment]
No problem!  Assuming it's working, I'll mark this as closed.
