### ISSUE TITLE
Keyboard layout indicator?

### ISSUE THREAD

**Issue by foi** [joewing/jwm#303]
Hello! Any suggestitions where to dig?

P.S.  JWM is awesome.

**Comment by joewing** [comment]
I assume you're looking for something to show and possibly switch keyboard layouts.  Something like a dock app (or an application that can be swallowed into the tray).

JWM doesn't have anything built-in, as you may have guessed.  I don't use such a thing, so I'm not familiar with what's out that that may work (anyone else know of one?).  I would think there must be something out there.  If not, it's not something that would really need to be built into JWM, but it would be fairly easy to write such a thing that could be "swallowed" into a tray.

**Comment by Israel-** [comment]
@foi fcitx OR ibus are useful for that if I understand you correctly
You can add them to startup or make a script that goes through the autostart directory and starts things that way.

**Comment by dumblob** [comment]
@foi, use the suggestions from @Israel- or if you don't want to install another input method layer, use just `setxkbmap -query` to find out which keyboard layout is currently in use.

Regarding your initial question, [xxkb](https://wiki.manjaro.org/index.php?title=Openbox:_Switch_languages_using_the_keyboard_and_xxkb#Install_.26_configure_graphical_language_switcher_.28xxkb.29) is quite widespread.
