### ISSUE TITLE
Default icon

### ISSUE THREAD

**Issue by nimday** [joewing/jwm#310]
The default icon for a window is square not x anymore,is possible to add custom icon as alternative ?
Many of my apps(fltk) don't have icon and i want to use my own if possible.
Thanks.

**Comment by Israel-** [comment]
@nimday Are they apps you have written?  if so you can add icons to fltk apps (not entirely as easily as one would hope), but it is doable.
```c++
#include <X11/xpm.h>
#include <FL/x.H>
char* YourCLASS::Get_Fl_Icon(const char** pIcon){
    static Pixmap p= 0;
    // static store of assigned icon
    static Pixmap mask;
    if (!p && pIcon){
        // assign icon once
        fl_open_display();
        XpmCreatePixmapFromData(fl_display, DefaultRootWindow(fl_display),
(char**) pIcon, &p, &mask, 0);
    }
    return (char*) p;
}
```
Just make sure your icon is xpm and structured like
```c
static const char* icon_name[] = {
/*whatever*/
}
```
You can probably figure out the rest yeah?

**Comment by nimday** [comment]
Thanks for the code i'll try that,the apps mostly made by the notorious tiny core team and the editor from fltk test folder :)
I can change x.xpm with my own but not anymore.

**Comment by technosaurus** [comment]
IIRC you can just put an icon (or symlink to one) with the same name as your executable in your icon path.

**Comment by Israel-** [comment]
@technosaurus that worked in JWM for a short while, however something was changed to make everything better.  FLTK recently added something easier, IIRC but it might not be available in @nimday distro's repos.
So unfortunately the apps have to tell the window manager what icon to use, though for menus you are correct @technosaurus 
@nimday can you point me a link to those apps?  I like tiny FLTK apps a lot, it is my toolkit preference for many things.

**Comment by nimday** [comment]
@technosaurus , i think @Israel is right,that only for the menu and taskbar not for the titlebar
Below screenshots from my old jwm from tcl repo,2.3.5 and 2.35 from @technosaurus

http://s5.postimg.org/kkjblbgmf/screenshot_0419020319.png
http://s5.postimg.org/q9zk5mmsn/screenshot_0419021829.png
http://s5.postimg.org/iiiu72inb/screenshot_0419023408.png

No icon from the taskbar from 2.3.5 except from @technosaurus , i even tried 2.3.6
If this for good reason no problem but if possible to add this manually for my own personal use please let me know :)

@Israel this is the link for Tcl source
http://git.tinycorelinux.net/index.cgi?url=fltk_projects/

**Comment by Israel-** [comment]
@nimday I tried a few of them.  Most are extremely tinycore oriented, and wont 'just work'
The run dialog is nice, but does not work for commands.
It is a simple modification to do that.
You can manually add the function I sent you, but you do not need to make a class... install fluid and open the fl file.  Add a function, include the xpm you make (up top in the #include portion)
and call the function when the main window is drawn, with the icon_name from inside the xpm icon.
That is how I do it for my apps anyways.

**Comment by nimday** [comment]
@Israel,can you create 1 or 2 dummy app with fltk without icon and test it with jwm 2.3.5 or the latest.
I can see the square default icon from the panel from 2.3.3 but not the latest.
If the same result like me maybe @joewing can check.

For change the default icon with custom forget it,i can create app with icon as suggested by @Israel
Or small modification to icon.c

```
/* Check if this icon has already been loaded */
   result = FindIcon(name);
   if(result) {
      return result;
   }
   //mod
   image = LoadImageFromData(x_xpm);
   if(image) {
      result = CreateIcon(image);
      if(result){
        result->name = CopyString(name);
        result->images = image;
        InsertIcon(result);
        return result;
      }
   }
   /* Allocate image data. *
```

**Comment by Israel-** [comment]
@nimday I just thought of another slightly more complicated/simple idea
Your programs could be wrapped in a script that uses wmctrl to set the icon.

`
APP &
 wmctrl -r "APP Window Title" -I "Icon" 
`
you can do complicated things to get the window, something like

```
#!/bin/bash
APP="$1"
ICON="$2"
[[ -n "$1 ]] && exit 1
[[ -n "$2 ]] && exit 1
$APP &
pid=$(pgrep -n $APP)
wid=
while [ "$wid" == "" ]
do
  wid=$(wmctrl -lp | grep "$pid" | cut -d' ' -f1)
done
 wmctrl -r "$wid" -I "$Icon" 
```
then run the script with app name and icon for your exec

**Comment by israel** [comment]
You've got the wrong user -:)

**Comment by nimday** [comment]
@Israel ,thanks again l'll try that
this is your working code 
``c++
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/x.H>
#include <X11/xpm.h>
#include "x.xpm"
char* Get_Fl_Icon(char** pIcon){
    static Pixmap p= 0;
    // static store of assigned icon
    static Pixmap mask;
    if (!p && pIcon){
        // assign icon once
        fl_open_display();
        XpmCreatePixmapFromData(fl_display, DefaultRootWindow(fl_display),
       (char**) pIcon, &p, &mask, 0);
    }
    return (char*) p;
}
int main(){
   Fl_Window win(200, 200,"Icon");
   win.icon(Get_Fl_Icon(x_xpm));
   win.show();
   return Fl::run();
}

I tried with 2.3.4 and the default icon is displayed from the panel so the problem is started from 2.3.5 and so on
Btw i pressed fork button by accident,how to remove that ?

**Comment by joewing** [comment]
Sorry for not getting to this sooner.  I think setting a default is probably useful (and easy to implement), so I added the ability to set a default icon (available in snapshot 1507).  To set the default, use something like:
```xml
<DefaultIcon>myicon</DefaultIcon>
```
I also fixed the issue where the icon wasn't showing up in the task list for windows without icons.

Please let me know if that works for you.

**Comment by nimday** [comment]
Thanks a lot it's working :)

**Comment by Israel-** [comment]
@joewing Yeah I notice things working much better here too!  Great improvement!!
