### ISSUE TITLE
how to disable alt + mouse click actions in JWM

### ISSUE THREAD

**Issue by abrasmelin** [joewing/jwm#311]
Is it possible to disable alt + left and right mouse click actions? Right now the defaults are;

alt + left mouse : window dragging

alt + right mouse : window scale

I cant find a way to disable this behaviour.

This is very annoying. I am a 3D Artist and i cant use my main 3d software (Autodesk Maya) because of this. Because the program is using alt + mouse click navigation. (and there are lots of other programs that uses the same behaviour) Please Joe help me. I really like your work and dont want to skip JWM because of this. Thanks in advance.

**Comment by joewing** [comment]
Unfortunately that's not configurable right now.  A long standing issue is to make mouse bindings configurable.  Some behaviors, such as this, are more important than others though (who really wants left click on the title bar to do something other than move?).  So I think I'll probably try to work in a near-term solution that will attempt to work like a more generic solution.

In the mean time, if you want to disable this, it can be done with a fairly minor code change.  In `event.c` in the `DispatchBorderButtonEvent` function (around line 1537), comment out the special case around the `MoveClient` call.  Something like this:
```c
   /* Middle click starts a move unless it's over the maximize button. */
   action = GetBorderActionType(np, event->x, event->y);
/*
   if(event->button == Button2 && action != BA_MAXIMIZE) {
      MoveClient(np, event->x, event->y);
      return;
   }
*/
```

**Comment by joewing** [comment]
In trying to come up with a fix for this, I realized that the code that you want to remove is actually in `event.c` in the `HandleButtonEvent` function (around line 399):
```c
         switch(event->button) {
         case Button1:
         case Button2:
            FocusClient(np);
            RaiseClient(np);
            if(move_resize) {
/*
               GetBorderSize(&np->state, &north, &south, &east, &west);
               MoveClient(np, event->x + west, event->y + north);
*/
            }
            break;
```

**Comment by joewing** [comment]
I was going to do something more extreme, but I ended up just adding a "nodrag" group option.  So, as of snapshot 1517, you can disable this binding with:
```xml
<Group>
    <Option>nodrag</Option>
</Group>
```

This is a little bit of a hack since complete control over key bindings is the ultimate goal, but it's a quick fix that avoids breaking existing configurations.

Please let me know if that does what you need.

**Comment by abrasmelin** [comment]
Where should i add this?

**Comment by holmeslinux** [comment]
thank you Joe, i tried to help the @abrasmelin , but i could not!

vlw fwi, Holmes :)

**Comment by abrasmelin** [comment]
Ah so in order to this work i need to update jwm? Can you also add noscaling to groups? Because alt left mouse drags the window okay but also alt right click scales the window. Also holmes will you add this updated version?

**Comment by joewing** [comment]
You do need to update JWM (and be sure to exit the old version; restart won't pull in the new code).  The `nodrag` option should disable both left and right click over the window content.

**Comment by Ygarr** [comment]
Please help to disable Alt+Mouse1 dragging windows - i tried - nothing helps:

  <Key mask="A" key="mod1">nomove</Key>
  <Key mask="A" key="button 1">nomove</Key>
  <Key mask="A" key="mod1">nodrag</Key>
  <Key mask="A" key="button 1">nodrag</Key>
  <Key mask="A" key="1">nodrag</Key>
  <Key mask="A" key="1">nodrag</Key>
   <Key mask="A" key="button1">nomove</Key>
  <Key mask="A" key="Button1">nodrag</Key>
  
<Mouse context="window" button="1">nodrag/Mouse>
<MoveMode mask="CS"></MoveMode>
<Group>
    <Option>nodrag</Option>
</Group>
