### ISSUE TITLE
Calendar and JWM

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#312]
hi all,
installed gsimplecal and added on the clock:

`<Clock format = "% H:% M">exec:gsimplecal</Clock>`

by clicking on the clock the calendar appears, but does not disappear.
i wondered if what i did is correct!

vlw fwi, Holmes :)

**Comment by joewing** [comment]
What behavior are you expecting?  JWM runs the program after "exec:".  Once the program is started, it doesn't do anything else to manage the program (clicking the clock again would start multiple instances unless the program prevents that somehow).

**Comment by ml-** [comment]
You could use a wrapper to toggle gsimplecal, means start it if there is not already an instance or close it if there is.

would be something like
`<Clock format = "% H:% M">exec:pgrep gsimplecal > /dev/null && killall gsimplecal || gsimplecal</Clock>`

Short explanation:
If `pgrep gsimplecal` returns a PID, an instance exists 
and (&&) it is closed with the command `killall gsimplecal` 
or (||) if there is no instance running, it is started with `gsimplecal`. 

Please correct me if I'm missing something. I'm currently not at home and don't have a JWM setup here.

killall sends the signal SIGTERM to gsimplecal, this signal is handled by the code of the program:
https://github.com/dmedvinsky/gsimplecal/blob/master/src/gsimplecal.cpp#L17

means the existing intance will close properly, without any side-effects

**Comment by holmeslinux** [comment]
hi @ml- ,
i will test...

thanks @Israel- 

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@holmeslinux I e-mailed you rather than posting here, since it wasn't completely relevant to JWM, rather it is a script I wrote for a yad/zenity/dialog based calendar.
But you are welcome :)
