### ISSUE TITLE
Wine system tray icons are not shown

### ISSUE THREAD

**Issue by foobar0815** [joewing/jwm#314]
I guess that this might be the same bug the fluxbox window manager was affected by. Apparently the coordinates sent in the ConfigureNotify have to be in the root coordinate system.

The fluxbox bug report:
https://sourceforge.net/p/fluxbox/bugs/1034/

The comment in the wine bug report hinting at ICCCM:
https://bugs.winehq.org/show_bug.cgi?id=30944#c7

The commit in the fluxbox repository:
https://github.com/fluxbox/fluxbox/commit/6346368b58e054174075f615a836ff3bd9c9f823

**Comment by joewing** [comment]
Thanks for the detailed bug report!
I think this should be fixed in snapshot 1531.  Please let me know if that works for you (I don't have wine installed).

**Comment by foobar0815** [comment]
That fixes the problem indeed. Thanks!
