### ISSUE TITLE
Seperate tray icons/buttons for different instances of same application?

### ISSUE THREAD

**Issue by varmanishant** [joewing/jwm#315]
Currently when I open an application say `pcmanfm` more than once, JWM Tray clubs it into a single Tray Icon `pcmanfm(2)`. Would it be possible to have it separetly listed out? I don't see much benefit in accessing it, in groups in my old computer.

**Comment by joewing** [comment]
In your configuration, set `group="false"` in `TrayStyle`:
```xml
<TrayStyle group="false" ... >
...
</TrayStyle>
```

**Comment by varmanishant** [comment]
Thanks its even documented. I searched for 'group' in the documentation but it took me to Group Settings and that wasnsn't what I needed. Is there a tag for faq, so it would be good to have it as a faq item.
