### ISSUE TITLE
move windows using super

### ISSUE THREAD

**Issue by nixingizgood** [joewing/jwm#324]
I disabled alt-dragging for inkscape using 'nodrag'. Inkscape's tools make use of alt-click dragging to provide additional functionality. For example, doing so with the select tool invokes "freehand select" (versus a rectangular select)

But what I really want is to remap alt-drag to super-drag for moving windows. I have encountered zero conflicts to date, and don't foresee any for the future. Therefore, I consider Super to be the logical choice for movement, and would appreciate an option to set it. 

As an idea... `<MoveMask>4</MoveMask>`

**Comment by joewing** [comment]
I like the idea of making that configurable.  Adding a `mask` attribute to the existing `MoveMode` element is another idea.

**Comment by nixingizgood** [comment]
Indeed, as an attribute seems more correct

**Comment by joewing** [comment]
This should work as of snapshot 1550.

**Comment by HellishINC** [comment]
This really needs to be on the documentaion on https://joewing.net/projects/jwm/config.shtml

I spent about 2 hours looking through the code (I'm no programmer) trying to see if I could accomplish this.

**Comment by joewing** [comment]
Sorry about that.  I usually update the online documentation as I get time or when I'm doing a release (this particular feature isn't in a release yet).  The man page should be more current.

**Comment by HellishINC** [comment]
It's cool, I learned how to create a patch using git diff as well as using makepkg on arch. I just wanted to poke you to update the docs.
