### ISSUE TITLE
inconsistent screen snapping

### ISSUE THREAD

**Issue by nixingizgood** [joewing/jwm#329]
There are 3 ways to move a window that I know of. Dragging titlebar, the move hotkey, and alt-dragging

Here is how screen snapping is working with `<SnapMode>screen</SnapMode>`

Dragging via titlebar, the window will snap to all screen sides

Via move hotkey: no screen snapping...  (and movement will stop when cursor hits a side)

Alt-dragging, same as move hotkey

I am wondering if this is a feature or a bug?

**Comment by joewing** [comment]
This is the intended behavior.  Of course, whether it's the right behavior is arguable.  I think alt+drag used to snap, but snapping was removed due to an explicit request (which I can't seem to find right now).

**Comment by nixingizgood** [comment]
Ok :+1:
