### ISSUE TITLE
Version JWM in conky

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#333]
Hi guys
i want to put the version of JWM in my conky.
when using jwm -v is very large in conky.
see the image: http://wstaw.org/m/2016/09/21/2016-09-21-005520_1366x768_scrot.png
i would like to display the version only (JWM v2.3.6). does anyone have any ideas?

vlw fwi, Holmes :)

**Comment by technosaurus** [comment]
There are several ways to select chunks of text, awk, sed, grep, cut, read... just pipe it through one of those.

**Comment by holmeslinux** [comment]
here use

`${alignr}${color2}${font Cantarell:size=10}${alignr} ${execi 1200 jwm -v}`

vlw fwi, Holmes :)

**Comment by technosaurus** [comment]
replace the jwm -v with your wrapper that cuts out only what you want
${alignr}${font Cantarell:size=10}${alignr} ${execi 1200 jwm_conky_wrapper.sh}
```shell
#!/bin/sh
jwm -v | while read JWM VERSION OTHERGARBAGE; do
echo $JWM $VERSION
exit
done
```

**Comment by holmeslinux** [comment]
@technosaurus , thank you!
It worked in conky....

vlw fwi, Holmes :)
