### ISSUE TITLE
Does not move to the next window in the stacking order

### ISSUE THREAD

**Issue by roandbox** [joewing/jwm#335]
I have got two windows. The first window has a normal layer. The second window has a above layer. Also the second window is active.  When calls a command "nextstacked" does not move to the first window.

**Comment by roandbox** [comment]
`diff -cr a/src/clientlist.c b/src/clientlist.c
*** a/src/clientlist.c  2016-09-14 03:57:29.000000000 +0300
--- b/src/clientlist.c  2016-09-25 17:52:46.000000000 +0300
***************
*** 157,163 ****
           /* Skip this window if it no longer exists or is currently in
            * a state that doesn't allow focus.
            */
!          if(np == NULL || !ShouldFocus(np, 1)) {
              continue;
           }
 
--- 157,163 ----
           /* Skip this window if it no longer exists or is currently in
            * a state that doesn't allow focus.
            */
!          if(np == NULL || !ShouldFocus(np, 1) || np->state.status & STAT_ACTIVE) {
              continue;
           }

`

**Comment by roandbox** [comment]
I'm not sure, but i think for solution of the problem need apply a patch: 
```diff
diff -cr a/src/clientlist.c b/src/clientlist.c
*** a/src/clientlist.c  2016-09-14 03:57:29.000000000 +0300
--- b/src/clientlist.c  2016-09-25 17:52:46.000000000 +0300
***************
*** 157,163 ****
           /* Skip this window if it no longer exists or is currently in
            * a state that doesn't allow focus.
            */
!          if(np == NULL || !ShouldFocus(np, 1)) {
              continue;
           }
 
--- 157,163 ----
           /* Skip this window if it no longer exists or is currently in
            * a state that doesn't allow focus.
            */
!          if(np == NULL || !ShouldFocus(np, 1) || np->state.status & STAT_ACTIVE) {
              continue;
           }
```

**Comment by joewing** [comment]
Your patch makes sense and seems to improve the situation.  Thanks!
