### ISSUE TITLE
3 digit color hexcode interpretation is unexpected

### ISSUE THREAD

**Issue by nixingizgood** [joewing/jwm#336]
# bbb translates to #b0b0b0 in JWM, where as I typically am used to seeing it translate to #bbbbbb. Of course this isn't a bug, but was wondering if you were aware of this?

**Comment by technosaurus** [comment]
That is from [XParseColor](https://cgit.freedesktop.org/xorg/lib/libX11/tree/src/ParseCol.c) ... it is historically flawed to prevent true white (now most code, including jwm translates it to #bbbbbb) ... perhaps it should only call XParseColor if the string does not start with #?

**Comment by joewing** [comment]
JWM handles 3-digit hex strings (rather than passing them along to XParseColor) as of snapshot 1574.
