### ISSUE TITLE
unicode character not appearing in tasklist

### ISSUE THREAD

**Issue by nixingizgood** [joewing/jwm#337]
I'm getting 2 empty boxes instead of a ► in the task list (I think U+25BA or U+25B6). The font is Liberation Sans for both the tab font in Chromium and for the task list 

![playbutton](https://cloud.githubusercontent.com/assets/15900066/19413459/7d757dd2-92e2-11e6-8acb-e28c18d86466.png)

**Comment by ml-** [comment]
You almost got the answer yourself.
**Liberation Sans** simply doesn't have those characters. It will work with every font that contains those chars.

**Comment by 01micko** [comment]
Interesting. I'm running older jwm-2.3.2 with DeJavu Sans and I get the
arrow char plus another empty char.

**Comment by 01micko** [comment]
Screenshot
![jwm](https://cloud.githubusercontent.com/assets/1019119/19413816/04d0baa4-937d-11e6-8884-d17a1ee931f0.png)

**Comment by nixingizgood** [comment]
@ml- Chromium's tab title is using Liberation Sans... so... where is that arrow coming from then, if not the font? Another font?

**Comment by nixingizgood** [comment]
@ml-  I'm looking at Liberation Sans in KCharSelect...  25B6 and 25BA are present

![kchar](https://cloud.githubusercontent.com/assets/15900066/19413999/79f12c12-92f4-11e6-93d1-8db5e3c7d8c8.png)

**Comment by nixingizgood** [comment]
@ml- I think you may be right. 23F5 is a black right pointing triangle that is missing from the font. 

I'm guessing Chromium must have a Unicode fallback font for missing glyphs then. Otherwise, how to explain the triangle in Chromium's tab title? It is using Liberation Sans as the font

**Comment by joewing** [comment]
I think this should be fixed now.
