### ISSUE TITLE
the autohiding tray feature in the horizontal layout positioned to the left,  makes the menu appear only in the top or bottom instead of left 

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#34]
this his what am using in the configuration file for a left tray (autohide="true" halign="left" valign="center" layout="horinzontal") i suggest that the (autohide feature should have  instead of "true" his "left" "right" "top" "bottom" so we can chose wich side off the screen the menu appears back again!

**Comment by joewing** [comment]
This should be available in the latest snapshot.  "true" and "false" are no longer supported since I'm breaking config compatibility anyway.  Now it's "left", "right", "top", "bottom", or "off".
