### ISSUE TITLE
The title bar and move the window: problem

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#341]
hi all,
i am now experiencing something weird. i can open a terminal or folder fine. but, if i grab the title bar and move the window, the contents of that window disappears completely. the folder looks like a big white empty box and the terminal is a black window. i have done some looking in to and it is definitely compton. i removed compton entry from /.jwm/start and everything works correctly. no glitches.

now i do not know if the problem is compton or JWM.
does anyone have any ideas?

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
Hi I have not had any good success with compton in JWM, but that may be just me.
It could be your compton config is odd, OR the terminal emulator you are using.
What terminal emulator are you using?
You might also check the output of your jwm errors (see #322 for in depth details) via jwm -p or your xsession errors.
Both your issues may ultimately be related.
Though I'd be curious to know if anyone has terminal transparency working nicely in JWM.

**Comment by holmeslinux** [comment]
hello Israel,
my setup, see:

in file start

compton -cCGb

in file Compton.conf

# Shadow
shadow = true;            # Enabled client-side shadows on windows.
clear-shadow = true;        # Zero the part of the shadow's mask behind the window (experimental).
detect-rounded-corners = true;
shadow-ignore-shaped = false;
shadow-exclude = ["class_g = 'Conky'"];

i use Sakura terminal emulator and PCManFM.

i used xcompmgr and i do not remember having this problem.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
with jwm -p no errors.
the file .xsession-errors is empty.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
hi all,
below is an image of the problem

http://www.auplod.com/u/lduoap8b460.png

this happens with any application. when moving the mouse occurs this!

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
Does it effect you with different GTK themes?
As I said before I have not gotten compton working correctly in JWM (terminal transparency), but I have not had this particular issue.  So it is either your compton configuration.  It may even be an issue in your gtk theme, as well.  Depending on how it is written... there are odd problems that can come in when the theme is malformed and this could be possible here .

**Comment by holmeslinux** [comment]
hi Israel
yes, it is with all gtk themes.
see how the terminal is

http://www.auplod.com/u/adpoul8b5cb.png

i have no idea what this is!
i have tried everything and nothing to solve.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
@Israel- 
leaving corner zero (setting <Corner>0</Corner> in WindowStyle). solved the problem!

thank you @joewing 

vlw fwi, Holmes :)
