### ISSUE TITLE
aerosnap not working well on multihead

### ISSUE THREAD

**Issue by gensenio** [joewing/jwm#342]
on a dual head setup aerosnap is not working on inner (touching) borders of the two screen.

to explaing better

i have two monitors and the followind xrandr configuration

xrandr --output HDMI1 --left-of HDMI2

aerosnap is not  working on right side onf hdmi2 screen and on the left side of hdmi1 screen.

but is working on others sides

**Comment by joewing** [comment]
I've attempted to make this work better in snapshot 1575, but I don't have a good way of testing.  Please let me know if it works for you or if something could be improved.

**Comment by gensenio** [comment]
Hallo thank you very much, it is working well on my setup!!

Giovanni
