### ISSUE TITLE
Localized TrayButton labels

### ISSUE THREAD

**Issue by ghost** [joewing/jwm#354]
It would be really nice if there was a way to localize TrayButton names, or some special syntax JWM could use to use gettext.sh
perhaps it could be something like
```xml
<TrayButton label="Apps" textdomiain="torios" icon="torios-logo" border="false">
	<Button mask="1">root:2</Button>
	<Button mask="23">root:m</Button>
</TrayButton>
```
This has drawbacks, of course it would require gettext.sh to be installed for scripts.

Or if JWM could include a few of pre-translated words and (I only really need Applications and Places for my purpose) and use special syntax (like a cmake configurable file in my example)
```xml
<TrayButton label="@Applications@" icon="torios-logo" border="false">
	<Button mask="1">root:2</Button>
	<Button mask="23">root:m</Button>
</TrayButton>
<TrayButton label="@Places@" icon="folder" border="false">
	<Button mask="1">root:7</Button>
	<Button mask="23">root:m</Button>
</TrayButton>
```
I think this could go a long way to help more users use JWM.  I know the common way to get around this is by simply making a button with no label

The other way around this would be to be able to reload the Trays (or TrayButtons only) dynamically, which would mean we could also make our own 'indicators'

**Comment by technosaurus** [comment]
Its not really necessary, I just localized the xml generator.  see: http://murga-linux.com/puppy/viewtopic.php?p=871334  I have been meaning to update it for the new dynamic stuff.

**Comment by Israel-** [comment]
@technosaurus That post looks like it is about menus.  My menus work much the same, I have a mostly freedesktop compliant menu that uses a menu file, and directory files to localize the menu, and the desktop files are already localized as much as possible from upstream.

I suppose I could generate xml, but for custom configurations using something like
sed -i "s#@Applications@#$LocalizedApps#g" ~/.jwmrc
wont work.  If there was a **standardized** jwm method for doing so OR a dynamic TrayButton tag it could be very simple... JWM localizes it on the fly.

Then if the user switches languages (say they use Chinese, and English quite often) how do you then translate it back?  
I have directory files to do this already
[/usr/share/desktop-directories/*](https://github.com/Israel-/jwm-menus/tree/master/usr/share/desktop-directories)
specifically:
 [Applications](https://github.com/Israel-/jwm-menus/blob/master/usr/share/desktop-directories/jwm-applications.directory)
[Places](https://github.com/Israel-/jwm-menus/blob/master/usr/share/desktop-directories/jwm-home.directory)

If your method is really viable for the TrayButton, I will close this and use it, all I really want is a better user experience for everyone :smile:

**Comment by technosaurus** [comment]
Actually my method uses a gettext-free technique to provide localization, but you can use gettext in your jwmrc generator something like:
```bash
MYLABEL=$(gettext "My label string")
echo "<TrayButton label=\"$MYLABEL\">"
```
My alternative technique is detailed [here](http://murga-linux.com/puppy/viewtopic.php?t=73440); 

BTW, this discussion has enlightened me that I should probably actually generate a jwmrc.lang-LANG and symlink that to the jwmrc so that if the language doesn't match (via readlink and substring manipulation of the $HOME/.jwmrc) the properly localized version is automatically generated and linked.

**Comment by Israel-** [comment]
@technosaurus I suppose I already have something that does something similar to this, but this will also effect users who do not speak the same language on the system, UNLESS the file is generated each time the user logs in, which would be hard to do if the user has a customized jwmrc file.
It seems that it should make sense to either have translatable labels, or have a few common words with a special syntax for the label.  @APPLICATIONS@  and @HOME@ or something along those lines.

I have not noticed any large lag in using gettext, but it is definitely something to consider, I am also a fan of bash builtins ( [[ vs [  ${thing:-default} etc...)

**Comment by joewing** [comment]
I don't think this is something that JWM should be responsible for doing.  I like the idea of symlinking to language-specific parts or using includes with a preprocessor.  This is part of the reason JWM supports running executables in includes.
