### ISSUE TITLE
`showdesktop` call makes clock tray blank when there are fullscreen windows.

### ISSUE THREAD

**Issue by Magicloud** [joewing/jwm#356]
I just tried to bind Ctrl-Alt-D to showdesktop on JWM 2.3.5. The binding works. The problem is that, when there are fullscreen windows, for example Firefox. Then showdesktop makes clock tray blank when desktop is shown. showdesktop again (the windows are restored) makes the clock showing again.

**Comment by holmeslinux** [comment]
hi
have you tried using version 2.3.6?

vlw fwi, Holmes :)

**Comment by joewing** [comment]
I was able to reproduce this (tray buttons demonstrated the behavior pretty easily).  This should be fixed in snapshot 1577.

Thanks!
