### ISSUE TITLE
Add space in the notification area

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#357]
hi guys
i would like to know if it is possible to place a space between the icons in the notification area
see the image

http://www.auplod.com/u/opdula8ff49.png

all the icons are stuck together...

**the space is possible?**

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
My Dock looks fine...
http://www.auplod.com/u/lopdau8ff5f.png

**Comment by holmeslinux** [comment]
kkkkkkkk...

how did you leave it with space?

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@holmeslinux not sure... I just have
```xml
<Dock/>
```
But it could be the icon theme I am using... I am using Numix-Circle

**Comment by joewing** [comment]
JWM doesn’t leave any space between items in the dock right now, but depending on scaling, some space might show up.  I agree that it would be nice to have to ability to add padding (a padding attribute for `Dock`).

**Comment by holmeslinux** [comment]
thank you @joewing 

vlw fwi, Holmes :)

**Comment by joewing** [comment]
JWM supports the `spacing` attribute in `Dock` as of snapshot 1578.  Please let me know if that solves the problem!
