### ISSUE TITLE
Can JWM handle 30-bit display?

### ISSUE THREAD

**Issue by fhlfibh** [joewing/jwm#358]
Hi,

Kinda stupid question, sorry...

I noticed that with 30-bit display (i.e. `DefaultDepth 30` in `xorg.conf`) some programs show black rectangles in place of images. With 24-bit display same programs show same images with no problem.

I'm trying to find out what exactly causes this issue, and just wanted to make sure, if JWM can handle 30-bit display or not.

Regards,
Alex

**Comment by joewing** [comment]
JWM should be able to handle 30-bit displays (TrueColor, 10 bits per pixel?), but I’ve never tested this mode, so I can’t say for sure everything works.  If some icons aren’t showing up correctly, I would guess there’s a bug in the way some icon format is being converted.  If you give me more information on what images are showing up incorrectly (such as location (task list, menu, window border, etc.) and image format), I might be able to track it down.  A screen shot would be helpful.

Thanks!

**Comment by fhlfibh** [comment]
This is the issue I opened in Dolphin's forum https://forums.dolphin-emu.org/Thread-dolphin-5-0-on-linux-black-images-in-place-of-banners
and screenshot for it http://s019.radikal.ru/i602/1701/16/5790548a7982.png

Or if you have GIMP installed -- when it starts, it should normally show like a fox face splash-screen for some seconds. With 30-bit it shows only a black rectangle. Don't know how to make screenshot of it.

I'm not sure that something is wrong with JWM. It might be a GTK bug or something. Just trying to rule variants out.

**Comment by fhlfibh** [comment]
Made some more tests. JWM itself seems to be Ok with 30-bit display. It's programs that have problems...
I close this issue for now.
Thanks a lot for your help!
