### ISSUE TITLE
Move windows along the tray

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#359]
hi guys
i would like to know if it is possible to move with the mouse the windows that are in the tray
for example: if the tray has five windows
1 2 3 4 5
i want to move the 5 to the beginning
5 1 2 3 4
it's possible?

vlw fwi, Holmes :)

**Comment by technosaurus** [comment]
This should probably reference the drag and drop issue.

**Comment by holmeslinux** [comment]
ok
how to activate this option?

vlw fwi, Holmes :)

**Comment by joewing** [comment]
I believe this is a duplicate of #347 (which has not yet been implemented).  If that's not the case, please let me know how it differs and re-open.
