### ISSUE TITLE
How install JWM on LinuxMint 17.3 in one click?

### ISSUE THREAD

**Issue by Symbian9** [joewing/jwm#360]
I would be happy if you could make "LinuxMint 18.x JWM"

But currently, more realistic would be if you describe how replace Xfce with JWM on LinuxMint 17.3

**Comment by joewing** [comment]
This sounds like an issue for a package maintainer of JWM.  It’s outside the scope of JWM to support every possible OS/distribution.

**Comment by Israel-** [comment]
@Symbian9 I am in contact with the Debian package maintainer, and there is a pretty new version in Debian which Linux Mint is based on.
`sudo apt install jwm`
Should work on the newer versions of Linux Mint, though I don't use Mint so I don't know if 18 is newer or not.
If it is older you can use
`sudo apt-get install jwm`
I also maintain a PPA of various programs that help turn JWM into something more similar to XFCE with a self generating menu, and a graphical settings program, as part of ToriOS which is based on Debian, and works well in Ubuntu as well.
