### ISSUE TITLE
How to map the volume and brightness keys in jwm?

### ISSUE THREAD

**Issue by varmanishant** [joewing/jwm#361]
How can I map the volume and brightness keys to jwm?

**Edit this works:**
```
    <Key key="XF86MonBrightnessUp">exec:{command}</Key>
    <Key key="XF86MonBrightnessDown">exec:{command}</Key>
    <Key key="XF86AudioRaiseVolume">exec:amixer -q sset Master,0 5+</Key>
    <Key key="XF86AudioLowerVolume">exec:amixer -q sset Master,0 5-</Key>
    <key key="XF86AudioMute">exec:amixer -q sset Master,0 toggle</Key>
```

**Comment by varmanishant** [comment]
Mute works! I guess this is the way to do, just that my machine is not working correctly?

**Comment by roandbox** [comment]
https://wiki.archlinux.org/index.php/Backlight

**Comment by varmanishant** [comment]
Hmmm for some reason xbacklight is not working. So might need to directly. Thanks.

**Comment by Israel-** [comment]
Here are my scripts:
[Volume Down](https://github.com/Israel-/torios-core/blob/master/usr/bin/amixer-down)
[Volume Up](https://github.com/Israel-/torios-core/blob/master/usr/bin/amixer-up)
[Mute/Toggle](https://github.com/Israel-/torios-core/blob/master/usr/bin/amixer-toggle)
[Microphone Mute](https://github.com/Israel-/torios-core/blob/master/usr/bin/amixer-mic-mute)

[Brightness Up/Down/Reset (or gamma)](https://github.com/Israel-/torios-core/blob/master/usr/bin/torios-gamma)
This is run as
`torios-gamma up`
`torios-gamma down`
`torios-gamma`
This uses xbacklight if it exists, and works, OR xgamma if xbacklight isn't installed or doesn't support your monitor

Feel free to modify these to your own use in anyway you choose.

**Comment by varmanishant** [comment]
Thank You. I will check your scripts.
