### ISSUE TITLE
Fullscreen Firefox and Conky bug when JWM reloads.

### ISSUE THREAD

**Issue by Magicloud** [joewing/jwm#363]
To reproduce, start a Firefox and turn to fullscreen, and a Conky, and a regular window. Then `jwm -reload`. Then, seems like Conky's layer is not handled well that I can switch to its layer as a white blank fullscreen area.
JWM is 2.3.6.

**Comment by joewing** [comment]
This may be fixed with snapshot 1582 (the cause might be the same as #340).

**Comment by Magicloud** [comment]
Sorry response late. I did wrong verification and thought this was fixed in s1582. It does not, even the latest release s1592.

**Comment by Magicloud** [comment]
Seems fixed. in 2.3.7
