### ISSUE TITLE
Disable mouse scroll of virtual desktops

### ISSUE THREAD

**Issue by david2012brooke** [joewing/jwm#366]
I would like to disable the virtual desktop selection via the mouse scroll wheel on the root window but I can't find any documentation or other user info.

Per the JWM site "Scrolling up on the root window switches to the left desktop and scrolling down switches to the right desktop". 
https://joewing.net/projects/jwm/config.shtml#mouse

**Comment by J-Reis** [comment]
This would be a useful enhancement. Though not essential, I do occasionally confuse myself when the screen suddenly goes crazy … and it takes a moment or (embarrassingly) two to realize that my cursor has wandered over root while I read, etc.

**Comment by romeojulietthotel** [comment]
I think it's an essential feature, ability to remap or disable,  that's needed. It has become annoying to the point that I may look at another wm. But I like jwm for it's simplicity and that it works just fine.

I don't mind the feature of scrolling the desktop but my problem is that it always happens by accident. I'm not sure but sometimes it seems as if the pointer jumps to the edge when I want to scroll in the browser.

**Comment by joewing** [comment]
Snapshot 1599 allows you to define an empty root menu as a means to disable desktop switching by scrolling on the desktop:
```xml
<RootMenu onroot="45"/>
```

**Comment by romeojulietthotel** [comment]
@joewing thanks for snapshot 1599, it does work as you documented. One problem for me is if I access my jwm desktop via vnc then I really need that root menu.  I have to guess that just disabling the mousewheel on the desktop is harder to accomplish.  i.e. 
`<RootMenu onroot="13"/>`

But mouse bindings look like the long term solution or do I misunderstand that feature?

**Comment by joewing** [comment]
Disabling the scroll wheel should be:
```xml
<RootMenu onroot="45"/>
```
and you should be able to keep menus for the other buttons.  Is there some reason that doesn't work within VNC?

Obviously, mouse bindings will be a cleaner solution, but this should work just as well for this particular purpose.

**Comment by romeojulietthotel** [comment]
If I set onroot="45" I can press the middle-mouse-button and then scroll to see a menu. Left mouse button click shows no menu nor does the right button.

In my previous comment I didn't then realize that the middle-mouse would raise a menu but only when the wheel is scrolled. That's not a feature I would use since I don't like it.

Maybe I just have bad expectations or I am misunderstanding something here. All I want is to never scroll between desktops by scrolling the mousewheel. But I want left or right button to pop up the menu.

**Comment by joewing** [comment]
Set `onroot="45"` in a new, empty, root menu (you can have multiple).  You can disable the scroll wheel affecting anything completely and have a root menu show up with buttons 1, 2, and 3.

**Comment by romeojulietthotel** [comment]
LGTM!  Thank you for your time and efforts. Jwm is nice and simple and lightweight!
