### ISSUE TITLE
Does StartupCommand guarantee execution after JWM is up and running?

### ISSUE THREAD

**Issue by limelime** [joewing/jwm#371]
I have scripts that run from <**StartupCommand**>.

Sometimes, I get the following errors and sometimes not(Run from ISO):
```
volumeicon: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
wicd-client.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

It looks like <**StartupCommand**> is not guaranteed to be executed after JWM is up and running. Does it?

**Comment by technosaurus** [comment]
It sounds like your xinit program is starting the window manager before the X server is fully up and running.  You can either change that or add something to your startup command to check that X is up
in bash/posix shell you can wait for X to come up with something like:

    `while [ ! -S "/tmp/.X11-unix/X" ]; do sleep 0.1;done`

in python you can use similar code on the same file (if your system uses the unix socket) or IIRC there is a virtual socket ... sorry my python is rusty or I'd post a python snippet (The only time I used it was to get to level 5 of Google's foobar challenge)

**Comment by limelime** [comment]
@technosaurus , thx for the info. I'm using 64-bit version of libxcb =1.10-3+b1. From the bug, 64-bit version shouldn't be affected.

I did add a wait for X to come up to run the other applications.

Still I find it weird that I got the error on startup and JWM is still running fine.
My expectation of running sequence would be:
```
X -> JWM -> whatever script that are put in <StartupCommand> configuration.
```
