### ISSUE TITLE
Mouse pointer is very strange!

### ISSUE THREAD

**Issue by kibojoe** [joewing/jwm#376]
hi guys,
here is the Holmes (holmeslinux)... :)
well, sometimes the mouse pointer is very strange, see image

http://wstaw.org/m/2017/04/21/IMG_20170421_242256407_1.png

i do not know why this occurs
to return to normal i have to restart the pc

**what can this be? a bug of JWM?**

obs: use JMW 2.3.6

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@kibojoe are you using a compositor (i.e. compton) and NVidia graphics card.  That is what it looks like to me.

**Comment by joewing** [comment]
This doesn’t seem like something that would be caused by JWM (JWM doesn’t draw the cursor, so if JWM were the cause, exiting JWM should fix it).
