### ISSUE TITLE
Font hinting

### ISSUE THREAD

**Issue by Gavcheg** [joewing/jwm#378]
Please add support of font hinting. Antialias is fine, but without hinting options many fonts (for example Verdana) looks really ugly.

**Comment by roandbox** [comment]
Use the XFT syntax: 
```
Verdana-10:hinting=True
```

**Comment by Gavcheg** [comment]
It work! Xft syntax support work as expected. I simly forgot set hintstyle..
Now it looks like "Verdana-11:antialias=true:encoding=utf8:hinting=1:hintstyle=hintfull:weight=bold" if anyone intresting.. 
Thanks! 
Now i close this ticket.
