### ISSUE TITLE
Assigning the windows key as a mask does not work

### ISSUE THREAD

**Issue by eamdog** [joewing/jwm#379]
Hi. I am trying to make keybindings with my windows key but something goes wrong when I use the key as a mask. xev reports the button to be Super_L. For instance, I tried mask="Super_L" key="d" for showing the desktop but it doesnt work. Instead, Shift + d started showing me the desktop. This happens with every combination that involves Super_L. Surprisingly, assigning Super_L as a key alone works just fine. This has left me clueless. 
I am on 4.4.0-72-generic with ubuntu base. Currently using JWM v2.3.5. My keyboard is a "Microsoft Wired Keyboard 600"

**Comment by Israel-** [comment]
Hi @eamdog for me it is `4`
For example I use this
```xml
<Key mask="C4" key="Up">maxtop</Key>
<Key mask="C4" key="Left">maxleft</Key>
<Key mask="C4" key="Right">maxright</Key>
<Key mask="C4" key="Down">maxbottom</Key>
```
Control + Super (4) + *directional key*

**Comment by technosaurus** [comment]
IIRC this depends on which modifier your distro sets the key to (using xmodmap usually) ... maybe in your .xinitrc?

**Comment by myself12345** [comment]
I use Super+d key and it works for me :
<Key mask="4" key="d">exec:wmctrl -r :ACTIVE: -b remove,fullscreen; wmctrl -k on </Key>
The key mask is "4" for ' window' key
