### ISSUE TITLE
Root menu opening in the extended desktop monitor (dual monitors setup)

### ISSUE THREAD

**Issue by rGabiru** [joewing/jwm#384]
Hi,

I have a dual-monitor setup where my Trays, that include icons, menu, clock, etc are on the left screen, and the right screen is used mainly as an extended desktop to where i drag windows.

The issue is when I mouse click near the right hand side of the left monitor, the Root menu will appear on the right monitor. (i believe it should detect i am clicking near the edge of the screen, and thus appearing on the left). 

I hope I'm describing this issue clearly.

**Comment by joewing** [comment]
Unfortunately, I lack a dual monitor setup to test. Just to be sure, this is a recent build (2.3.6 or later) correct?  JWM should be confining menus to a particular screen, though it's possible that JWM is initially selecting the wrong screen.  Does it help to make the tray smaller?

**Comment by rGabiru** [comment]
Yes, this is occurring with the last build available (2.3.6).
Making the tray small doesn't help in this because i have two root menus one on the left and one on the right, where i keep logoff, shutdown, etc)
![19859105_1500681403285495_1203284244_o](https://user-images.githubusercontent.com/29799457/28082679-0f1bf4a8-666b-11e7-894d-2823815b7c54.jpg)
![19897910_1500681386618830_365640538_o](https://user-images.githubusercontent.com/29799457/28082686-134e4df0-666b-11e7-979b-a8b56c5034b6.jpg)

**Comment by joewing** [comment]
It's strange that the menu is spanning screens like that.  I could see the menu appearing on the wrong screen in your second example, but the menu show always show up completely on one screen.  Is JWM compiled with Xinerama support and is Xinerama supported by your X server?
Running `jwm -v` should tell you if JWM was compiled with Xinerama, you should get something like:
`compiled options: confirm debug icons jpeg png shape xbm xft xinerama xpm xrender`.
I imagine the X server would output whether Xinerama is enabled in a log file.

**Comment by rGabiru** [comment]
I installed jwm via the package manager of my distribution but it was compiled with Xinerama nonetheless. the output of my `jwm -v` is `compiled options: confirm fribidi icons jpeg nls png shape svg xbm xft xinerama xpm xrender` could this be related with my `xrandr` config?

i have `xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output DP2 --off --output HDMI2 --off --output HDMI1 --mode 1280x1024 --pos 1280x0 --rotate normal --output VGA1 --mode 1280x1024 --pos 0x0 --rotate normal`

**Comment by joewing** [comment]
I think this should be fixed as of snapshot 1598.  Please let me know if that works for you!
Thanks!

**Comment by rGabiru** [comment]
Unfortunately it didn't work. I compiled and installed. `jwm -v` gave me the version 2.3.7 so i believe it is correctly installed.

**Comment by joewing** [comment]
So this fixed it for me.  Are you sure it's actually running the new version?  You should be able to just run `jwm -v` to verify the right executable and then `jwm` directly in the terminal to cause JWM to replace the old process.

**Comment by rGabiru** [comment]
actually it worked! there was a conflict with jwm versions installed. The menu is showing in the correct screen now. Solved!
Many thanks

**Comment by joewing** [comment]
Awesome! Thanks!
