### ISSUE TITLE
Odd interaction between JWM and Firefox causes Firefox to crash

### ISSUE THREAD

**Issue by willbprog127** [joewing/jwm#385]
Hi Joe,
I know this is a Firefox issue (sort of) but it only seems to happen in JWM.  

When I double-click an empty spot near the 'new tab' button, JWM maximizes Firefox.  When I double-click it again, Firefox crashes.  

Here is the location where I double-click:
![](https://www.pismotek.com/media/jwm-firefox-double-click-issue-2017-07-08b.png)

I have already reported this to Mozilla, but ~~I know it'll take a billion years~~ historically it has taken a while for them to address other issues.  There's just some odd interaction going on with JWM and Firefox as this doesn't happen on Fluxbox or Mate.

Can you reproduce this?

Thanks Joe! 😄

**Comment by willbprog127** [comment]
(Second) bug report filed with Mozilla
    https://bugzilla.mozilla.org/show_bug.cgi?id=1379434

**Comment by yetanothergeek** [comment]
Happens to me too, with Firefox-54.0.1. Just recently switched to Void Linux but it was also happening on Arch. I prefer my tabs on the side, and installing the "Vertical Tabs Reloaded" extension somehow hides the problem (Clicking on an empty space in the tabbed sidebar works as intended, opens a new tab.)

**Comment by joewing** [comment]
Thanks for reporting this and narrowing it down!  I'm pretty sure I've run across this before without realizing what happened.  In any case, I am able to reproduce this, so hopefully I'll have a fix soon.

**Comment by joewing** [comment]
I haven't found an easy way to work around this yet.  JWM gets an initial ConfigureRequest, but doesn't see an event from the second click.  So Firefox may be expecting something specific in response to the first configure request perhaps.

Just as another data point, this happens for me with TWM as well.

**Comment by samueloph** [comment]
I don't know if you already know this, but the expected behavior of double clicking that area should be to open a new tab. I can confirm that this works under i3.

**Comment by willbprog127** [comment]
@samueloph and @joewing thanks for that.  So maybe it's an issue that needs to be resolved on both sides...?  At any rate, the bug report I filed with Mozilla has been triaged, so hopefully something will become of it.

**Comment by willbprog127** [comment]
Based on further testing, Firefox 45.0.2 was the last version that *didn't* crash when the empty space next to the 'New Tab' button is double-clicked.  Instead of crashing, 45.0.2 opens a new tab when the area in question is double-clicked.  45.0.2 also appears to be the last major Firefox version that is Gtk 2.  Looks like the issue might be based on the migration to Gtk 3.

**Comment by willbprog127** [comment]
It appears that this has been addressed at Mozilla.  The status of the bug is `RESOLVED`.  Hopefully the fix will appear in a Firefox release soon.

https://bugzilla.mozilla.org/show_bug.cgi?id=1379434
