### ISSUE TITLE
Virtual desktop no work

### ISSUE THREAD

**Issue by kibojoe** [joewing/jwm#388]
hi guys,
my virtual desktop is not working
by clicking on them does not occur nothing

any idea?

vlw fwi, Holmes :)

**Comment by joewing** [comment]
Virtual desktops work fine for me, what specifically is not working for you?

**Comment by kibojoe** [comment]
i have two virtual desktop (1 2)
i work in the first virtual
when i click on the second 2 it does not change anything

vlw fwi, Holmes :)

**Comment by joewing** [comment]
I assume you mean the JWM pager? This works for me.  What version of JWM?  Does it fail even with the default configuration and no other program that might interfere running?  I need more information to be able to reproduce this.

**Comment by kibojoe** [comment]
version JWM 2.3.6
my configurations in https://github.com/kibojoe/desktop-settings-kibojoe/tree/master/shared/skel_new/.jwm
i do not know what could be happening!

**Comment by joewing** [comment]
Is this something that you just noticed broke recently or?  Does it work with the default configuration?

**Comment by kibojoe** [comment]
i compared my configuration with the default and found nothing wrong

**Comment by kibojoe** [comment]
strange things are happening
when i open the terminal virtual desktop works
see images
http://www.auplod.com/u/pluoda9a434.png
http://www.auplod.com/u/lapudo9a435.png
i took the test with the file manager
is on virtual desktop 1 and clicking on 2 (it is empty) nothing happens
the virtual desktop image is transferred to 2
see images
http://www.auplod.com/u/puloda9a436.png
http://www.auplod.com/u/pudloa9a438.png
very strange...

vlw fwi, Holmes :)

**Comment by STrRedWolf** [comment]
Are you using a file manager that slaps icons onto the desktop?

**Comment by kibojoe** [comment]
the desktop has no icons
this also occurs with the browser (palemoon)

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
i'm going to review some things here
i think i know what happened!

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
really is in trouble here
one thing I noticed is that sometimes works and sometimes does not work
for example, now restart the pc and the virtual desktop is not working

vlw fwi, Holmes :)

**Comment by yetanothergeek** [comment]
Just curious, do the keybindings Ctrl+Alt+Right Ctrl+Alt+Left still work?

**Comment by kibojoe** [comment]
@yetanothergeek 
yes, is work!
but the windows that are in 1 are also in 2

vlw fwi, Holmes :)

**Comment by joewing** [comment]
Sounds likely that some application is telling JWM that it wants to be on all desktops.  Not enough information here to say for sure.

**Comment by kibojoe** [comment]
strange this...
because sometimes the virtual desktop work?
and sometimes not?
do you have any problems with my settings?

vlw fwi, Holmes :)

**Comment by kibojoe** [comment]
hi all,
in versions of Manjaro JWM the virtual desktop worked
i do not know why it's not working now.
i will have to remove it from the new version of Kibojoe Linux 17.09

vlw fwi, Holmes :)

**Comment by joewing** [comment]
Does this happen with the default configuration included with JWM?  Does it happen with an application I'm likely to have (xterm, perhaps)?  What does `xprop` say when you run it and click a window that is showing up on multiple deskops?

**Comment by kibojoe** [comment]
Does this happen with the default configuration included with JWM?
>>> the same thing

Does it happen with an application I'm likely to have (xterm, perhaps)?
>>> xterm appears in both on multiple desktops

What does xprop say when you run it and click a window that is showing up on multiple desktops?
>>> the result https://gist.github.com/kibojoe/9afca47ce769d7b2649dac4f0568a5bb

i do not know what is happening!
in previous versions of Manjaro JWM is working well

vlw fwi, Holmes :)

**Comment by joewing** [comment]
This doesn't happen for me with xterm.  `_NET_WM_STATE_STICKY` is set on that window, so JWM thinks the window should be on all desktops.  Unfortunately, I don't know how that property got set.  JWM is capable of setting it as are other applications.  xterm itself almost certainly wouldn't set it.  If you run nothing but JWM and xterm, does it still happen?

**Comment by kibojoe** [comment]
@joewing 
i found the error
this **<Option>sticky</Option>** was enabled
I disabled it and now it works

**Comment by joewing** [comment]
That's good to hear, thanks for the update!
