### ISSUE TITLE
Change window placement on opening to be below the mouse?

### ISSUE THREAD

**Issue by rGabiru** [joewing/jwm#393]
Following the issue https://github.com/joewing/jwm/issues/312 i tried to add `gsimplecal` to open when clicking on the clock. It works except that the calendar opens at the very top of the screen, which means i cannot click again to close the calendar.
![image](https://user-images.githubusercontent.com/29799457/28493859-885fc070-6f16-11e7-94b9-6da6a1b9f840.png)

I noticed that all my windows are opening centered with the mouse position. Is there way to open at least `gsimplecal` to be immediately below the below the mouse and not under it?

**Comment by joewing** [comment]
JWM supports a few placement policies, but none of them center the window under the mouse, so I assume that's the program itself?  You could use the `pignore` [group option](http://joewing.net/projects/jwm/config.shtml#groups) to have JWM ignore the program-specified placement.

The placement policies JWM supports are `centered` (centers the window on the screen), `tiled` (tiles the windows to avoid overlap, and cascaded, which is the default if nothing else is specified.  It's also possible to specify explicit `x` and `y` coordinates (this is a relatively new feature).  Placement polices are all [group settings](http://joewing.net/projects/jwm/config.shtml#groups).

**Comment by rGabiru** [comment]
I tried with the new `x` and `y` placement and it works for what i pretend. thanks for the help
