### ISSUE TITLE
Key binding to send a window to a specific desktop

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#395]
A follow on to #119.
The idea is to have a key binding to send a window to a specific desktop rather than just up/down/left/right.  Something like “send#”.

**Comment by joewing** [comment]
This is available as of snapshot 1621.

**Comment by varmanishant** [comment]
@joewing, How do I make a binding for this? I have the below bindings to switch desktops. Can I add a "Shift" to this and use that to move windows across desktops? I am using the latest jwm.

```
    <Key mask="4" key="Right">rdesktop</Key>
    <Key mask="4" key="Left">ldesktop</Key>
    <Key mask="4" key="Up">udesktop</Key>
    <Key mask="4" key="Down">ddesktop</Key>

```

**Comment by joewing** [comment]
This issue added the `send#` binding, which sends a window to a specific desktop identified by whatever number you select (having a mask of alt with the `send#` binding will allow you to press alt+5 to send to desktop 5).

I think you are interested in the `sendl/r/u/d` bindings, which send the window left/right/up/down.

**Comment by varmanishant** [comment]
Thank You. I actually needed `send#` itself. I pasted the wrong section here!

I have `<Key mask="4" key="#">desktop#</Key>`

The problem was that I was still using `/bin/jwm` while the latest was in `/usr/local/bin/jwm`.
