### ISSUE TITLE
Restore `autohide="on"` functionality

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#398]
With the fix for #34, JWM made it necessary to specify the position of the tray for auto-hiding.  Unfortunately, this seems to cause some confusion and also makes re-positioning the tray somewhat more difficult than it should be.  To address this, JWM should support `on` such that JWM would use the old algorithm for deciding where to hide the tray.

**Comment by Israel-** [comment]
@joewing will it support ALL the current attributes as well.
I.E.
```xml
<Tray autohide="on"></Tray>
<Tray autohide="left"></Tray>
<Tray autohide="right"></Tray>
<Tray autohide="top"></Tray>
<Tray autohide="bottom"></Tray>
<Tray autohide="off"></Tray>
```

**Comment by joewing** [comment]
That's the plan: make it possible to override what JWM would decide by setting it explicitly or have JWM pick something based on where the tray is positioned (via `on`).

**Comment by Israel-** [comment]
@joewing great!  I think that makes it easier for end users, but also supports the 'power user' to be able to fine tune their system to their exact specifications!
