### ISSUE TITLE
[1628] Does not find /etc/jwm/system.jwmrc anymore

### ISSUE THREAD

**Issue by jdoe0154** [joewing/jwm#399]
jwm 1628 does not find the system configuration file "/etc/jwm/system.jwmrc" any longer on my computer, even though it exists:

```
root [~] jwm -v
JWM vgit-1628 by Joe Wingbermuehle
compiled options: icons png xft xinerama 
system configuration: /etc/jwm/system.jwmrc
root [~] jwm -p
JWM: warning: configuration error: could not open $XDG_CONFIG_HOME/jwm/jwmrc or /etc/jwm/system.jwmrc
root [~] ls -l /etc/jwm
total 8
-rw-r--r--    1 root     root          5418 May  7 04:14 system.jwmrc
```

So when starting X, I get a blank desktop without root menu, task bar, keyboard shortcuts, or any other jwm functionality. As a workaround I have now created the directory "~/.config/jwm", and there inside, a link named "jwmrc" which points to the system configuration file. This makes everything work again, but is certainly not the intended way of accessing the system-wide configuration.

**Comment by STrRedWolf** [comment]
Dumb question, but what's the output of `ls -1l /etc/jvm` ?

**Comment by jdoe0154** [comment]
Unsurprisingly, `ls -1l /etc/jwm` gives the exact same output.

**Comment by STrRedWolf** [comment]
Okay, I mistyped that.  Try `ls -dl /etc/jvm` (-d for the "list the directory entry itself, not it's contents")

**Comment by jdoe0154** [comment]
```
root [~] ls -dl /etc/jwm
drwxr-xr-x    2 root     root          4096 May  7 04:14 /etc/jwm
```
Thank you for your interest. What are you after? The configuration file exists, it works flawlessly with all jwm versions up to 1604, and it works with jwm 1628 via the symlink described above.

**Comment by joewing** [comment]
Thanks! This should be fixed in snapshot 1629.

**Comment by jdoe0154** [comment]
Yes, snapshot 1629 fixed it. Thank you! Closing the bug report.

**Comment by STrRedWolf** [comment]
Just eliminating some of the "easy" answers.  Joe got it.
