### ISSUE TITLE
[[BUILD]] configuration error in configure file

### ISSUE THREAD

**Issue by Obarun** [joewing/jwm#401]
hi there,

on latest release 2.3.7 : 

`./configure: line 5455: AM_PROG_MKDIR_P: command not found
./configure: line 6542: gt_INTL_MACOSX: command not found
`

Obviously, this is not break the build process.

Regards

**Comment by joewing** [comment]
The build should be somewhat cleaner as of snapshot 1636.

**Comment by Obarun** [comment]
thanks
