### ISSUE TITLE
Sticky Keys - Accessability

### ISSUE THREAD

**Issue by Israel-** [joewing/jwm#402]
Hi, a user just commented to me about something they require.  Does a way exist to make 'Sticky Keys' in JWM?
Even some sort of external program would be fine, but if the responsibility should lie in JWM code, is this more than a trivial addition of an option
```xml
<StickyKeys>on</StickyKeys>
<!-- or perhaps something like CSA4 i.e. the modifier keys -->
```
I will have to gather more information on what would actually be required, but as I understand it it would make things like Control, Super, Shift, Alt into a toggle key

**Comment by Israel-** [comment]
Another issue I was presented was the ability to find the cursor on clicking the desktop.
I am hoping for something like this:

```xml
<Mouse context="desktop" button="1">exec:find-cursor</Mouse>
```

The `<Mouse>` documentation doesn't exist on your site nor in
`man jwm`

**Comment by joewing** [comment]
Sticky keys is already handled by X11 using the `xkbset` program.  The window manager really shouldn't be doing that type of thing.

Using a mouse binding as you mention would probably be my preference for a way to find the mouse.  As far as the documentation is concerned, the man page is up-to-date (see the `MOUSE BINDINGS` section), but there is no 2.4 documentation on the website yet (it turns out I enjoy writing the code more than the documentation :smile:  ).

**Comment by Israel-** [comment]
thanks @joewing I mean the documentation about context
```xml
<Mouse context="title" button="1">move</Mouse>
```
The man page and web site are the same on 2.4.0 for me...
I didn't see anything about context or button there.  sorry if I skimmed it too fast

I didn't know if there was a "desktop" context or what other contexts were available for the Mouse Element... the button part is obvious to me from using root menus and button masks in my tray buttons

**Comment by Israel-** [comment]
I am glad you like coding more @joewing , it has made for my favorite computing experience!

**Comment by joewing** [comment]
The mouse binding documentation is [here](https://github.com/joewing/jwm/blob/master/jwm.1.in#L1727).

**Comment by Israel-** [comment]
I must have a slightly older one... sorry for the trouble.... I didn't rebuild the last couple of commits, I've  been busy... as always you rock thanks Joe!

**Comment by joewing** [comment]
No problem!

It occurs to me that `root` for the desktop might not be terribly descriptive these days, though it's pretty pervasive X11 terminology...

Thanks for the kind words!

**Comment by Israel-** [comment]
if root will work then this can be officially closed.
You deserve more than kind words, but again thanks for all you do for us!
