### ISSUE TITLE
Sensors temperature tray

### ISSUE THREAD

**Issue by Ygarr** [joewing/jwm#405]
No way to control temperature sensors in tray. But there is one in Puppy linux distribution only

**Comment by joewing** [comment]
I assume Puppy Linux has an application that either uses the [system tray protocol](https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html) or is just swallowed via a [`Swallow` tray component](http://joewing.net/projects/jwm/config.shtml#trays).  In any case, this type of thing is outside the scope of JWM (as are things such as load monitors, etc.).

**Comment by 01micko** [comment]
[pmcputemp](https://github.com/01micko/pmcputemp) is what you are looking for and should run in any linux (tested in slackware) as normal user and can be compiled against gtk 2 or 3.

Be warned it hasn't been updated in a while and _don't_ enable the lmsensors option as there are unicode and memory leak issues. I intend to remove that code.
