### ISSUE TITLE
Windows cannot be moved, closed, right-clicked, etc.

### ISSUE THREAD

**Issue by willbprog127** [joewing/jwm#406]
Hi Joe,

With the very latest git version of JWM (d664eba) when attempting to drag, close, right-click, iconify, restore, maximize or resize windows, nothing happens.  I have not changed my mouse or keyboard mappings and the latest release of JWM available on your site works fine.  Windows can be iconified by clicking the task button or closed by quitting the program using the program's Quit item, but JWM windows will not do anything by clicking the decoration.

My build config:
`./configure --disable-confirm --disable-cairo --disable-rsvg --disable-fribidi --disable-nls --disable-shape`

I am running JWM on PCLinuxOS, no systemd with the following command-line:
`exec ck-launch-session dbus-launch --sh-syntax --exit-with-session /home/will/apps/bin/jwm`

I have run JWM with this command-line just fine on other distros (and the latest non-git release), so I'm not sure what's going on.

Thanks! 😄

**Comment by Israel-** [comment]
Hi @willbprog127 There was a major breaking change that allows things to be customized more fully.
[HERE](https://github.com/joewing/jwm/blob/master/jwm.1.in#L1715) is the <Mouse> documentation

Basically the answer is to use xsltproc and [this file](https://github.com/joewing/jwm/blob/master/xslt/jwm-2.4.xslt)
I think there should be a default action setup to avoid this issue, however I like the new features.
You can now configure the placement and order of window buttons.
You can simply manually copy over the Mouse context stuff into your jwmrc or use xsltproc it will also modify the tasklist grouping

**Comment by willbprog127** [comment]
@Israel- Thanks for letting me know.  When I read raw man code my eyes glass over. :-P

This throws me for a loop.  I'm going to try to find an older release until the smoke clears.

Thanks!

**Comment by Israel-** [comment]
@willbprog127 
Here is the stuff to add.
It is really simple.  But the usefulness of this is pretty large.  You can make mouse context for the desktop (like running programs when you click) So the benefits are much greater than the slight inconvenience!
:smile: 

```xml
	<Mouse context="title" button="1">move</Mouse>
	<Mouse context="title" button="2">move</Mouse>
	<Mouse context="title" button="3">window</Mouse>
	<Mouse context="title" button="4">shade</Mouse>
	<Mouse context="title" button="5">shade</Mouse>
	<Mouse context="title" button="11">maximize</Mouse>
	<Mouse context="icon" button="1">window</Mouse>
	<Mouse context="icon" button="2">move</Mouse>
	<Mouse context="icon" button="3">window</Mouse>
	<Mouse context="icon" button="4">shade</Mouse>
	<Mouse context="icon" button="5">shade</Mouse>
	<Mouse context="border" button="1">resize</Mouse>
	<Mouse context="border" button="2">move</Mouse>
	<Mouse context="border" button="3">window</Mouse>
	<Mouse context="close" button="-1">close</Mouse>
	<Mouse context="close" button="2">move</Mouse>
	<Mouse context="close" button="-3">close</Mouse>
	<Mouse context="maximize" button="-1">maximize</Mouse>
	<Mouse context="maximize" button="-2">maxv</Mouse>
	<Mouse context="maximize" button="-3">maxh</Mouse>
	<Mouse context="minimize" button="-1">minimize</Mouse>
	<Mouse context="minimize" button="2">move</Mouse>
	<Mouse context="minimize" button="-3">shade</Mouse>
```
