### ISSUE TITLE
Key bindings to resize a window from all sides/corners.

### ISSUE THREAD

**Issue by Obarun** [joewing/jwm#409]
maybe i do something wrong with the configuration file but resizing window with ALT+Left mouse button only pick the bottom right corner of the windows. It's impossible to resize by e.g the top left corner of the windows. This is a normal behaviour?
Passing through the menu when i click with the left button on the task list and picking the resize option give me the same behaviour.
If this behaviour is not expected , can you enlight me what i need to do?
If this behaviour is normal, can you please add the possibility to resize window whatever the corner picked? 

Edit : i use the last release available  2.3.7

**Comment by Israel-** [comment]
Hi @Obarun In the most recent git version (2.4.0 version) the ability to configure the resize option is very configurable.  The mouse context can be changed for MANY actions.
For a list  `man jwm` in the latest version
Example:
```xml
	<Mouse context="title" button="1">move</Mouse>
	<Mouse context="title" button="2">move</Mouse>
	<Mouse context="title" button="3">window</Mouse>
	<Mouse context="title" button="4">shade</Mouse>
	<Mouse context="title" button="5">shade</Mouse>
	<Mouse context="title" button="11">maximize</Mouse>
	<Mouse context="icon" button="1">window</Mouse>
	<Mouse context="icon" button="2">move</Mouse>
	<Mouse context="icon" button="3">window</Mouse>
	<Mouse context="icon" button="4">shade</Mouse>
	<Mouse context="icon" button="5">shade</Mouse>
	<Mouse context="border" button="1">resize</Mouse>
	<Mouse context="border" button="2">move</Mouse>
	<Mouse context="border" button="3">window</Mouse>
	<Mouse context="close" button="-1">close</Mouse>
	<Mouse context="close" button="2">move</Mouse>
	<Mouse context="close" button="-3">close</Mouse>
	<Mouse context="maximize" button="-1">maximize</Mouse>
	<Mouse context="maximize" button="-2">maxv</Mouse>
	<Mouse context="maximize" button="-3">maxh</Mouse>
	<Mouse context="minimize" button="-1">minimize</Mouse>
	<Mouse context="minimize" button="2">move</Mouse>
	<Mouse context="minimize" button="-3">shade</Mouse>
```
It seems as though I have always been able to resize the window irregardless of which corner I chose, but honestly I have been using the keyboard to resize windows for quite some time, which is easier and faster for me and might be something you want to use.
Example:
```xml
	<Key mask="C4" key="Up">maxtop</Key>
	<Key mask="C4" key="Left">maxleft</Key>
	<Key mask="C4" key="Right">maxright</Key>
	<Key mask="C4" key="Down">maxbottom</Key>
```

**Comment by Obarun** [comment]
@israel, i didn't found the last release 2.4.0 at http://joewing.net/projects/jwm/releases/, maybe i don't use the good URL.
By the way, thanks for the tricks about mouse configuration. I use already keyboard to have "tiling", but sometime is good to be able to rezise the windows with the mouse.

**Comment by joewing** [comment]
The key binding to resize a window only does the bottom right corner.  Currently there's no key binding to select a different corner, though that is something that could be added.  Of course, it's possible to combine resize/move, but I could see someone who is trying to avoid using the mouse want a more key bindings.  This is something that would be fairly easy to add.

Unfortunately, the mouse bindings won't help with this, there would need to be additional key bindings introduced.

Version 2.4 isn't released yet (it's the version number selected for the next version).  The mouse bindings will only work with 2.4, not 2.3.7.

**Comment by joewing** [comment]
I forgot to mention previously, but the reason key bindings matter here is because in 2.4, key bindings and mouse bindings are shared to a certain degree.  So adding a "key" binding would make that action available to for mouse bindings as well.

**Comment by Obarun** [comment]
@joewing , thanks for your answer, i will wait for this new feature :)

**Comment by joewing** [comment]
As of snapshot 1651, it's possible to explicitly set which border you want to resize in a binding by suffixing with the side (`resize:ne` to resize the north-east corner, for example).
