### ISSUE TITLE
Can we specify the icon size for window buttons?

### ISSUE THREAD

**Issue by varmanishant** [joewing/jwm#412]
Does the ButtonClose, ButtonMax, ButtonMaxActive ButtonMin support resizing of any kind? It currently occupies the complete Window which is slightly large.

**Comment by technosaurus** [comment]
Maybe just add some transparent padding to your icons, unless what you really want is a thinner title bar which is configurable.  If those suggestions don't help, could you post a couple images: 1 of what you have and another indicating the prefered look.

**Comment by joewing** [comment]
I agree with @technosaurus.  It seems like you should be able to just modify the icon to show up the way you want or am I missing something?

**Comment by varmanishant** [comment]
It's okay I guess. Better to close it.

**Comment by varmanishant** [comment]
Thanks for looking into it.
