### ISSUE TITLE
[Feature request] Please add WM_NAME as match criteria for Group settings

### ISSUE THREAD

**Issue by willbprog127** [joewing/jwm#416]
Greetings!

I have a use case that causes some inconvenience when using Group settings.  When I do `xprop` on both the VirtualBox machine manager and a VirtualBox VM, the WM_CLASS name *and* class are always `VirtualBox` but the WM_NAME is more specific as to the window's function.  This causes both the VBox manager and VM to match my rule, and ends up removing the title and borders on the VBox manager, which I don't want.

I realize I should probably file a bug on the VBox site, but this feature request may come in handy for other programs run under JWM.

Is it possible to add matching for WM_NAME in Group settings?

Thank you! :smile:

**Comment by willbprog127** [comment]
Added comment to existing (four year old) VirtualBox bug report.

https://www.virtualbox.org/ticket/12534#comment:3

**Comment by rdnvndr** [comment]
See #265

**Comment by willbprog127** [comment]
@rdnvndr Thanks.  I did a search but that bug didn't come up.  I'll go ahead and close this since Joe doesn't want to do this.  Thanks! :smile:
