### ISSUE TITLE
Run one file every two hours (start file JWM)

### ISSUE THREAD

**Issue by kibojoe** [joewing/jwm#419]
hello all,
i would like to know if JWM (start file) understands that a file needs to run every two hours, for example:

**<StartupCommand>sleep 9s &amp;&amp; /usr/bin/kibojoe/upnotifier 7200 &amp;</StartupCommand>**

so it does not work! 
does anyone have any tips?

vlw fwi, Holmes :)

**Comment by STrRedWolf** [comment]
I think that's a job not for JWM or any window manager...  but for cron.

Does the program need to be run every two hours no matter if the user is logged in or not?  I assume this is on a PC you own and not a shared terminal at a university.

**Comment by yetanothergeek** [comment]
It looks like your command would cause JWM to hang for nine seconds at startup. Maybe you mean this?
```sh
( sleep 9s && /usr/bin/kibojoe/upnotifier 7200 ) &
```

**Comment by kibojoe** [comment]
hello all,
the upnotifier is a script to check for system updates
the operation is for a personal pc with logged in user
does not crash JWM, script works when you start the system, but not alert every two hours
i'll try the cron...

vlw fwi, Holmes :)

**Comment by STrRedWolf** [comment]
I definitely would put this in as a cron job and use an existing notification system to pop the notice up.

**Comment by joewing** [comment]
I'm not sure why it wouldn't work within JWM, the startup command thing really just runs the specified command in the background at startup.  I wouldn't think JWM would kill the command or anything.  More logging around it might help (within upnotifier, etc).

**Comment by kibojoe** [comment]
ok thank you @joewing @STrRedWolf @yetanothergeek 

vlw fwi, Holmes :)
