### ISSUE TITLE
Add ability to show hidden trays on keypress

### ISSUE THREAD

**Issue by codesardine** [joewing/jwm#424]
Is there a way i can show a hidden tray on keypress?

**Comment by joewing** [comment]
The `showtray` key binding does this.  Unfortunately, it doesn't make the tray stay visible for very long (the auto-hide timeout should be configurable, but it isn't).  Also, the binding applies to all trays if you have multiple.

**Comment by codesardine** [comment]
I think that should do the trick, i need to experiment with it, thanks.
