### ISSUE TITLE
Better image type detection

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#427]
Way back when, JWM would just try to load images using every library it knew about.  That was slow, so now JWM uses the file extension.  Unfortunately, file extensions don't necessarily tell the truth.  JWM should do something more intelligent, such as check the first few bytes of the file (using the appropriate image library to identity the file if possible).

Reported by Barry Kauler/the Puppy forums.

**Comment by technosaurus** [comment]
I have something at https://github.com/technosaurus/MIMEtype , but currently it does more than just image types and returns a specialized MimeType string.  Would you rather it just return an enum of supported image types?

**Comment by joewing** [comment]
A simple fix for this is in place where JWM will just attempt all understood formats if loading by file extension fails.  JWM logs a warning when this occurs so that the extension can be fixed.
