### ISSUE TITLE
Labels add space between text lines

### ISSUE THREAD

**Issue by codesardine** [joewing/jwm#428]
Can this be fixed, am trying to get space between the images and the text and align F keys so it looks nice.

It also be nice if we could add some space between text lines.

![jwmmenu](https://user-images.githubusercontent.com/4250006/33962423-68b7275a-e049-11e7-92f4-3180b75881e3.png)

```<RootMenu onroot="3">
    <Program 
      label="  Browser          - F1" 
      tooltip="Open Default Browser"
      icon="/usr/share/icons/Paper/48x48/apps/browser.png"
        >$JADE_BROWSER
    </Program>
    <Program 
      label="  File Manager     - F2"
      tooltip="Browse Your Files"
      icon="/usr/share/icons/Paper/48x48/places/folder_color_pink.png"
        >$JADE_FILE_MANAGER
    </Program> 
    <Program 
      label="  Software Center  - F3"
      tooltip="Install/Remove Applications"
      icon="/usr/share/icons/Paper/48x48/apps/software-store.png"
        >$JADE_SOFTWARE_INSTALLER
    </Program>
    <Program 
      label="  Manjaro Settings - F4"
      tooltip="Configure - Language/Kernel/Users/Time/Date/Keyboard/Hardware"
      icon="/usr/share/icons/Paper/48x48/categories/gnome-settings.png"
        >$JADE_SETTINGS
    </Program>
    <Program 
      label="  Terminal         - F5"
      tooltip="Use The Command Line"
      icon="/usr/share/pixmaps/hyper.png"
        >$JADE_TERMINAL
    </Program>
    <Program
      label="  Desktop          - F10"
      tooltip="Launch Desktop Environment"
      icon="/usr/share/pixmaps/jade-logo.svg"
        >jade-desktop
    </Program>
  </RootMenu>```

**Comment by joewing** [comment]
This is similar to issue #365.  As far as adding space between lines is concerned, I wonder if something like the ability to use the "separator" component with an invisible line would work?

**Comment by codesardine** [comment]
Hi Joe

An invisible separator might work, depending how wide it is or if we can define the heigh, if we could define the height of the line or even a margin bottom in pixels would be better, as the space between lines depends of the font used.

**Comment by technosaurus** [comment]
Is this happening even with fixed width fonts?

**Comment by codesardine** [comment]
I could add space to the images, but that would require to edit icon themes, or make separate images.

periods or underscores will kill a UI design to be honest.

I ended up going with this just because it looks a bit better.
![menu](https://user-images.githubusercontent.com/4250006/34025433-cb9b6fa8-e147-11e7-92c9-4bbb99ff8bea.png)

There is nothing wrong with this it works, but when you look at it closer, people read from left to right top to bottom, the main focus should be the words first then the keys and icons last, unfortunately i cant do that so this will have to do .for now

**Comment by technosaurus** [comment]
How about align="left|right|center"?  I would still put the shortcut info in the tooltip or leave them off and have a separate submenu called "Keyboard Shortcuts" that does your latest version.  The benefit of this is that  it can be "dynamic" in new versions of jwm so it can sync with your keyboard shortcut config tool and integrated into a help menu (which BTW should be the F1 shortcut by convention)

**Comment by codesardine** [comment]
I din'd think about the tooltip for the shortcuts that's a good idea :+1:
