### ISSUE TITLE
no titlebar or hide titlebar request

### ISSUE THREAD

**Issue by davidpaulos** [joewing/jwm#429]
the title-bar is usually used to help in moving/resizing whatever but as most of us have a keybind to do each of those things it becomes useless and as such i would like to ask/recommend as a user of this wm that an option be added to completely deactivate it like idk decoration="null" for example

love jwm keep up the awesome work

**Comment by codesardine** [comment]
Did you try notitle? in group settings, that should do the job.

**Comment by davidpaulos** [comment]
maybe but can i add everything to that group???? and also wouldn`t it be easier if we could do it it the widow decorations

**Comment by codesardine** [comment]
I think you can use Regex in the tag itself, @joewing should be able to explain that better that me

**Comment by davidpaulos** [comment]
you are totally right you can do it in the group options you just have to not put the Name tag like so 
<Group>
               <Option>notitle</Option>
</Group>

**Comment by davidpaulos** [comment]
you are tottaly right just dont put the name tag and it will assume all of them thanks
