### ISSUE TITLE
Tooltip delay not working

### ISSUE THREAD

**Issue by codesardine** [joewing/jwm#431]
Setting tooltip <delay>0</delay> seems that is not working, and I still have a delay before it appears.

**Comment by joewing** [comment]
This seems to be working for me:
```xml
    <PopupStyle delay="0">
        <Font>Sans-9</Font>
        <Foreground>#000000</Foreground>
        <Background>#999999</Background>
    </PopupStyle>
```

**Comment by joewing** [comment]
Ah, it doesn't work for the menu tooltip, only for the tray.  I should have a fix soon.

**Comment by joewing** [comment]
This should be fixed in snapshot 1660.

**Comment by codesardine** [comment]
Thanks :+1:
