### ISSUE TITLE
Option to disable window title icons

### ISSUE THREAD

**Issue by kazufukurou** [joewing/jwm#438]
Is there a way to disable window title icons but keep task list icons?

**Comment by Israel-D** [comment]
Yes.
Edit the TitleButtonOrder tag
here is mine:
```xml
<TitleButtonOrder>ximtw</TitleButtonOrder>
```
`w` stands for window icon, simply remove it like so:
```xml
<TitleButtonOrder>ximt</TitleButtonOrder>
```

**Comment by kazufukurou** [comment]
Thanks @Israel-D, I'm glad this feature is implemented, but it seems that not in current release 2.3.7. Will wait for next release.
