### ISSUE TITLE
Inactive label

### ISSUE THREAD

**Issue by mrgreenlinux** [joewing/jwm#448]
More of a question than an issue, looking at several .jwmrc files I see the Inactive label. Only it is not part of configuration on main site. Have checked my own files with 'jwm -p' and was getting errors. Was this part of an old version or has it simply been dropped (or even ever existed)?

**Comment by joewing** [comment]
It was part of the configuration in v2.2, see the configuration changes here: http://joewing.net/projects/jwm/release-2.3.shtml#v2.3.7

**Comment by mrgreenlinux** [comment]
Thanks so much ;-)
