### ISSUE TITLE
Please add config option to disable ShadeClient/UnshadeClient

### ISSUE THREAD

**Issue by dvhx** [joewing/jwm#451]
It is easy to accidentally shade window when scrolling near edge of window. This can be very confusing for older users, I disabled it by adding "return;" at the beginning of 2 functions in client.c

void ShadeClient(ClientNode *np) {
    return;
   ...

void UnshadeClient(ClientNode *np) {
    return;
   ...

But it would be nice to have this option in xml config file. Thanks.

**Comment by Israel-D** [comment]
@dvhx This option exists in the current JWM. See the [JWM documentation](http://www.joewing.net/projects/jwm/config-2.3.shtml#mouse)
You have more fine grained control over each part of the title bar now
```xml
<!-- to disable it globally -->
<RootMenu onroot="45"/>
<!-- to enable it in mouse context -->
<Mouse context="title" button="4">shade</Mouse>
<Mouse context="title" button="5">shade</Mouse>
```
