### ISSUE TITLE
how to disable the "shade" mode?

### ISSUE THREAD

**Issue by aicoutos** [joewing/jwm#452]
how to disable the "shade" mode to prevent accidental collapse?

**Comment by Israel-D** [comment]
@joewing It seems you should disable this option by default, and add a configuration option to enable it. Since there have been two similar issues about this back to back

@aicoutos add this simple line to your .jwmrc file
```xml
<RootMenu onroot="45"/>
```

**Comment by aicoutos** [comment]
@Israel-D this don't work, only freezes my desktop and need to restart to solve it.

**Comment by joewing** [comment]
@Israel-D In 2.4, things will work differently because of the mouse bindings.  I do plan to make that disabled by default though (it won't be included with the default mouse bindings).

@aicoutos What version of JWM are you running?

**Comment by aicoutos** [comment]
@joewing 2.3.5-2 with Ubuntu Xenial 16.04

**Comment by joewing** [comment]
Unfortunately, this feature wasn't really supported before v2.3.7 (it worked on some older versions of JWM, but that was only accidental).  See #366.
