### ISSUE TITLE
Use _NET_WM_WINDOW_TYPE in program groups

### ISSUE THREAD

**Issue by thabubble** [joewing/jwm#453]
Add tag `<Type/>` to `<Group/>`

**Comment by joewing** [comment]
My interpretation of the EWMH is that this should only be set by the client.  Maybe it would be ok to have JWM actually set it, but I'd rather adhere to the standard where possible.  This could be added in such a way that JWM just behaved as if the client had set a particular window type (though leave the actual window type alone).

**Comment by thabubble** [comment]
Sorry if I phrased it vaguely, what I meant was a tag that works in much the same way as <Name/> and <Class/>

**Comment by joewing** [comment]
Thanks for clarifying, that makes sense.  I like that idea!

**Comment by joewing** [comment]
This is available as of snapshot 1679 (thank you @rdnvndr!).
