### ISSUE TITLE
StartupCommand: starting GUI-based programs?

### ISSUE THREAD

**Issue by rytz2k** [joewing/jwm#456]
Hi:

Love JWM.  Simple and straight-forward.

Regarding the StartupCommand option: I can't seem to get any GUI/desktop-based applications to start.  Running console/shell-based commands works fine.

If I try to start up something like lxterminal or pidgin using the StartupCommand, nothing happens.  I don't have a problem running them from JWM menus (while in JWM).  I don't see the process listed with ps.  Must be failing on execution.

Is there something special that I need to do to get GUI/desktop applications to launch on startup?

My setup:
Slackware 14.2
Latest JWM

Thanks.

**Comment by rytz2k** [comment]
Thanks for the response.  I did try the & on my GUI programs but they don't pop up.  I tried running everything in a separate script as well but no change.

**Comment by yetanothergeek** [comment]
Strange, I just tried adding lxterminal & to my jwm startup script and it came up just fine.

**Comment by rytz2k** [comment]
Ugh.  Must be something system related.  I just tried with OpenBox and I have the same problem.

Any clues as to what might be causing this?  I'm guessing that something is preventing the programs from seeing $DISPLAY or it is not set.

**Comment by yetanothergeek** [comment]
You did chmod +x on your script, right? And it starts with #!/bin/sh or similar? You have full path to the script in your ~/.jwmrc with no typos?

Maybe you could put something like:
`lxterminal 2> ~/error.wtf`

And see if the output file gets created, and if it shows any errors.

**Comment by rytz2k** [comment]
Yeah. it's 775. Named it .jwmrc.startup_commands .

Tried getting output redirected to file, but not getting anything.  I know the script is being processed because I have two command-line programs that are getting executed before the GUI programs I'm trying to launch.

**Comment by Israel-D** [comment]
@rytz2k I have had some issues with starting things IF they all start running before X11
For example I use plank and pcmanfm in my startup... you can add a sleep .7 between each thing to see if that helps

**Comment by rytz2k** [comment]
Alright this turned out to be a silly problem with a simple fix.  Had to do with commands with ampersands and semicolons.  I was doing "<command> &;" which was causing problems within the script.  I need to experiment more but this is resolved.  Sorry for the confusion.

**Comment by rytz2k** [comment]
If anyone else is having issues trying to run multiple commands within the StartupCommand section, I had to use the following approach.  I wanted to be able to keep these commands within .jwmrc for simplicity:

`<StartupCommand>
       (
       COMMAND_THAT_FORKS;
       COMMAND_THAT_NEEDS_FORK &
       COMMAND_THAT_NEEDS_FORK &
       COMMAND_THAT_FORKS;
       )
   </StartupCommand>`
