### ISSUE TITLE
[minor irritant] invalid run time warning for WindowStyle <Font align="left">

### ISSUE THREAD

**Issue by Corin-EU** [joewing/jwm#460]
Not critical, or that important, but just irritating that something in the style file is being rerported  to be wrong when it is valid.

The manual page states

>  Font
                     The font used for title bars. See the FONTS  section  for
                     more   information.   This  tag  supports  the  following
                     attribute:

                     align
                            The window title  alignment.   Valid  options  are
                            left, right, and center.  left is the default.
 
However if the default value "left" is specified, eg

               <Font align="left">DejaVu Sans:bold:size=12</Font>

then JWM produces the warning message

             JWM: invalid text alignment "left"

The window title bar text is correctly aligned to the left, and the alternative values "center" and "right" do **not** produce a warning and work as expected.

Issue is present in v2.6.37 where noticed, and then with a download of latest s1679 and test run, is still seen to be present.

Quick scan of source code suggest warning is coming from src/parse.c

            if(JLIKELY(x >= 0)) {
               return x;
           } else {
              Warning(_("invalid text alignment: \"%s\""), attr);
            }

Speculation -- perhaps it could have something to do with JWMLIKELY (__builtin_expect) being used on a three way condition rather than simple (two condition) if/else ???

Reason for including default value -- because if attribute is already present in style file, it is so much simpler to do a string substitution with eg sed 's/Font align="left"/Font align="center"/ and back again, rather than more error prone insertion or deletion.

**Comment by joewing** [comment]
Thanks for reporting this.  The issue is that the "left" option is not sorted in the list and JWM uses binary search.

**Comment by joewing** [comment]
This should be in snapshot 1685.

**Comment by Corin-EU** [comment]
I have downloaded s1685, built and installed, and can confirm that the false warning message is no long displayed for Font align="left".

Thank you for resolving this issue.
