### ISSUE TITLE
Is it possible to configure font styles for menus?

### ISSUE THREAD

**Issue by paoloschi** [joewing/jwm#464]
According with the documentation, I understood that in _jwmrc_ the fonts can be configured for the contexts  `<WindowStyle>`, `<TaskListStyle>` and `<TrayStyle>`
Is it not available (or planned) the possibility of doing so in the same way for every single `<RootMenu>` that the user defines?

Otherwise, how can I now at least adjust the size (the _characters_ size, not the `height=` menu attribute space..)??

**Comment by Israel-D** [comment]
Here is my MenuStyle tag.
It gives the basics, but you can use all the Xfont stuff IIRC
```xml
<MenuStyle>
		<Font>serif-12:antialias=true:encoding=utf8:hinting=true</Font>
</MenuStyle>
```

**Comment by Israel-D** [comment]
You can also change color and opacity via the internal tags:
```xml
<Active>
			<Foreground>#ffffff</Foreground>
			<Background>#940000</Background>
		</Active>
		<Foreground>#ffffff</Foreground>
		<Background>#383838</Background>
		<Opacity>1.0</Opacity>
```

**Comment by paoloschi** [comment]
I apologize: I had missed the existence of the tag `<MenuStyle>`.. :-(
Would it be hypothetical, however, the interest for other users of the possibility of being able to adjust `<MenuStyle>` for each distinct _RootMenu_?

**Comment by paoloschi** [comment]
I close this my senseless intervention.
Sorry for the noise.
