### ISSUE TITLE
Re-add option to remove borders from maximized windows

### ISSUE THREAD

**Issue by ARR8** [joewing/jwm#470]
Per #392 and @technosaurus

The borders on every maximized window cause problems with certain applications, especially on touchscreen devices where bezel-in gestures are common. With these borders, they often end up resizing a window. Other problems include difficulty in using the scrollbar, and inability to distinguish maximized windows from windows which were not closed properly and take up the full screen when re-opened.

The proposed solution of using fullscreen instead of maximize has a few drawbacks:
- No titlebar
- Some programs (e.g. Firefox) have different behavior for fullscreen
- Some window management programs send a MAXIMIZE_RESTORE signal which this breaks
- Can't access the dock

Hopefully this can be added as a configuration option. If not, I am fine with applying a patch and compiling my own version, if possible. Thanks in advance.

**Comment by joewing** [comment]
I think it would be good to make this a group configuration option (`nomaxborders` or something, not sure what to call it).  There already is a `noborder` option, so I think just making that apply to maximized windows would work, though I haven't looked into this very closely yet.

**Comment by joewing** [comment]
There is now a "nomaxborder" group option. Please let me know if that does what you need. Thanks!
