### ISSUE TITLE
How to install jwm on puppy linux?

### ISSUE THREAD

**Issue by muktyas** [joewing/jwm#472]
I can not install on my puppy linux.
On previous version, i can do 
    configure --prefix=/usr
    make
    new2dir make install
But at this snapshot (1685) I dont see any configure script in that. I do ./autogen.sh but still got error. Thank you

**Comment by joewing** [comment]
Probably not relevant anymore, but I would guess the auto-tools are missing if autogen.sh fails. This shouldn't be a problem when configure exists (which it should for releases).
