### ISSUE TITLE
Arrows submenu indicator when menu is close to the right edge of the screen

### ISSUE THREAD

**Issue by paoloschi** [joewing/jwm#475]
In these cases, necessarily, the submenu window appears totally to the left of the root-menu but the arrow indicator remains on the right side. Really a quite negligible issue but, if not too programmatically complicated, it would be pleasant in these cases if even the arrow in the root-menu appeared on the left...

**Comment by yetanothergeek** [comment]
When navigating the menu with the keyboard, the right arrow key activates the sub-menu no matter which side it is displayed on, so having the arrow on the left side might be confusing to keyboard users.

**Comment by paoloschi** [comment]
Thanks to you for the brilliant observation, I hadn't really thought of that. At this point the thing would only be functional by also adding a user configurable switch option in jwmrc for that purpose otherwise better to leave things as they are
