### ISSUE TITLE
Keybinding using mouse button?

### ISSUE THREAD

**Issue by tomas** [joewing/jwm#488]
Hi @joewing and congrats on your work in jwm. Really like it.

I was wondering if I could add a keybinding using a mouse button. In particular, I want to use ctrl+scrollwheel for zooming in and out of the desktop. I'm using a customized version of `xzoom` for this, and currently calling it using `CA+Up` and `CA+Down`, but it would be far easier if I could just use the assigned scrollwheel (4 and 5). I tried using `CA+button4` or `CA+button 4` but no workie.

Thanks again!

**Comment by joewing** [comment]
Recent snapshots of JWM have "mouse bindings", which may let you do what you want.  Something like:
```xml
<Mouse context="root" button="4" mask="C">exec:xzoom</Mouse>
```

**Comment by tomas** [comment]
Awesome! What possible values can the `context` attribute have?

**Comment by joewing** [comment]
`context` determines where the binding is active.  It can be any of `root` for the root window, `title` for the title bar, `icon` for the window icon, `border` for the window border, `close` for the close button, `maximize` for the maximize button, or `minimize` for the minimize button.

**Comment by tomas** [comment]
Perfect! Thanks again.

**Comment by tomas** [comment]
@joewing Unrelated quick question: is it possible to modify the Alt+Right Click behaviour for resizing a window? When clicking on the upper-left portion of a window, I'd prefer to have the top-left corner of that window moved instead of the bottom-right one. Is this possible?

**Comment by joewing** [comment]
Unfortunately that's not possible right now, though it probably wouldn't be too difficult to implement.

**Comment by tomas** [comment]
I see. If you're interested I can help with that.

**Comment by tomas** [comment]
Hi @joewing, any plans to implement the new behaviour in alt+right click resizing?

**Comment by joewing** [comment]
I don't plan on implementing it any time soon, but feel free to dig in if you're interested!
