### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by JBHoren** [joewing/jwm#489]
Clicked on Clock (top tray, on right end), trying to get "exec:xterm ... -e cal -3" working (miss that drop-down calendar from Mint). JWM crashed twice. Here's from dmesg:

[ 3990.315970] jwm[564]: segfault at 4 ip 004d4097 sp bfa4d268 error 4 in jwm[4be000+3d000]
[ 3990.315986] Code: 7c 24 2c 89 54 24 04 89 5c 24 0c 65 a1 14 00 00 00 89 84 24 ec 00 00 00 31 c0 b8 ff ff ff ff 89 7c 24 14 83 ec 04 f3 ab 6a 00 <ff> 75 04 ff 75 00 e8 1e ff ff ff 8b 55 04 89 44 24 2c 83 c4 10 8b
[ 4147.476135] jwm[18606]: segfault at 4 ip 00424097 sp bfe9f268 error 4 in jwm[40e000+3d000]
[ 4147.476151] Code: 7c 24 2c 89 54 24 04 89 5c 24 0c 65 a1 14 00 00 00 89 84 24 ec 00 00 00 31 c0 b8 ff ff ff ff 89 7c 24 14 83 ec 04 f3 ab 6a 00 <ff> 75 04 ff 75 00 e8 1e ff ff ff 8b 55 04 89 44 24 2c 83 c4 10 8b

**Comment by rdnvndr** [comment]
The crashing of JWM does not reproduce. I use Arch Linux and last building of JWM.
