### ISSUE TITLE
window auto maximize?

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#49]
one of the things i miss from my times with other WMs and his very usefull specially if i use multiple screens to do some work his draging the window to another screen o even in same screen and if i droped the window at the very top end of the desktop the window wil auto maximize to full screen.

maybe this his something you like to implement it will be a usefull time saver.

**Comment by Israel-** [comment]
It might be nice to have options to maxleft maxright maxbottom maxtop in this same configuration....
as well as minimize/maximize
maybe configuration like:
```xml
 <WindowStyle>
        <Left>maxleft</Left>
        <Right>maxright</Right>
        <Top>maximize</Top>
        <Bottom>minimize</Bottom>
    </WindowStyle>
```

**Comment by technosaurus** [comment]
Perhaps using a regex on a group?

**Comment by joewing** [comment]
This is available as of snapshot 1464.
Currently, it's enabled by default and can be disabled with the `noaerosnap` group option.
