### ISSUE TITLE
Some tiled background jpeg files are more blurry and less crisp than after using xsetbg

### ISSUE THREAD

**Issue by shlomif** [joewing/jwm#490]
Hi!

I'm on mageia linux v7 x86-64 and when setting Background type="tile" for a Desktop, I get this - https://www.shlomifish.org/Files/files/images/jwm-jwmrc-bg.png whereas xsetbg gives me this - https://www.shlomifish.org/Files/files/images/jwm-xsetbg-bg.png - which looks much better. Here is the source image (SFW) - https://www.shlomifish.org/Files/files/images/lovely-red-fox.jpg . I noticed it with a different image as well (somewhat sketchy) - https://www.shlomifish.org/Files/files/images/hjZIPaw.jpg (originally from https://imgur.com/gallery/hjZIPaw ).

**Comment by shlomif** [comment]
Note that it does not seem to happen with the [gm convert](http://www.graphicsmagick.org/)ed jpg→png, so it may be a possible workaround

**Comment by JBHoren** [comment]
I did not know about GraphicsMagick. Impressive! יום ירושלים שמח

**Comment by shlomif** [comment]
@JBHoren : thanks for testing. gm is not unusual and there are many other apps that can do that, e.g: https://www.shlomifish.org/open-source/resources/graphics-programs/ . מועדים לשמחה.

**Comment by shlomif** [comment]
Here is a tentative fix for the issue, which just disables the scaling:

```
diff --git a/src/image.c b/src/image.c
index e4df522..b4ee67e 100644
--- a/src/image.c
+++ b/src/image.c
@@ -370,6 +370,7 @@ ImageNode *LoadJPEGImage(const char *fileName,
    /* Check the header. */
    jpeg_read_header(&cinfo, TRUE);
 
+#if 0
    /* Pick an appropriate scale for the image.
     * We scale the image by the scale value for the dimension with
     * the smallest absolute change.
@@ -387,6 +388,7 @@ ImageNode *LoadJPEGImage(const char *fileName,
       cinfo.scale_num = Max(1, Min(8, (ratio >> 2)));
       cinfo.scale_denom = 8;
    }
+#endif
 
    /* Start decompression. */
    jpeg_start_decompress(&cinfo);

```

It took me a while to figure out that was the issue.

**Comment by shlomif** [comment]
The tentative fix is now in a branch: https://github.com/shlomif/jwm/tree/issue490-tentative-fix--make-jpeg-not-blurry .
