### ISSUE TITLE
2.4.0 release?

### ISSUE THREAD

**Issue by tsutsui** [joewing/jwm#491]
Is there any plan or schedule for jwm 2.4.0 release?
It would be great especially for package systems that require official release tar balls.

Thanks,

**Comment by FrostKnight** [comment]
I agree, I have looked at 2.4 just now and installed it on my system, and it looks better than 2.3 :)

I love jwm, it really is the most reasonable, lightweight window manager out there. It uses the cpu, so little that dwm is no match. ;)

Thanks to the author of jwm for this awesome alternative to i3-wm. :)

**Comment by neandrake** [comment]
@FrostKnight do you have any tips on compiling 2.4? For 2.3.7 I'm able to download the source package from the website and compile that just fine, but when I try to compile the current state of this repository I've been running into issues. I'm compiling on CentOS7, per the steps in the readme:
```
[root@f8d877b67cb7 jwm]# ./autogen.sh
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.20 but this version
               is older. Please upgrade to gettext-0.20 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

I'm not sure wha tthe `AM_INIT_AUTOMAKE` issue is about, but the gettext version also seems odd -- I've tried compiling on Ubuntu distributions as well but not even Ubunutu seems to package a version of gettext newer than 0.19.

**Comment by FrostKnight** [comment]
You have to modify a bunch of stuff, for starters, you need to change the gettext version that is required to one your os supports. I am going to refresh myself so I can give you further info.

**Comment by FrostKnight** [comment]
Change configure.ac, that is where you need to make the gettext depend on 0.19,

MY OS has the same issue... ;)

Its working on transitioning to a huge massive update, thus I have the same problem.

once thats changed, ./autogen.sh
./configure or in my case configure prefix=/usr which you dont need to do, :)

make 

then doas make install 

that should be it.

**Comment by FrostKnight** [comment]
well in my case its doas for you it would be sudo heh.

**Comment by neandrake** [comment]
Thank you @FrostKnight! I was not expecting to be able to just change the dependency version like that, but changing to 0.19 does allow to complete compilation (as long as `gettext-devel` is installed.

**Comment by FrostKnight** [comment]
@neandrake I did something similar to get dosbox-x working without a new enough ffmpeg version. :P
And other software too... :)

My point? Sometimes being willing to try insane shortcuts works! :)

For software anyways... never try this for hardware like stuff though... like a friggin bios. :P

Anywho, glad it helped you! Keep this in mind for other types of software, it might help a lot!

**Comment by joewing** [comment]
Finally pulled the trigger on this one!
