### ISSUE TITLE
Tamil Fonts not rendering properly in title bar

### ISSUE THREAD

**Issue by lecramyajiv** [joewing/jwm#498]
I am running Debian stable 64bit.I  have  Installed all the Tamil Fonts and is rendering properly inside the browser but in the title bar it only displays  boxes for the font. I tried editing the jwmrc by adding the fonts but it didn't work, So how can I make it work.

**Comment by lecramyajiv** [comment]
After a lot of tinkering here is what i found out
1. Jwm doesn't give a damn about fontconfig
    a. If font is mentioned as Sans or Serif it either selects the default Latin font mentioned in the fontconfig or chooses the system      fonts.
2. If you need fallback font support make sure you use a font that covers various glyphs. For Tamil these fonts work
  a. Akshar Unicode [Wide range of support -Latin,Devanagari,Tamil, Telugu,  Kannada, Malayalam, Sinhalese]
  b. TSCu_Times supports  only Latin and Tamil
  c. Unifont CSUR. This font should be your ultimate last resort.

**Comment by joewing** [comment]
I think this should be fixed now (due to the use of pango). Please let me know if not.

**Comment by lecramyajiv** [comment]
I apologize for the late reply. I compiled the latest version in Debian Sid 64 bit in a virtual machine, and it renders Tamil and Devanagari Characters perfectly.  When  I ran ./autogen.sh  there are a couple of  non-fatal error, seems like there is already an open thread about it #262 . This is what I got when i ran ./autogen.sh
``
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
``
Another Issue is  <StartupCommand>  didn't work. I checked with the command jwm -p , it didn't report anything.Can you give me a hint or something on why it didn't work.

**Comment by joewing** [comment]
`StartupCommand` does work for me (easy to verify by setting a StartupCommand of something like `echo "test"`), are you sure the command is correct?

**Comment by lecramyajiv** [comment]
I added the ``top``  process to check if it runs at startup but it doesn't I also checked the `` journalctl ``  and with `` qps``  it seems as if the command isn't running. This is what I have in ``jwmrc``

``<StartupCommand>/usr/bin/qterminal -e /usr/bin/top</StartupCommand>``
``<StartupCommand>/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1</StartupCommand>
``

This is  my  ``./configure`` options when I compiled JWM 

`` ./configure  --enable-confirm --enable-icons --enable-png --enable-cairo --enable-rsvg --enable-jpeg  --enable-xft --enable-xrender --enable-pango --enable-xpm --enable-xbm --enable-shape --enable-xmu --enable-xinerama --enable-nls --enable-debug --with-x ``
 
Results of ``jwm -v ``  and   `` jwm -p``

``jwm -v``
``DEBUG: main.c[116]: debug mode started``
``JWM v2.4.0 by Joe Wingbermuehle``
``compiled options: confirm debug icons jpeg nls png shape svg xbm xft xinerama xpm xrender ``
``system configuration: /usr/local/etc/system.jwmrc``
``DEBUG: main.c[235]: debug mode stopped``
``DEBUG: MEMORY: no memory leaks``

Although I compiled with ``Pango`` it doesn't show  in the compiled options.

``jwm -p``
``DEBUG: main.c[116]: debug mode started``
``DEBUG: main.c[235]: debug mode stopped``
``DEBUG: MEMORY: no memory leaks``

You can checkout my sample [jwmrc](https://github.com/lecramyajiv/Emptydeeds/blob/master/.jwmrc)
