### ISSUE TITLE
Moving windows displays a small black screen with coordinates for x and y - can we hide it?

### ISSUE THREAD

**Issue by arcolinuxz** [joewing/jwm#500]
ArcoLinux is going to launch an iso just with JWM

![jwm](https://user-images.githubusercontent.com/36679406/79046620-65f48280-7c12-11ea-89c1-66785c7e619d.png)

We were wondering if you could help us. 

We were wondering if it is possible not to show the small tooltip like window with x and y coordinates.

See image

![coordinates](https://user-images.githubusercontent.com/36679406/79046598-43626980-7c12-11ea-8654-22b755048611.png)

**Comment by Israel-D** [comment]
It is really easy change these in your config

```

    <MoveMode coordinates="off">opaque</MoveMode>
    <ResizeMode coordinates="off">outline</ResizeMode>

```

coordinates="off" is what you need

**Comment by arcolinuxz** [comment]
that solved it
thanks for the quick response

**Comment by Israel-D** [comment]
No worries, that's what we're here for!
