### ISSUE TITLE
invalid Group Option: shaded

### ISSUE THREAD

**Issue by OgalFinklestein** [joewing/jwm#501]
Latest, current version **2.3.7** (although Ive experienced this error in earlier versions too).  Latest Debian 10.

https://joewing.net/projects/jwm/config-2.3.html#groups shows `shaded` as a valid option, but
I have 

> 119         &lt;Group>
> 120                 &lt;Name>pavucontrol&lt;/Name>
> 121                 &lt;Option>shaded&lt;/Option>
> 122                 &lt;Option>sticky&lt;/Option>
> 123         &lt;/Group>
 

`jwm -p` returns
**JWM: warning: .jwmrc[121]: invalid Group Option: shaded** and pavucontrol does not shade, but can be manually shaded.

Syntax seems pretty straightforward, but am I missing something?
Thanks.

**Comment by joewing** [comment]
Thanks! JWM wasn't parsing the tag properly. This should be fixed on master now.
