### ISSUE TITLE
No font fallback

### ISSUE THREAD

**Issue by szc126** [joewing/jwm#502]
JWM seems to use glyphs from only a single font.

For example, I have `<Font>-9</Font>` in `.jwmrc`, which produces the system default `sans` font at size 9. However, it only uses the first font defined as `sans`. This first font doesn't support $FOOBAR script, so I cannot see any $FOOBAR characters, only rectangles.

#498 and  #337 seem to be related.

**Comment by joewing** [comment]
Thanks! I updated JWM to use pango, which I believe should fix this issue (and hopefully #498 and #337).

**Comment by szc126** [comment]
It works!
