### ISSUE TITLE
SetDefaultCursor in AddClientToWindow overrides I-beam in newly created xterm windows

### ISSUE THREAD

**Issue by exikyut** [joewing/jwm#521]
Just a quick note to point out that

https://github.com/joewing/jwm/blob/fadba9a32765ed3765688ee093310e1e1a8c086a/src/client.c#L183

causes new xterm windows to have the default `left_ptr` cursor, when they should have an I-beam. IOW, this overrules xterm's cursor preference.

XTerm hides the mouse cursor when any key is pressed; if I do this then move the mouse to make the pointer disappear then reappear, it reappears correctly (with the I-beam). (This is because xterm switches between an internal invisible cursor and the `XC_xterm` cursor built into the X server :).)

Incidentally, xterm windows that existed on the screen before jwm was started seem to display an I-beam correctly! (...?)

Commenting out the `SetDefaultCursor()` in `AddClientToWindow()` causes all newly created xterm windows to show up with an I-beam, which is the behavior I experience with all other windowmanagers I've used over the years.

Out of curiosity I wondered what the canonical behavior I should expect would be (since I'm actually using jwm inside Xvnc while I learn about the X protocol... hence my OCD here), so I had a look at Openbox - which seems to not alter the client window's cursor in any way.

OB uses `XSetCursor` in only one place, [`screen_set_root_cursor()`](https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/screen.c#L1879), which (as the function name suggests) only alters the cursor for the root window. A quick search finds this function only being used at initial startup and during startup notification events.

To handle resize and move cursors the [`frame_adjust_cursors()`](https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/frame.c#L890) function uses a giant bunch of `XChangeWindowAttributes` calls to apply the appropriate cursor(s) based on current window state. (In other news I just learned that Openbox [creates a massive pile of subwindows](https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/frame.c#L123) for each of the various regions in the window frame. Yeow.)

Finally to handle resize and move events OB [grabs the cursor](https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/moveresize.c#L177) X-server-wide, which of course does not alter any specific window.

I'm guessing the correct fix for this is to somehow apply the default cursor selection to the parent window, but not the reparented child window. I have no idea how to do that. :)

Until then, leaving the noted call commented out seems to not be breaking too much. Identifying whichever bug or inconsistency that it fixed, if any, would probably be interesting - if it was done "just to be sure", maybe it can be removed.

Thanks for jwm!

**Comment by joewing** [comment]
Thanks for such a detailed report!
That particular change goes back 16 years, so probably back to when I initially imported this to SVN. I don't recall there being a particular reason for doing that. My guess is either that it either addresses some issue with an IRIX application back in the day or that the reason for doing so is no longer relevant. In any case, removing that line seems to fix the issue so I think I'm just going to do that.
