### ISSUE TITLE
Can't start JWM with startx or manually

### ISSUE THREAD

**Issue by acoolstraw** [joewing/jwm#529]
I downloaded the latest release, installed the dependencies and ran all the commands. JWM is installed in `/usr/local/bin` but for some reason running `startx` doesn't start it anymore.

My `xinitrc` is just the one from `/etc/X11/xinit/xinitrc` with `exec jwm` at the end. It used to work with the Debian package on another install.

Running it manually just says
`error: could not open display`

**Comment by acoolstraw** [comment]
Nope, I tried all of those and they all either say could not open display or they open a frozen prompt (what startx does)

jwm -p returned no errors

**Comment by joewing** [comment]
For development, I'll usually have startx or whatever start an `xterm` as the window manager and then run JWM from the xterm. If X still refuses to start, that removes JWM from the equation. Otherwise, you should be able to see why JWM doesn't start.
