### ISSUE TITLE
autogen does not find the current gettext

### ISSUE THREAD

**Issue by tim042849** [joewing/jwm#533]
When attempting to install jwm for ubuntu 20.04, the following is generated:
```
~/Downloads/gettext-0.20.1$ 
tim@mini:~/Downloads/jwm-2.4.0$ ./autogen.sh 
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.20 but this version
               is older. Please upgrade to gettext-0.20 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
tim@mini:~/Downloads/jwm-2.4.0$ gettext --version
gettext (GNU gettext-runtime) 0.20.1
Copyright (C) 1995-2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.

```
A current version of gettext that should be acceptable to autogen is indeed in my system at /usr/local/bin,
however it appears to autogen is querying the older version
```
tim@mini:~/Downloads/jwm-2.4.0$ which -a gettext
/usr/local/bin/gettext
/usr/bin/gettext
/bin/gettext
```
Please advise on how to proceed regarding this matter and the others referenced above. I am new to autogen.
thanks
tim

**Comment by joewing** [comment]
There are a few options:
* Probably the easiest is to download the latest release tarball for 2.4.0 (it should be pretty up-to-date), and not bother with autogen.sh.
* You could instead update configure.ac to request the version of gettext for your system (the AM_GNU_GETTEXT_VERSION line).
* You could try updating your system's gettext (rather than installing in /usr/local). I'd be careful doing that though.

**Comment by tim042849** [comment]
Hello Joe:
I choose your first option and downloaded jwm-2.4.0.tar.xz
Ignored autogen as you suggested.
configured, compiled and installed without complaint.
Thanks very much
tim
