### ISSUE TITLE
icons with a dot (.) in the filename are not found

### ISSUE THREAD

**Issue by JWMKit** [joewing/jwm#536]
**Summary** : JWM does not find images with a dot (.) in the filename when searching the iconpaths unless the file extension is specified.

**Version**: jwm v2.4.0
compiled options: confirm icons jpeg nls pango png shape svg xbm xft xinerama xpm xrender

**Expected behavior**
Users can reference an icon by it's filename only. No extension, or path is needed because JWM searches the IconPaths defined in jwmrc. 

For example with the iconpath "$HOME/.local/share/icons/" declared in jwmrc we can reference the file $HOME/.local/share/icons/utilities-terminal.svg in a menu item or traybutton with the icon attribute like this:  icon="utilities-terminal"

**Unexpected behavior** (The Problem)
Images with a filename containing a dot (.) are not found unless you specify the the extension.

To demonstrate rename the file by changing the dash to a dot in the file so we now have this:
$HOME/.local/share/icons/utilities.terminal.svg

You would expect the same behavior for this  file, but apparently the dot (.) in the filename confuses it. So you must add the file extension .svg for JWM to find it. Like this:
icon="utilities.terminal.svg"

**Comment by joewing** [comment]
Thanks, this should be fixed in master now for the next release.
