### ISSUE TITLE
Icon + Label in TaskButton results in chopped text.

### ISSUE THREAD

**Issue by keshto** [joewing/jwm#542]
![image](https://user-images.githubusercontent.com/766237/151233106-36f6e556-460d-4e41-8973-59bf4c27489a.png)
Please see others having same issue (picture from here as well): https://www.antixforum.com/forums/topic/jwm-menu-button-in-taskbar-is-weird/

I tried setting the label to 2-5+ characters and all are chopped. In fact, with only 2 characters the resulting label is "..." only.

**Comment by joewing** [comment]
I think this is a dup of #534, which should be fixed in master (to be in 2.4.1).

**Comment by keshto** [comment]
Yep sorry about the duplication and thanks for the fix :heart:
