### ISSUE TITLE
[Bug] Alt+tab being assigned even when not assigned in jwmrc

### ISSUE THREAD

**Issue by keshto** [joewing/jwm#543]
This is on a Debian packaged jwm (might be different other places?).
My jwmrc has no binding for alt+tab and would like to use that keybinding to use https://github.com/sagb/alttab while we wait on https://github.com/joewing/jwm/issues/334. However, when running alttab, I get:
`alttab: Error while (un)grabbing key 0x17 with mask 0x8/0x12.
Probably other program already grabbed this combination.
Check: xdotool keydown alt+Tab; xdotool key XF86LogGrabInfo; xdotool keyup Tab; sleep 1; xdotool keyup alt
and then look for active device grabs in /var/log/Xorg.0.log
...`
One can see that indeed jwm is using this keybinding although not assigned.

**Comment by joewing** [comment]
The reason for this behavior is that JWM assigns alt-tab by default, though it probably should not. The offending line is here:
https://github.com/joewing/jwm/blob/master/src/default.c#L20

**Comment by keshto** [comment]
I think that is a sane default. However, if there is a .jwmrc (user defined) and it is not set then don't apply any of the defaults.

**Comment by joewing** [comment]
The defaults that are built into JWM are really intended as a failsafe in case you don't have a configuration file. The example configuration already includes these bindings. So I removed them from the code.

**Comment by keshto** [comment]
Makes sense. Could we do a "if no config file use defaults else expect user to know what they doing"?

It sorta surprising when one don't have a keybinding and that combination is taken, especially by something that is configurable and defined in config file.

Will give the changes a run. Seems like it just close and switch windows you removed opposed to above logic which should be fine for my use case,  but I see in future maybe the other defiant keybinding that are defined differently in someone's config will went to be used.

Thanks again!

**Comment by keshto** [comment]
I don't know if those mouse bindings and arrow, ESC, return keys will have same effect as the alt+tab did in the BASE_CONFIG. If not then, don't mind me :)

**Comment by joewing** [comment]
The alt bindings are special because JWM needs to grab them on all windows. Those other bindings are only grabbed when a menu is shown, etc. So they shouldn't interfere with anything, though I could remove them too if they cause problems somehow.
The mouse bindings are essentially what was there before mouse bindings were a thing in 2.4, so I suspect they won't cause any surprises unless they aren't there... and in that case it would be quite surprising for the mouse to not work after an upgrade (I suspect many bug reports would follow).

**Comment by keshto** [comment]
Thanks for the context. Will close this one out. I think the commit you made should solve it. Will check, and reopen if it is still an issue.
