### ISSUE TITLE
[Feature request/bug?] Taking action on a notification does not got to workspace.

### ISSUE THREAD

**Issue by keshto** [joewing/jwm#549]
When a notification appears and one clicks on the action to go to the window instead of going to that workspace the window is moved from it's workspace to the current workspace.

**Comment by joewing** [comment]
Does using the `fixed` group option provide the desired behavior? That should maybe be the default...
```xml
<Group>
  <Option>fixed</Option>
</Group>
```

**Comment by keshto** [comment]
:facepalm: it does exactly what is expected. My bad, sorry for not reading through all the options. I agree it should be a default. Sorry again
