### ISSUE TITLE
Move command invoke by key binding crashes JWM

### ISSUE THREAD

**Issue by tim042849** [joewing/jwm#550]
jwm v2.4.0 on ubuntu 20.04
With an example keybinding such as
`<Key mask="C4" key="u">move</Key>`
invoking ctrl-super-u where super is mod4, jwm crashes and exists to the login screen.
Other bindings have yielded the same result. super-alt-m was used previously with crash as well.
Since I prefer the keyboard where possible (over a pointing device), resolving this is of some
interest to me. I note that using the pointing device or invoking the menu through some keybinding,
then scrolling to select move works fine too. 
What am I doing wrong?
Thanks
Tim

**Comment by joewing** [comment]
I'm having trouble reproducing this. I tried binding `move` with v2.4.0 as well as with the most recent changes. Some questions to help narrow it down:
* Does it happen every time you invoke the binding?
* Does it happen only with `move` or also with `resize` (another binding that requires additional interaction)?
* What about something like `close` (a binding that affects a window, but requires no additional interaction)?
* What about `rdesktop` (a binding that does not require a window at all)?
* Does it happen only if the mouse is over a window, not over a window, there are no windows, etc?

If I could get a stack trace, that would be most useful. If you set your window manager to be `xterm` for example, then you can run `gdb jwm` from the terminal. Then run `run` to start JWM. After JWM crashes, the terminal should keep X alive and you can run `bt` to get the stack trace. I'm guessing though, that JWM was compiled without the `--enable-debug` option to `configure`, so it would be more useful if JWM is re-compiled from source with `./configure --enable-debug`.

**Comment by tim042849** [comment]
Answering Joe's questions:
The crash happens every time I invoke the binding. 
Resize as a keybinding does not respond but does not crash either. as with move, it works as advertise with the menu.
rdesktop works fine.
move crashes jwm in all circumstances as Joe mentions in his last question.
It will take me a day or two to to address and enable the instructions for stack trace. Thanks for the thorough and quick reply.

**Comment by tim042849** [comment]
Duh. No more problem. It all works. jwm.desktop was pointing to /usr/bin/jwm which is ver 2.3.7 
I changed the Exec parameter to /usr/local/bin/jwm and now everything I have observed to have been malfunctioning now
works. I compiled jwm some time ago and obviously forgot to change the Exec argument.

**Comment by joewing** [comment]
Good to hear. Thanks for reporting back!
