### ISSUE TITLE
Text not appearing in application

### ISSUE THREAD

**Issue by Ranbato** [joewing/jwm#594]
I maintain a Docker image for [Vorta](https://github.com/borgbase/vorta) built on top of @jlesage's image [baseimage-gui](https://github.com/jlesage/docker-baseimage-gui).  The latest version of the base image has moved to JWM and when I upgrade I am not seeing any text in the UI.  I've tried adding various optional libraries without success.
The only suspect thing I've found is the following in the logs
`QFont::setPointSizeF: Point size <= 0 (-0.750000), must be greater than 0`

Any pointers for how to resolve?  Here is my [dev branch](https://github.com/borgbase/vorta-docker/tree/jlesage-v4) if someone wants to try the actual image I am working with but I suspect it can be reproduced with Vorta itself though I haven't been able to try yet since all my Linux boxes are headless.

Thanks

CC @m3nu

**Comment by jlesage** [comment]
@Ranbato, I think your issue might be that you don't have any font installed.  Try to install the package `font-croscore` to see if it helps.

**Comment by Ranbato** [comment]
Thanks, that was it.  Didn't even think to check for fonts. 😞
