### ISSUE TITLE
New release? :)

### ISSUE THREAD

**Issue by crftbt** [joewing/jwm#612]
With 18 commits since the 2.4.3 release 2 years ago, are there any plans for a new release? :)

**Comment by joewing** [comment]
I think there are really only a couple changes since 2.4.3 at this point, but there's no point in postponing a release. I'll try to push one out in the next week or so.

**Comment by achadwick** [comment]
I see there are two `v[.]2.4.3` tags, but one is described as "v2.4.4", by the program itself as well as its tag description on here. Should we make the new version's tag[s] `v[.]2.4.5` just in case some downstream packager has got it wrong (or right) (I'm not even sure myself now!)

**Comment by purpasmart96** [comment]
@joewing 
Any updates? I would love to see the new version in Debiab trixie before the freeze.

**Comment by joewing** [comment]
No updates, so I guess assuming nothing major pops up, I'll try to get a release out this weekend.

**Comment by joewing** [comment]
v2.4.5 is published. Let me know if you find any problems! Thanks!
