### ISSUE TITLE
Background colours broken

### ISSUE THREAD

**Issue by bkauler** [joewing/jwm#640]
EasyOS is currently using jwm 2.4.2
I thought should update, did so, but found background colours are wrong. It seems this is due to a syntax change.
So, have stayed with 2.4.2.

We have been through this before. EasyOS, Puppy Linux and derivatives have lots of jwm theme PET packages, and the last major syntax change we had to update many of them. Don't want to do it again.

**Comment by joewing** [comment]
There shouldn't be a syntax change between 2.4.2 and 2.4.5. This is for desktop backgrounds? Is there a small config snippet to demonstrate the problem?

**Comment by bkauler** [comment]
Sorry, I made a mistake, seems I was accidentally using an older jwm theme PET package.
Sorry for wasting your time, closing this issue.

**Comment by bkauler** [comment]
No, I am correct, found the wrong colour...

**Comment by bkauler** [comment]
When an app is minimized, its background colour is wrong. This is jwm 2.4.4 and the two minimized in the tray have a dark-brown background:
![jwm-2 4 4-wrong-bg](https://github.com/user-attachments/assets/f7824152-8c32-43bf-a24b-1a33babb6050)

**Comment by bkauler** [comment]
I restarted X with jwm 2.4.2, now minimized apps are the correct colour. In this snapshot, Chromium is minimized and it is the expected dark blue background:
![jwm-2 4 2-ok-bg](https://github.com/user-attachments/assets/fc3488c3-f866-4f7e-aec0-b1f87487a38d)

**Comment by bkauler** [comment]
Here is the fragment:

```
	<TaskListStyle>
		<Font>Open Sans-12</Font>
		<Active>
			<Foreground>#edf9ff</Foreground>
			<Background>#3761b6</Background>
		</Active>
		<Background>#72c8eb</Background>
		<Foreground>#304a9f</Foreground>
	</TaskListStyle>

```

**Comment by joewing** [comment]
Thanks! I see the problem. A new feature inadvertently broke this (minimized window styles). It's an easy fix though.

**Comment by joewing** [comment]
The fix is merged. I'll try to get a release out within a week or so.
