### ISSUE TITLE
Enhancement- new language .po's for JWM

### ISSUE THREAD

**Issue by scsijon** [joewing/jwm#67]
I started a topic on the puppy forum for new JWM .po's for you as you only seem to have a few there at present.

The url is: http://www.murga-linux.com/puppy/viewtopic.php?p=710535#710535

there are es and nl at present, but more will appear.

are there any you especially want?

regards
scsijon

**Comment by joewing** [comment]
I'm closing this since there hasn't been any activity on this for a while.  I certainly welcome additional translations and updates to existing translations (via pull request if possible)!
