### ISSUE TITLE
Window position group settings

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#79]
This request is for two additional group settings: "x" and "y".  The "y" setting should fix the y-coordinate for a window and the "x" setting should fix the x-coordinate for a window.

**Comment by J-Reis** [comment]
Agreed, this would be a very useful addition!

**Comment by fedemp** [comment]
Please let `x` and `y` accept negatives values, relative to the right and bottom of the screen. I'm currently launching a calendar from the clock in the system tray.

**Comment by joewing** [comment]
This is available in snapshot 1572.

**Comment by willbprog127** [comment]
Thanks Joe!  👍
