### ISSUE TITLE
request: menu tooltips and cli messages

### ISSUE THREAD

**Issue by technosaurus** [joewing/jwm#83]
the .desktop files have a Comment= section that is ideally suited to menu tooltips and would look much nicer to just have "My App" in the menu with a mouseover description than "My App - a really long description of My App"

The advent of the -reload command made it possible to have pseudo apps built into a jwm menu that can be updated with -reload ... I have done a drive mounter/unmounter/<whatever action> and a basic package manager, but...
It would be helpful if there were an additional arg -message that could be passed on start/restart/reload that comes up ... like "Welcome to jwm on Puppy Linux" / "'Drives Updated" / "Packages synced" or simply "jwm Menus reloaded"

.... btw the package manager is way more responsive than any other GUI tools - jwm menus are extremely fast ... too bad 9 is the limit

**Comment by Israel-** [comment]
@technosaurus fortunately now 9 menus is not the limit.  I agree JWM menus are the FASTEST menus around hands down

**Comment by joewing** [comment]
As of JWM v2.3.3, menu tooltips are supported.  Also, as of JWM v2.3.0, there can be up to 36 menus (0-9 and a-z).
I'll open a separate issue to add support for custom dialog windows (issue #249).
