### ISSUE TITLE
Vertical tray doesn't expand full screen.

### ISSUE THREAD

**Issue by STrRedWolf** [joewing/jwm#94]
Using the following for my tray, as I'm looking for a old-style NeXTstep look.

```
<Tray  x="-1" y="0" width="48" autohide="false" layout="vertical">
```

Instead of stretching down the full height of the display (all 1080 pixels) it stays tucked into the corner.  Am I doing this wrong?  I'm on version 2.1 on a Gentoo box.

**Comment by Israel-** [comment]
Hi I just tested this in 1208.
I tried doing what @STrRedWolf suggested setting the height to 1050 on my 1680X1050
I only have TrayButton in my Tray and instead of spanning the entire length it moves to the upper corner

```xml
<Tray layout="vertical" valign="center" halign="left" autohide="left" layer="above" height="1050">
<!-- TrayButtons -->
</Tray>
```

**Comment by joewing** [comment]
The issue is that tray buttons are fixed size components, so JWM will shrink the tray to fit them.  To make the tray larger, you need a component that fills vertically to use up the space (a "Spacer" component, for example).

**Comment by Israel-** [comment]
Correct,
I tested this and it is indeed working as intended!
I think you can close this bug.
