### ISSUE TITLE
REQ Dock configuration

### ISSUE THREAD

**Issue by STrRedWolf** [joewing/jwm#95]
Outside of my other issue here on Github... I am liking JWM very much.  It's got 90% of what I'm looking for, and I can deal with that.  I can get it to a NeXTstep-like configuration.

However, is there a way to expand the icons in the dock to like 20px by 20px, or even better make that size configurable?

**Comment by joewing** [comment]
I don't know if there is more to do on this. Please re-open if there is still something missing.
